#!/usr/bin/env python3

from __future__ import annotations

import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

from . import events as events_mod
from . import xcbxml
from .common import Emit
from .errors import emit_errors_module
from .events import EventStructType, EventType
from .request import RequestType
from .resolver import Resolver
from .simple import SCALAR_TYPES, EnumType, EnumWireType
from .struct import StructType
from .union import UnionType
from .xid import XidUnionType, make_xid_type


@dataclass(frozen=True)
class Module:
    name: str
    header: str
    extension_xname: str | None
    extension_name: str | None
    is_core: bool
    enums: tuple[EnumType, ...]
    xid_unions: tuple[XidUnionType, ...]
    structs: tuple[StructType, ...]
    unions: tuple[UnionType, ...]
    eventstructs: tuple[EventStructType, ...]
    events: dict[str, EventType]
    errors: tuple[xcbxml.Error | xcbxml.ErrorCopy, ...]
    requests: tuple[RequestType, ...]
    resolver: Resolver

    def extension_enum_name(self) -> str:
        if self.is_core:
            return 'CORE'
        name = self.extension_xname or self.extension_name or self.header
        name = name.replace('-', '_').upper()
        overrides = {'XINPUTEXTENSION': 'XINPUT'}
        return overrides.get(name, name)

    def global_tagged_prefix(self) -> str:
        if self.is_core:
            return ''
        assert self.extension_name
        overrides = {'xkb': 'Xkb'}
        return overrides.get(self.extension_name, self.extension_name)

    @staticmethod
    def from_schema(
        name: str,
        bindings: xcbxml.Bindings,
        resolver: Resolver,
        is_core: bool,
    ) -> Module:
        enums: list[EnumType] = []
        xid_unions: list[XidUnionType] = []
        structs: list[StructType] = []
        unions: list[UnionType] = []
        eventstructs: list[EventStructType] = []
        events: dict[str, EventType] = {}
        errors: list[xcbxml.Error | xcbxml.ErrorCopy] = []
        requests: list[RequestType] = []

        for decl in bindings.decls:
            if isinstance(decl, xcbxml.XidType):
                resolver.set(decl.name, make_xid_type(decl.name, enums))

        for decl in bindings.decls:
            if isinstance(decl, xcbxml.Enum):
                try:
                    existing = resolver.get_local(decl.name.upper())
                except KeyError:
                    enums.append(resolver.set(decl.name, EnumType.from_schema(decl)))
                else:
                    if not isinstance(existing, EnumWireType):
                        raise NotImplementedError('enum name collides with non-xid type')
                    existing.enum_type.add_items_from_schema(decl)

        for decl in bindings.decls:
            if isinstance(decl, xcbxml.TypeDef):
                resolver.set(decl.name, resolver.get(decl.alias))
            elif isinstance(decl, xcbxml.XidUnion):
                xid_unions.append(resolver.set(decl.name, XidUnionType.from_schema(decl, resolver)))
            elif isinstance(decl, xcbxml.Struct):
                structs.append(StructType.from_schema(decl, resolver))
            elif isinstance(decl, xcbxml.Union):
                resolver.set(decl.name, UnionType.from_schema(decl, resolver))
                unions.append(resolver.set(decl.name, UnionType.from_schema(decl, resolver)))
            elif isinstance(decl, xcbxml.EventStruct):
                eventstructs.append(resolver.set(decl.name, EventStructType.from_schema(decl)))
            elif isinstance(decl, xcbxml.Event):
                events[decl.name] = resolver.set(
                    f'{decl.name}Event', EventType.from_schema(decl, resolver)
                )
            elif isinstance(decl, xcbxml.EventCopy):
                events[decl.name] = events[decl.ref].copy_as(decl)
            elif isinstance(decl, xcbxml.Error | xcbxml.ErrorCopy):
                errors.append(decl)
            elif isinstance(decl, xcbxml.Request):
                requests.append(RequestType.from_schema(decl, resolver, is_core=is_core))

        return Module(
            name=name,
            header=bindings.header,
            extension_xname=bindings.extension_xname,
            extension_name=bindings.extension_name,
            is_core=is_core,
            enums=tuple(enums),
            xid_unions=tuple(xid_unions),
            structs=tuple(structs),
            unions=tuple(unions),
            eventstructs=tuple(eventstructs),
            events=events,
            errors=tuple(errors),
            requests=tuple(requests),
            resolver=resolver,
        )

    def emit(self) -> str:
        events_mod.resolve_types(self)
        emit = Emit()
        emit('// zig fmt: off')
        emit('// This file is generated by `python -m genproto`')
        emit()
        emit('const std = @import("std");')
        emit('const wire = @import("../_wire.zig");')
        emit('const extensions = @import("../_ext.zig");')
        if self.events:
            emit('const DecodeError = @import("../_errors.zig").DecodeError;')
            emit('const global_events = @import("events.zig");')
        for module_name in sorted(self.resolver.touched_imports):
            emit(f'const {module_name} = @import("{module_name}.zig");')
        emit()

        emit('const current_mod = struct {')
        with emit.block():
            ext_value = 'null' if self.is_core else f'.{self.extension_enum_name()}'
            emit(f'const extension: ?extensions.Extension = {ext_value};')
        emit('};')
        emit()

        for enum in self.enums:
            enum.emit_definition(emit)
            emit()

        for xid_union in self.xid_unions:
            xid_union.emit_definition(emit)
            emit()

        for struct in self.structs:
            struct.emit_definition(emit)
            emit()

        for union in self.unions:
            union.emit_definition(emit)
            emit()

        for eventstruct in self.eventstructs:
            eventstruct.emit_definition(emit)
            emit()

        for request in self.requests:
            request.emit_definition(emit)
            emit()

        events_mod.emit_definitions(emit, self, list(self.events.values()))

        return emit.render()


def load_bindings(path: Path) -> xcbxml.Bindings:
    root = ET.parse(path).getroot()
    bindings = xcbxml.root_item.match(root)
    return bindings


def make_module_resolver(
    module_name: str,
    bindings: xcbxml.Bindings,
    modules_by_name: dict[str, Module],
) -> Resolver:
    imports: dict[str, Resolver] = {}
    for name, module in modules_by_name.items():
        if module.is_core or name in bindings.imports:
            imports[name] = module.resolver

    return Resolver(
        module_name=module_name,
        types=dict(SCALAR_TYPES),
        imports=imports,
        touched_imports=set(),
    )


def load_module(path: Path, modules_by_name: dict[str, Module], is_core: bool) -> Module:
    bindings = load_bindings(path)
    resolver = make_module_resolver(path.stem, bindings, modules_by_name)
    return Module.from_schema(path.stem, bindings, resolver, is_core=is_core)


def load_modules(core_xml_path: Path, extension_xml_paths: Sequence[Path]) -> list[Module]:
    modules_by_name: dict[str, Module] = {}
    modules = []
    core_module = load_module(core_xml_path, modules_by_name, is_core=True)
    modules.append(core_module)
    modules_by_name[core_module.name] = core_module
    for xml_path in extension_xml_paths:
        module = load_module(xml_path, modules_by_name, is_core=False)
        modules.append(module)
        modules_by_name[module.name] = module
    return modules


def generate(
    directory: str | Path,
    core_xml_filename: str,
    extension_xml_names: Sequence[str],
    output_directory: str | Path,
    ext_import: str = '../_ext.zig',
) -> list[Path]:
    xml_directory = Path(directory)
    out_directory = Path(output_directory)
    out_directory.mkdir(parents=True, exist_ok=True)

    core_xml_path = xml_directory / core_xml_filename
    extension_xml_paths = [xml_directory / name for name in extension_xml_names]
    modules = load_modules(core_xml_path, extension_xml_paths)

    written: list[Path] = []
    for module in modules:
        out_path = out_directory / f'{module.name}.zig'
        out_path.write_text(module.emit() + '\n')
        written.append(out_path)

    errors_path = out_directory / 'errors.zig'
    errors_path.write_text(emit_errors_module(modules, ext_import=ext_import) + '\n')
    written.append(errors_path)

    events_path = out_directory / 'events.zig'
    events_path.write_text(events_mod.emit_events_module(modules, ext_import=ext_import) + '\n')
    written.append(events_path)

    return written
