#!/usr/bin/env python3

from __future__ import annotations

import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path

from . import events as events_mod
from . import xcbxml
from .common import Emit, Resolver
from .errors import emit_errors_module
from .events import EventType
from .request import RequestType
from .simple import SCALAR_TYPES, EnumType
from .struct import StructType
from .union import UnionType
from .xid import XidType, XidUnionType

DEFAULT_XML_PATH = Path('genproto/testdata/toy.xml')
DEFAULT_OUT_PATH = Path('src/gen/toy.zig')


@dataclass(frozen=True)
class Module:
    header: str
    xid_types: tuple[XidType, ...]
    enums: tuple[EnumType, ...]
    xid_unions: tuple[XidUnionType, ...]
    structs: tuple[StructType, ...]
    unions: tuple[UnionType, ...]
    events: dict[str, EventType]
    requests: tuple[RequestType, ...]

    @staticmethod
    def from_schema(bindings: xcbxml.Bindings, resolver: Resolver) -> Module:
        xid_types: list[XidType] = []
        enums: list[EnumType] = []
        xid_unions: list[XidUnionType] = []
        structs: list[StructType] = []
        unions: list[UnionType] = []
        events: dict[str, EventType] = {}
        requests: list[RequestType] = []

        for decl in bindings.decls:
            if isinstance(decl, xcbxml.XidType):
                xid_type = XidType.from_schema(decl)
                resolver.set(decl.name, xid_type)
                xid_types.append(xid_type)
            elif isinstance(decl, xcbxml.TypeDef):
                resolver.set(decl.name, resolver.get(decl.alias))
            elif isinstance(decl, xcbxml.Enum):
                enum = EnumType.from_schema(decl)
                resolver.set(decl.name, enum)
                enums.append(enum)
            elif isinstance(decl, xcbxml.XidUnion):
                xid_union = XidUnionType.from_schema(decl, resolver)
                resolver.set(decl.name, xid_union)
                xid_unions.append(xid_union)
            elif isinstance(decl, xcbxml.Struct):
                structs.append(StructType.from_schema(decl, resolver))
            elif isinstance(decl, xcbxml.Union):
                union = UnionType.from_schema(decl, resolver)
                resolver.set(decl.name, union)
                unions.append(union)
            elif isinstance(decl, xcbxml.Event):
                events[decl.name] = EventType.from_schema(decl, resolver)
            elif isinstance(decl, xcbxml.EventCopy):
                events[decl.name] = events[decl.ref].copy_as(decl)
            elif isinstance(decl, xcbxml.Request):
                requests.append(RequestType.from_schema(decl, resolver))

        return Module(
            header=bindings.header,
            xid_types=tuple(xid_types),
            enums=tuple(enums),
            xid_unions=tuple(xid_unions),
            structs=tuple(structs),
            unions=tuple(unions),
            events=events,
            requests=tuple(requests),
        )

    def emit(self) -> str:
        emit = Emit()
        emit('// zig fmt: off')
        emit('// This file is generated by tools/genproto.py')
        emit()
        emit('const std = @import("std");')
        emit('const io = @import("../io.zig");')
        if self.events:
            emit('const DecodeError = @import("../_errors.zig").DecodeError;')
            emit('const global_events = @import("events.zig");')
        emit()

        for xid_type in self.xid_types:
            xid_type.emit_definition(emit)

        for enum in self.enums:
            enum.emit_definition(emit)

        for xid_union in self.xid_unions:
            xid_union.emit_definition(emit)

        for struct in self.structs:
            struct.emit_definition(emit)

        for union in self.unions:
            union.emit_definition(emit)

        for request in self.requests:
            request.emit_definition(emit)

        events_mod.emit_definitions(emit, list(self.events.values()))

        return emit.render()


def load_bindings(path: Path) -> xcbxml.Bindings:
    root = ET.parse(path).getroot()
    bindings = xcbxml.root_item.match(root)
    return bindings


def parse_args(argv: list[str]) -> tuple[Path, Path]:
    if len(argv) == 1:
        return DEFAULT_XML_PATH, DEFAULT_OUT_PATH
    if len(argv) == 2:
        return Path(argv[1]), DEFAULT_OUT_PATH
    if len(argv) == 3:
        return Path(argv[1]), Path(argv[2])
    raise SystemExit(f'usage: {argv[0]} [xml-path] [out-path]')


def main() -> None:
    xml_path, out_path = parse_args(sys.argv)
    resolver = Resolver({})
    resolver.types.update(SCALAR_TYPES)
    bindings = load_bindings(xml_path)
    module = Module.from_schema(bindings, resolver)
    rendered = module.emit() + '\n'
    errors_rendered = emit_errors_module(bindings) + '\n'
    events_rendered = events_mod.emit_events_module(bindings, module) + '\n'
    out_path.write_text(rendered)
    out_path.with_name('errors.zig').write_text(errors_rendered)
    out_path.with_name('events.zig').write_text(events_rendered)
    print(f'generated file={out_path} structs={len(module.structs)}')
