from __future__ import annotations

from typing import TYPE_CHECKING, Sequence

from .common import Emit

if TYPE_CHECKING:
    from . import Module


def emit_errors_module(modules: Sequence[Module], ext_import: str = '../_ext.zig') -> str:
    module_errors = [(module, module.errors) for module in modules]

    emit = Emit()

    emit('// zig fmt: off')
    emit('// This file is generated by tools/genproto.py')
    emit()

    emit(f'const extensions = @import("{ext_import}");')
    emit()

    emit('pub const ProtocolError = struct {')
    with emit.block():
        emit('code: u8,')
        emit('sequence: u16,')
        emit('bad_value: u32,')
        emit('minor_opcode: u16,')
        emit('major_opcode: u8,')
        emit('tail: [20]u8,')
    emit('};')
    emit()

    emit('pub const TaggedError = union(enum) {')
    with emit.block():
        for module, errs in module_errors:
            prefix = module.global_tagged_prefix()
            for err in errs:
                emit(f'{prefix}{err.name}: ProtocolError,')
        emit('Unknown: ProtocolError,')
        emit('NonX11: anyerror,')
    emit('};')
    emit()

    emit('pub const ExtensionErrorSpec = struct {')
    with emit.block():
        emit('max_error_num: u8,')
        emit('decode: *const fn (u8, ProtocolError) ?TaggedError,')
    emit('};')
    emit()

    for module, errs in module_errors:
        if not errs:
            continue
        decode_name = f'decode{module.name.capitalize()}Error'
        emit(f'fn {decode_name}(code: u8, raw: ProtocolError) ?TaggedError {{')
        with emit.block():
            prefix = module.global_tagged_prefix()
            emit('return switch (code) {')
            with emit.block():
                for err in errs:
                    emit(
                        f'{int(err.number)} => .{{ .{prefix}{err.name} = raw }},'
                    )
                emit('else => null,')
            emit('};')
        emit('}')
        emit()

        max_error_num = max((int(err.number) for err in errs), default=0)
        emit(f'const {module.name}_error_spec: ExtensionErrorSpec = .{{')
        with emit.block():
            emit(f'.max_error_num = {max_error_num},')
            emit(f'.decode = {decode_name},')
        emit('};')
        emit()

    emit('pub fn errorSpec(extension: extensions.Extension) ?*const ExtensionErrorSpec {')
    with emit.block():
        emit('return switch (extension) {')
        with emit.block():
            for module, errs in module_errors:
                if errs:
                    emit(f'.{module.extension_enum_name()} => &{module.name}_error_spec,')
                else:
                    emit(f'.{module.extension_enum_name()} => null,')
        emit('};')
    emit('}')
    return emit.render()
