from . import xcbxml
from .common import Emit


def collect_errors(bindings: xcbxml.Bindings) -> tuple[xcbxml.Error | xcbxml.ErrorCopy, ...]:
    result: list[xcbxml.Error | xcbxml.ErrorCopy] = []
    for decl in bindings.decls:
        if isinstance(decl, xcbxml.Error | xcbxml.ErrorCopy):
            result.append(decl)
    return tuple(result)


def emit_errors_module(bindings: xcbxml.Bindings) -> str:
    errors = collect_errors(bindings)
    emit = Emit()
    emit('// zig fmt: off')
    emit('// This file is generated by tools/genproto.py')
    emit()
    emit('const extensions = @import("../_ext.zig");')
    emit()
    emit('pub const ProtocolError = struct {')
    with emit.block():
        emit('code: u8,')
        emit('sequence: u16,')
        emit('bad_value: u32,')
        emit('minor_opcode: u16,')
        emit('major_opcode: u8,')
        emit('tail: [20]u8,')
    emit('};')
    emit()
    emit('pub const TaggedError = union(enum) {')
    with emit.block():
        for err in errors:
            emit(f'{err.name}: ProtocolError,')
        emit('Unknown: ProtocolError,')
        emit('NonX11: anyerror,')
    emit('};')
    emit()
    emit('fn decodeCoreErrorImpl(code: u8, raw: ProtocolError) ?TaggedError {')
    with emit.block():
        emit('return switch (code) {')
        with emit.block():
            for err in errors:
                emit(f'{int(err.number)} => .{{ .{err.name} = raw }},')
            emit('else => null,')
        emit('};')
    emit('}')
    emit()
    emit('pub fn decodeCoreError(code: u8, raw: ProtocolError) ?TaggedError {')
    with emit.block():
        emit('return decodeCoreErrorImpl(code, raw);')
    emit('}')
    emit()
    emit('pub const ExtensionErrorSpec = struct {')
    with emit.block():
        emit('max_error_num: u8,')
        emit('decode: *const fn (u8, ProtocolError) ?TaggedError,')
    emit('};')
    emit()
    max_error_num = max((int(err.number) for err in errors), default=0)
    emit('const core_error_spec: ExtensionErrorSpec = .{')
    with emit.block():
        emit(f'.max_error_num = {max_error_num},')
        emit('.decode = decodeCoreErrorImpl,')
    emit('};')
    emit()
    emit('pub fn errorSpec(extension: extensions.Extension) ?*const ExtensionErrorSpec {')
    with emit.block():
        if bindings.header == 'xproto':
            emit('return switch (extension) {')
            with emit.block():
                emit('.CORE => &core_error_spec,')
                emit('else => null,')
            emit('};')
        else:
            emit('_ = extension;')
            emit('return null;')
    emit('}')
    return emit.render()
