#!/usr/bin/env python3

from __future__ import annotations

import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path


XML_PATH = Path("/usr/share/xcb/xproto.xml")
OUT_PATH = Path("src/xproto.zig")
TARGET_REQUESTS = ("InternAtom", "GetProperty", "GetInputFocus", "CreateWindow", "MapWindow")
TARGET_EVENTS = ("ButtonPress", "Expose", "MapNotify", "ConfigureNotify", "ReparentNotify")
TARGET_ENUMS = (
    "GetPropertyType",
    "WindowClass",
    "CW",
    "EventMask",
    "VisualClass",
    "BackingStore",
    "ImageOrder",
    "ColorFlag",
    "Family",
    "InputFocus",
    "Gravity",
    "KeyButMask",
)

SCALAR_TYPES = {
    "BOOL": ("bool", 1),
    "BYTE": ("u8", 1),
    "CARD8": ("u8", 1),
    "CARD16": ("u16", 2),
    "CARD32": ("u32", 4),
    "INT16": ("i16", 2),
    "char": ("u8", 1),
}


@dataclass(frozen=True)
class Field:
    name: str
    x_type: str
    zig_type: str
    wire_zig_type: str
    size: int


@dataclass(frozen=True)
class PadBytes:
    bytes: int


@dataclass(frozen=True)
class PadAlign:
    align: int


@dataclass(frozen=True)
class FieldRefExpr:
    field_name: str


@dataclass(frozen=True)
class ValueExpr:
    value: int


@dataclass(frozen=True)
class MultiplyExpr:
    lhs: "Expr"
    rhs: "Expr"


@dataclass(frozen=True)
class DivideExpr:
    lhs: "Expr"
    rhs: "Expr"


Expr = FieldRefExpr | ValueExpr | MultiplyExpr | DivideExpr


@dataclass(frozen=True)
class LengthExpr:
    expr: Expr


@dataclass(frozen=True)
class ListField:
    name: str
    x_type: str
    elem_size: int | None
    length_expr: LengthExpr | None
    is_last: bool


@dataclass(frozen=True)
class SwitchCase:
    field: Field
    enum_ref: str
    enum_item: str


@dataclass(frozen=True)
class SwitchField:
    name: str
    mask_field_name: str
    cases: list[SwitchCase]


Item = Field | PadBytes | PadAlign | ListField | SwitchField


@dataclass(frozen=True)
class StructDef:
    name: str
    items: list[Item]


@dataclass(frozen=True)
class RequestDef:
    name: str
    opcode: int
    header_field: Field | None
    body: list[Item]
    reply_items: list[Item] | None


@dataclass(frozen=True)
class EventDef:
    name: str
    number: int
    items: list[Item]


def main() -> None:
    root = ET.parse(XML_PATH).getroot()
    requests_xml = {child.attrib["name"]: child for child in root if child.tag == "request"}
    structs_xml = {child.attrib["name"]: child for child in root if child.tag == "struct"}
    events_xml = {child.attrib["name"]: child for child in root if child.tag == "event"}
    enums = {child.attrib["name"]: child for child in root if child.tag == "enum"}
    typedefs = {child.attrib["newname"]: child.attrib["oldname"] for child in root if child.tag == "typedef"}
    xidtypes = {child.attrib["name"] for child in root if child.tag == "xidtype"}
    xidunions = {child.attrib["name"] for child in root if child.tag == "xidunion"}
    xid_like_types = {zig_xid_name(name) for name in xidtypes | xidunions}

    requests = [
        parse_request(requests_xml[name], structs_xml, typedefs, xidtypes, xidunions)
        for name in TARGET_REQUESTS
    ]
    events = [
        parse_event(events_xml[name], structs_xml, typedefs, xidtypes, xidunions)
        for name in TARGET_EVENTS
    ]

    struct_defs: dict[str, StructDef] = {}
    for name, node in structs_xml.items():
        try:
            struct_defs[name] = parse_struct(node, structs_xml, typedefs, xidtypes, xidunions)
        except ValueError:
            continue
    emitted_structs = [
        struct_defs[name]
        for name in struct_defs
        if struct_supported(struct_defs[name], struct_defs)
    ]

    out: list[str] = []
    emit(out, "// This file is generated by tools/gen_xproto.py.")
    emit(out, f"// Source: {XML_PATH}")
    emit(out, "")
    emit(out, 'const std = @import("std");')
    emit(out, 'const wire = @import("wire.zig");')
    emit(out, "")
    for name in sorted(xidtypes):
        emit(out, f"pub const {zig_xid_name(name)} = enum(u32) {{ _ }};")
    for name in sorted(xidunions):
        emit(out, f"pub const {zig_xid_name(name)} = enum(u32) {{ _ }};")
    emit(out, "")

    for struct_def in emitted_structs:
        for line in emit_plain_struct(struct_def, struct_defs, xid_like_types):
            emit(out, line)
        emit(out, "")

    for enum_name in TARGET_ENUMS:
        emit_enum(out, enum_name, enums[enum_name])
        emit(out, "")

    for request in requests:
        for line in emit_request_module(request, xid_like_types):
            emit(out, line)
        emit(out, "")

    for event in events:
        for line in emit_event_module(event, xid_like_types):
            emit(out, line)
        emit(out, "")
    for line in emit_event_union(events):
        emit(out, line)
    emit(out, "")

    OUT_PATH.write_text("".join(out), encoding="utf-8")


def emit(buf: list[str], line: str) -> None:
    buf.append(line + "\n")


def emit_enum(buf: list[str], name: str, node: ET.Element) -> None:
    value = 0
    has_bits = any(item.find("bit") is not None for item in node.findall("item"))
    seen_values: dict[int, str] = {}
    aliases: list[tuple[str, str]] = []
    emit(buf, f"pub const {name} = enum(u32) {{")
    for item in node.findall("item"):
        item_name = item.attrib["name"]
        value_node = item.find("value")
        bit_node = item.find("bit")
        if value_node is not None and value_node.text is not None:
            value = int(value_node.text.strip(), 0)
        elif bit_node is not None and bit_node.text is not None:
            value = 1 << int(bit_node.text.strip(), 0)
        zig_item_name = zig_name(item_name)
        previous_name = seen_values.get(value)
        if previous_name is None:
            emit(buf, f"    {zig_item_name} = {value},")
            seen_values[value] = zig_item_name
        else:
            aliases.append((zig_item_name, previous_name))
        value += 1
    emit(buf, "    _,")
    if has_bits:
        emit(buf, "")
        emit(buf, "    pub fn of(flags: []const @This()) u32 {")
        emit(buf, "        return wire.maskOf(@This(), flags);")
        emit(buf, "    }")
    if aliases:
        emit(buf, "")
        for alias_name, target_name in aliases:
            emit(buf, f"    pub const {alias_name} = @This().{target_name};")
    emit(buf, "};")


def parse_request(
    node: ET.Element,
    structs_xml: dict[str, ET.Element],
    typedefs: dict[str, str],
    xidtypes: set[str],
    xidunions: set[str],
) -> RequestDef:
    body_nodes = [child for child in node if child.tag in {"field", "pad", "list", "switch"}]
    header_field: Field | None = None
    index = 0
    if body_nodes and body_nodes[0].tag == "field":
        first = parse_field(body_nodes[0], typedefs, xidtypes, xidunions)
        if first.size == 1:
            header_field = first
            index = 1
    elif body_nodes and body_nodes[0].tag == "pad" and body_nodes[0].attrib.get("bytes") == "1":
        index = 1
    body = parse_items(body_nodes[index:], structs_xml, typedefs, xidtypes, xidunions)
    reply = node.find("reply")
    reply_items = None
    if reply is not None:
        reply_items = parse_items([child for child in reply if child.tag in {"field", "pad", "list"}], structs_xml, typedefs, xidtypes, xidunions)
    return RequestDef(
        name=node.attrib["name"],
        opcode=int(node.attrib["opcode"]),
        header_field=header_field,
        body=body,
        reply_items=reply_items,
    )


def parse_struct(
    node: ET.Element,
    structs_xml: dict[str, ET.Element],
    typedefs: dict[str, str],
    xidtypes: set[str],
    xidunions: set[str],
) -> StructDef:
    items = parse_items([child for child in node if child.tag in {"field", "pad", "list"}], structs_xml, typedefs, xidtypes, xidunions)
    return StructDef(name=node.attrib["name"], items=items)


def parse_event(
    node: ET.Element,
    structs_xml: dict[str, ET.Element],
    typedefs: dict[str, str],
    xidtypes: set[str],
    xidunions: set[str],
) -> EventDef:
    items = parse_items([child for child in node if child.tag in {"field", "pad", "list"}], structs_xml, typedefs, xidtypes, xidunions)
    return EventDef(name=node.attrib["name"], number=int(node.attrib["number"]), items=items)


def parse_items(
    nodes: list[ET.Element],
    structs_xml: dict[str, ET.Element],
    typedefs: dict[str, str],
    xidtypes: set[str],
    xidunions: set[str],
) -> list[Item]:
    items: list[Item] = []
    for index, node in enumerate(nodes):
        if node.tag == "field":
            items.append(parse_field(node, typedefs, xidtypes, xidunions))
        elif node.tag == "pad":
            if "bytes" in node.attrib:
                items.append(PadBytes(bytes=int(node.attrib["bytes"], 0)))
            elif "align" in node.attrib:
                items.append(PadAlign(align=int(node.attrib["align"], 0)))
            else:
                raise ValueError(f"unsupported pad node: {ET.tostring(node, encoding='unicode')}")
        elif node.tag == "list":
            x_type = node.attrib["type"]
            items.append(
                ListField(
                    name=node.attrib["name"],
                    x_type=x_type,
                    elem_size=resolve_type_size(x_type, structs_xml, typedefs, xidtypes, xidunions),
                    length_expr=parse_length_expr(node),
                    is_last=index == len(nodes) - 1,
                )
            )
        elif node.tag == "switch":
            if len(node) == 0 or node[0].tag != "fieldref" or node[0].text is None:
                raise ValueError(f"unsupported switch: {ET.tostring(node, encoding='unicode')}")
            mask_field_name = node[0].text.strip()
            cases: list[SwitchCase] = []
            for case_node in node.findall("bitcase"):
                enumref = case_node.find("enumref")
                field_nodes = [child for child in case_node if child.tag == "field"]
                if enumref is None or enumref.text is None or len(field_nodes) != 1:
                    raise ValueError(f"unsupported bitcase: {ET.tostring(case_node, encoding='unicode')}")
                cases.append(
                    SwitchCase(
                        field=parse_field(field_nodes[0], typedefs, xidtypes, xidunions),
                        enum_ref=enumref.attrib["ref"],
                        enum_item=enumref.text.strip(),
                    )
                )
            items.append(
                SwitchField(
                    name=node.attrib["name"],
                    mask_field_name=mask_field_name,
                    cases=cases,
                )
            )
        else:
            raise ValueError(node.tag)
    return items


def parse_field(node: ET.Element, typedefs: dict[str, str], xidtypes: set[str], xidunions: set[str]) -> Field:
    wire_zig_type, size = zig_scalar_type(node.attrib["type"], typedefs, xidtypes, xidunions)
    zig_type = field_zig_type(node, wire_zig_type)
    return Field(
        name=node.attrib["name"],
        x_type=node.attrib["type"],
        zig_type=zig_type,
        wire_zig_type=wire_zig_type,
        size=size,
    )


def field_zig_type(node: ET.Element, wire_zig_type: str) -> str:
    if "enum" in node.attrib:
        return node.attrib["enum"]
    return wire_zig_type


def resolve_type_size(
    x_type: str,
    structs_xml: dict[str, ET.Element],
    typedefs: dict[str, str],
    xidtypes: set[str],
    xidunions: set[str],
) -> int | None:
    if x_type == "void":
        return 1
    if x_type in structs_xml:
        return None
    _, size = zig_scalar_type(x_type, typedefs, xidtypes, xidunions)
    return size


def zig_xid_name(name: str) -> str:
    return name.title().replace("_", "")


def zig_scalar_type(x_type: str, typedefs: dict[str, str], xidtypes: set[str], xidunions: set[str]) -> tuple[str, int]:
    if x_type in xidtypes or x_type in xidunions:
        return zig_xid_name(x_type), 4
    while x_type in typedefs:
        x_type = typedefs[x_type]
    if x_type == "void":
        return "u8", 1
    if x_type in SCALAR_TYPES:
        return SCALAR_TYPES[x_type]
    raise ValueError(f"unsupported scalar type: {x_type}")


def strip_len_suffix(name: str) -> str:
    if name.endswith("_len"):
        return name[: -len("_len")]
    return name


def parse_length_expr(node: ET.Element) -> LengthExpr | None:
    if len(node) == 0:
        return None
    if len(node) != 1:
        raise ValueError(f"unsupported list expression: {ET.tostring(node, encoding='unicode')}")
    return LengthExpr(expr=parse_expr(node[0]))


def parse_expr(node: ET.Element) -> Expr:
    if node.tag == "fieldref":
        if node.text is None:
            raise ValueError(f"empty fieldref: {ET.tostring(node, encoding='unicode')}")
        return FieldRefExpr(field_name=node.text.strip())
    if node.tag == "value":
        if node.text is None:
            raise ValueError(f"empty value: {ET.tostring(node, encoding='unicode')}")
        return ValueExpr(value=int(node.text.strip(), 0))
    if node.tag == "op":
        if len(node) != 2:
            raise ValueError(f"unsupported op arity: {ET.tostring(node, encoding='unicode')}")
        lhs = parse_expr(node[0])
        rhs = parse_expr(node[1])
        op = node.attrib.get("op")
        if op == "*":
            return MultiplyExpr(lhs=lhs, rhs=rhs)
        if op == "/":
            return DivideExpr(lhs=lhs, rhs=rhs)
    raise ValueError(f"unsupported expression: {ET.tostring(node, encoding='unicode')}")


def struct_supported(struct_def: StructDef, structs: dict[str, StructDef]) -> bool:
    for item in struct_def.items:
        if isinstance(item, ListField):
            if is_struct_list(item, structs):
                if item.length_expr is None:
                    return False
                if simple_fieldref_name(item.length_expr.expr) is None:
                    return False
                continue
            if item.length_expr is None and not item.is_last:
                return False
            if item.elem_size is None and not item.is_last:
                return False
    return True


def request_switches(items: list[Item]) -> dict[str, SwitchField]:
    return {item.mask_field_name: item for item in items if isinstance(item, SwitchField)}


def emit_container_fields(
    lines: list[str],
    items: list[Item],
    derived_fields: dict[str, ListField],
    structs: dict[str, StructDef],
    *,
    request_lists_are_bytes: bool,
    switches: dict[str, SwitchField] | None = None,
    request_name: str | None = None,
) -> None:
    switches = switches or {}
    for item in items:
        if isinstance(item, Field) and item.name not in derived_fields and item.name not in switches:
            lines.append(f"    {zig_name(item.name)}: {item.zig_type},")
        elif isinstance(item, ListField):
            if request_lists_are_bytes:
                lines.append(f"    {zig_name(item.name)}: []const u8,")
            else:
                lines.append(f"    {zig_name(item.name)}: {list_field_zig_type(item, structs)},")
        elif isinstance(item, SwitchField):
            assert request_name is not None
            lines.append(f"    {zig_name(item.name)}: {request_name}{zig_name(item.name).title().replace('_', '')},")


def switch_type_name(request_name: str, switch: SwitchField) -> str:
    return f"{request_name}{zig_name(switch.name).title().replace('_', '')}"


def emit_switch_types(request_name: str, switch: SwitchField) -> list[str]:
    type_name = switch_type_name(request_name, switch)
    spec_name = f"{type_name}Spec"
    lines = [f"pub const {type_name} = struct {{"]
    for case in switch.cases:
        lines.append(f"    {zig_name(case.field.name)}: ?{case.field.zig_type} = null,")
    lines.append("};")
    lines.append("")
    lines.append(f"pub const {spec_name} = struct {{")
    lines.append("    pub const fields = .{")
    for case in switch.cases:
        lines.append(
            f'        .{{ .name = "{zig_name(case.field.name)}", .bit = @intFromEnum({case.enum_ref}.{zig_name(case.enum_item)}), .value_type = {case.field.zig_type} }},'
        )
    lines.append("    };")
    lines.append("};")
    return lines


def emit_plain_struct(struct_def: StructDef, structs: dict[str, StructDef], xid_like_types: set[str]) -> list[str]:
    dynamic = struct_is_dynamic(struct_def)
    derived_fields = derived_length_fields(struct_def.items)
    lines = [f"pub const {struct_def.name} = struct {{"]
    emit_container_fields(lines, struct_def.items, derived_fields, structs, request_lists_are_bytes=False)
    lines.append("")
    lines.extend(emit_plain_struct_encode(struct_def, structs, xid_like_types))
    lines.append("")
    lines.extend(emit_plain_struct_decode(struct_def, structs, xid_like_types))
    if dynamic:
        lines.append("")
        lines.extend(emit_plain_struct_deinit(struct_def, structs))
    lines.append("};")
    return lines


def struct_is_dynamic(struct_def: StructDef) -> bool:
    return any(isinstance(item, ListField) for item in struct_def.items)


def emit_scalar_write(expr: str, zig_type: str, size: int, xid_like_types: set[str]) -> list[str]:
    if zig_type in xid_like_types:
        return [f"        try writer.writeInt(u32, @intFromEnum({expr}), .little);"]
    if zig_type == "bool":
        return [f"        try writer.writeByte(@intFromBool({expr}));"]
    if size == 1:
        return [f"        try writer.writeByte({expr});"]
    if size == 2:
        return [f"        try writer.writeInt({zig_type}, {expr}, .little);"]
    if size == 4:
        return [f"        try writer.writeInt({zig_type}, {expr}, .little);"]
    raise AssertionError((expr, zig_type, size))


def emit_field_write(expr: str, field: Field, xid_like_types: set[str]) -> list[str]:
    if field.zig_type != field.wire_zig_type and field.wire_zig_type != "bool":
        if field.size == 1:
            return [f"        try writer.writeByte(@intCast(@intFromEnum({expr})));"]
        return [f"        try writer.writeInt({field.wire_zig_type}, @intCast(@intFromEnum({expr})), .little);"]
    return emit_scalar_write(expr, field.zig_type, field.size, xid_like_types)


def derived_field_value_expr(
    item: Field,
    list_item: ListField,
    structs: dict[str, StructDef],
    *,
    self_prefix: str,
) -> list[str]:
    if is_struct_list(list_item, structs):
        count_expr = f"{self_prefix}{zig_name(list_item.name)}.len"
        return [], f"@intCast({count_expr})"
    byte_len_expr = list_field_len_expr(list_item, structs, self_prefix=self_prefix)
    divisor = scalar_list_elem_size(list_item)
    if divisor != 1:
        return [
            f"        std.debug.assert({byte_len_expr} % {divisor} == 0);",
        ], f"@intCast(@divExact({byte_len_expr}, {divisor}))"
    return [], f"@intCast({byte_len_expr})"


def emit_field_encode(
    item: Field,
    derived_fields: dict[str, ListField],
    structs: dict[str, StructDef],
    xid_like_types: set[str],
    *,
    self_prefix: str,
) -> list[str]:
    if item.name in derived_fields:
        extra_lines, value_expr = derived_field_value_expr(item, derived_fields[item.name], structs, self_prefix=self_prefix)
        return extra_lines + emit_field_write(value_expr, item, xid_like_types)
    return emit_field_write(f"{self_prefix}{zig_name(item.name)}", item, xid_like_types)


def emit_plain_struct_encode(struct_def: StructDef, structs: dict[str, StructDef], xid_like_types: set[str]) -> list[str]:
    uses_self_for_len = any(isinstance(item, ListField) for item in struct_def.items)
    byte_len_terms: list[str] = []
    for item in struct_def.items:
        if isinstance(item, Field):
            byte_len_terms.append(str(item.size))
        elif isinstance(item, PadBytes):
            byte_len_terms.append(str(item.bytes))
        elif isinstance(item, PadAlign):
            prev = previous_list(struct_def.items, item)
            assert prev is not None
            byte_len_terms.append(f"wire.pad4({list_field_len_expr(prev, structs, self_prefix='self.')})")
        elif isinstance(item, ListField):
            byte_len_terms.append(list_field_len_expr(item, structs, self_prefix="self."))
    lines = [
        "    pub fn byteLen(self: @This()) usize {",
    ]
    if not uses_self_for_len:
        lines.append("        _ = self;")
    lines.append(f"        return {' + '.join(byte_len_terms) if byte_len_terms else '0'};")
    lines.append("    }")
    lines.append("")
    lines.append("    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {")
    derived_fields = derived_length_fields(struct_def.items)
    for item in struct_def.items:
        if isinstance(item, Field):
            lines.extend(emit_field_encode(item, derived_fields, structs, xid_like_types, self_prefix="self."))
        elif isinstance(item, PadBytes):
            lines.append(f"        try writer.splatByteAll(0, {item.bytes});")
        elif isinstance(item, PadAlign):
            prev = previous_list(struct_def.items, item)
            assert prev is not None
            lines.append(f"        try writer.splatByteAll(0, wire.pad4({list_field_len_expr(prev, structs, self_prefix='self.')}));")
        elif isinstance(item, ListField):
            if (
                item.length_expr is not None
                and not is_struct_list(item, structs)
                and simple_fieldref_name(item.length_expr.expr) not in derived_fields
            ):
                lines.append(
                    f"        std.debug.assert({list_field_len_expr(item, structs, self_prefix='self.')} == {scalar_list_byte_len_expr(item, 'self.')});"
                )
            lines.extend(emit_encode_list(item, structs))
    lines.append("    }")
    return lines


def emit_decode_item(
    item: Item,
    derived_fields: dict[str, ListField],
    structs: dict[str, StructDef],
    xid_like_types: set[str],
) -> tuple[list[str], list[str]]:
    if isinstance(item, Field):
        field_name = zig_name(item.name)
        lines = [f"        const {field_name} = {decode_field_expr(item, xid_like_types)};"]
        result_lines = [] if item.name in derived_fields else [f"            .{field_name} = {field_name},"]
        return lines, result_lines
    if isinstance(item, PadBytes):
        return [f"        _ = try reader.take({item.bytes});"], []
    assert isinstance(item, ListField)
    lines = emit_decode_list(item, structs)
    return lines, [f"            .{zig_name(item.name)} = {zig_name(item.name)},"]


def emit_plain_struct_decode(struct_def: StructDef, structs: dict[str, StructDef], xid_like_types: set[str]) -> list[str]:
    dynamic = struct_is_dynamic(struct_def)
    derived_fields = derived_length_fields(struct_def.items)
    locals_lines: list[str] = []
    result_lines: list[str] = []
    for item in struct_def.items:
        if isinstance(item, PadAlign):
            prev = previous_list(struct_def.items, item)
            assert prev is not None
            locals_lines.append(f"        _ = try reader.take(wire.pad4({decoded_list_len_expr(prev, structs)}));")
            continue
        item_locals, item_results = emit_decode_item(item, derived_fields, structs, xid_like_types)
        locals_lines.extend(item_locals)
        result_lines.extend(item_results)
    lines = [
        f"    pub fn decode({ 'allocator: std.mem.Allocator, ' if dynamic else '' }reader: *std.Io.Reader) wire.Error!@This() {{",
    ]
    lines.extend(locals_lines)
    lines.append("        return .{")
    lines.extend(result_lines)
    lines.append("        };")
    lines.append("    }")
    return lines


def emit_plain_struct_deinit(struct_def: StructDef, structs: dict[str, StructDef]) -> list[str]:
    lines = [
        "    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {",
    ]
    for item in struct_def.items:
        if isinstance(item, ListField):
            field_name = zig_name(item.name)
            if is_struct_list(item, structs):
                if struct_is_dynamic(structs[item.x_type]):
                    lines.append(f"        for (self.{field_name}) |*elem| elem.deinit(allocator);")
                lines.append(f"        allocator.free(self.{field_name});")
            else:
                lines.append(f"        allocator.free(self.{field_name});")
    lines.append("    }")
    return lines


def previous_list(items: list[Item], target: PadAlign) -> ListField | None:
    prev: ListField | None = None
    for item in items:
        if item is target:
            return prev
        if isinstance(item, ListField):
            prev = item
    return None


def derived_length_fields(items: list[Item]) -> dict[str, ListField]:
    derived: dict[str, ListField] = {}
    for item in items:
        if isinstance(item, ListField) and item.length_expr is not None:
            field_name = simple_fieldref_name(item.length_expr.expr)
            if field_name is not None and field_name.endswith("_len"):
                derived[field_name] = item
    return derived

def is_struct_list(item: ListField, structs: dict[str, StructDef]) -> bool:
    return item.x_type in structs


def list_field_zig_type(item: ListField, structs: dict[str, StructDef]) -> str:
    if is_struct_list(item, structs):
        return f"[]{item.x_type}"
    return "[]const u8"


def list_field_len_expr(item: ListField, structs: dict[str, StructDef], *, self_prefix: str) -> str:
    if is_struct_list(item, structs):
        return f"wire.structListByteLen({self_prefix}{zig_name(item.name)})"
    return f"{self_prefix}{zig_name(item.name)}.len"


def decoded_list_len_expr(item: ListField, structs: dict[str, StructDef]) -> str:
    if is_struct_list(item, structs):
        return f"wire.structListByteLen({zig_name(item.name)})"
    return f"{zig_name(item.name)}.len"
def struct_list_count_expr(item: ListField) -> str:
    if item.length_expr is None:
        raise ValueError(f"struct list without count expression: {item.name}")
    field_name = simple_fieldref_name(item.length_expr.expr)
    if field_name is None:
        raise ValueError(f"struct list count must be direct fieldref: {item.name}")
    return f"@as(usize, {zig_name(field_name)})"


def emit_encode_list(item: ListField, structs: dict[str, StructDef]) -> list[str]:
    field_name = zig_name(item.name)
    if is_struct_list(item, structs):
        return [f"        for (self.{field_name}) |elem| try elem.encode(writer);"]
    return [f"        try writer.writeAll(self.{field_name});"]


def emit_decode_list(item: ListField, structs: dict[str, StructDef]) -> list[str]:
    field_name = zig_name(item.name)
    if is_struct_list(item, structs):
        count_expr = struct_list_count_expr(item)
        elem_type = item.x_type
        elem_struct_dynamic = struct_is_dynamic(structs[elem_type])
        lines = [
            f"        const {field_name} = try allocator.alloc({elem_type}, {count_expr});",
            f"        errdefer allocator.free({field_name});",
            f"        var {field_name}_decoded: usize = 0;",
        ]
        if elem_struct_dynamic:
            lines.append(f"        errdefer for ({field_name}[0..{field_name}_decoded]) |*elem| elem.deinit(allocator);")
        lines.extend([
            f"        for ({field_name}) |*elem| {{",
            f"            elem.* = try {elem_type}.decode({'allocator, ' if elem_struct_dynamic else ''}reader);",
            f"            {field_name}_decoded += 1;",
            "        }",
        ])
        return lines
    if item.is_last and item.elem_size is None:
        return [
            f"        const {field_name}_wire = reader.buffered();",
            f"        const {field_name} = try allocator.dupe(u8, {field_name}_wire);",
            f"        _ = try reader.take({field_name}_wire.len);",
        ]
    byte_len_expr = scalar_list_byte_len_expr(item)
    return [
        f"        const {field_name}_wire = try reader.take({byte_len_expr});",
        f"        const {field_name} = try allocator.dupe(u8, {field_name}_wire);",
    ]


def scalar_list_byte_len_expr(item: ListField, prefix: str = "") -> str:
    if item.length_expr is None:
        return "reader.buffered().len"
    elem_size = scalar_list_elem_size(item)
    count_expr = expr_to_zig(item.length_expr.expr, prefix)
    if elem_size == 1:
        return count_expr
    return f"({count_expr}) * {elem_size}"


def scalar_list_elem_size(item: ListField) -> int:
    if item.elem_size is None:
        raise ValueError(f"scalar list without fixed element size: {item.name}")
    return item.elem_size


def expr_to_zig(expr: Expr, prefix: str = "") -> str:
    if isinstance(expr, FieldRefExpr):
        return f"@as(usize, {prefix}{zig_name(expr.field_name)})"
    if isinstance(expr, ValueExpr):
        return str(expr.value)
    if isinstance(expr, MultiplyExpr):
        return f"({expr_to_zig(expr.lhs, prefix)} * {expr_to_zig(expr.rhs, prefix)})"
    if isinstance(expr, DivideExpr):
        return f"@divExact({expr_to_zig(expr.lhs, prefix)}, {expr_to_zig(expr.rhs, prefix)})"
    raise AssertionError(expr)


def simple_fieldref_name(expr: Expr) -> str | None:
    if isinstance(expr, FieldRefExpr):
        return expr.field_name
    return None


def decode_field_expr(item: Field, xid_like_types: set[str]) -> str:
    if item.zig_type in xid_like_types:
        return f"@as({item.zig_type}, @enumFromInt(try reader.takeInt(u32, .little)))"
    if item.zig_type != item.wire_zig_type and item.wire_zig_type != "bool":
        return f"@as({item.zig_type}, @enumFromInt(try reader.takeInt({item.wire_zig_type}, .little)))"
    if item.zig_type == "bool":
        return "(try reader.takeByte()) != 0"
    if item.size == 1:
        return "try reader.takeByte()"
    if item.size == 2:
        return f"try reader.takeInt({item.zig_type}, .little)"
    if item.size == 4:
        return f"try reader.takeInt({item.zig_type}, .little)"
    raise AssertionError(item)


def emit_request_module(request: RequestDef, xid_like_types: set[str]) -> list[str]:
    derived_fields = derived_length_fields(request.body)
    switches = request_switches(request.body)
    lines: list[str] = []
    for switch in switches.values():
        lines.extend(emit_switch_types(request.name, switch))
        lines.append("")
    lines.append(f"pub const {request.name}Request = struct {{")
    lines.append(f"    pub const opcode: u8 = {request.opcode};")
    if request.reply_items is not None:
        lines.append(f"    pub const Reply = {request.name}Reply;")
    else:
        lines.append("    pub const Reply = void;")
    lines.append("")
    if request.header_field is not None:
        lines.append(f"    {zig_name(request.header_field.name)}: {request.header_field.zig_type},")
    emit_container_fields(
        lines,
        request.body,
        derived_fields,
        {},
        request_lists_are_bytes=True,
        switches=switches,
        request_name=request.name,
    )
    lines.append("")
    lines.extend(emit_request_encode(request, xid_like_types, switches))
    lines.append("};")

    if request.reply_items is not None:
        lines.append("")
        lines.extend(emit_reply_struct(request.name, request.reply_items, xid_like_types))
    return lines


def emit_request_encode(request: RequestDef, xid_like_types: set[str], switches: dict[str, SwitchField]) -> list[str]:
    body_terms: list[str] = []
    uses_self = False
    for item in request.body:
        if isinstance(item, Field):
            if item.name in switches:
                body_terms.append(str(item.size))
            else:
                body_terms.append(str(item.size))
        elif isinstance(item, PadBytes):
            body_terms.append(str(item.bytes))
        elif isinstance(item, PadAlign):
            prev = previous_list(request.body, item)
            assert prev is not None
            body_terms.append(f"wire.pad4(self.{zig_name(prev.name)}.len)")
            uses_self = True
        elif isinstance(item, ListField):
            body_terms.append(f"self.{zig_name(item.name)}.len")
            uses_self = True
        elif isinstance(item, SwitchField):
            body_terms.append(f"wire.valueListByteLen({switch_type_name(request.name, item)}Spec, self.{zig_name(item.name)})")
            uses_self = True
    lines = [
        "    pub fn byteLen(self: @This()) usize {",
    ]
    if not uses_self:
        lines.append("        _ = self;")
    raw_len = f"4 + {' + '.join(body_terms) if body_terms else '0'}"
    lines.append(f"        return {raw_len};")
    lines.append("    }")
    lines.append("")
    lines.append("    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {")
    derived_fields = derived_length_fields(request.body)
    lines.append("        const len = self.byteLen();")
    lines.append("        const pad = wire.pad4(len);")
    lines.append("        try writer.writeByte(opcode);")
    if request.header_field is None:
        lines.append("        try writer.writeByte(0);")
    else:
        lines.extend(emit_scalar_write(f"self.{zig_name(request.header_field.name)}", request.header_field.zig_type, request.header_field.size, xid_like_types))
    lines.append("        try writer.writeInt(u16, @intCast((len + pad) / 4), .little);")
    for switch in switches.values():
        lines.append(f"        const {zig_name(switch.mask_field_name)} = wire.computeValueMask({switch_type_name(request.name, switch)}Spec, self.{zig_name(switch.name)});")
    for item in request.body:
        if isinstance(item, Field):
            if item.name in switches:
                lines.extend(emit_scalar_write(zig_name(item.name), item.zig_type, item.size, xid_like_types))
            else:
                lines.extend(emit_field_encode(item, derived_fields, {}, xid_like_types, self_prefix="self."))
        elif isinstance(item, PadBytes):
            lines.append(f"        try writer.splatByteAll(0, {item.bytes});")
        elif isinstance(item, PadAlign):
            prev = previous_list(request.body, item)
            assert prev is not None
            lines.append(f"        try writer.splatByteAll(0, wire.pad4(self.{zig_name(prev.name)}.len));")
        elif isinstance(item, ListField):
            if (
                item.length_expr is not None
                and item.elem_size is not None
                and simple_fieldref_name(item.length_expr.expr) not in derived_fields
            ):
                lines.append(
                    f"        std.debug.assert(self.{zig_name(item.name)}.len == {scalar_list_byte_len_expr(item, 'self.')});"
                )
            lines.append(f"        try writer.writeAll(self.{zig_name(item.name)});")
        elif isinstance(item, SwitchField):
            lines.append(f"        try wire.writeValueList({switch_type_name(request.name, item)}Spec, self.{zig_name(item.name)}, writer);")
    lines.append("        try writer.splatByteAll(0, pad);")
    lines.append("    }")
    return lines


def emit_reply_struct(name: str, items: list[Item], xid_like_types: set[str]) -> list[str]:
    scalar_fields = [item for item in items if isinstance(item, Field)]
    list_fields = [item for item in items if isinstance(item, ListField)]
    lines = [f"pub const {name}Reply = struct {{"]
    for field in scalar_fields:
        lines.append(f"    {zig_name(field.name)}: {field.zig_type},")
    for list_field in list_fields:
        lines.append(f"    {zig_name(list_field.name)}: []const u8,")
    lines.append("")
    if list_fields:
        lines.extend(emit_reply_decode_variable(items, xid_like_types))
    else:
        lines.extend(emit_reply_decode_fixed(items, xid_like_types))
    lines.append("};")
    return lines


def emit_reply_decode_fixed(items: list[Item], xid_like_types: set[str]) -> list[str]:
    scalar_fields = [item for item in items if isinstance(item, Field)]
    locals_lines: list[str] = [
        "    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {",
        "        if (try reader.takeByte() != 1) return error.UnexpectedReplyType;",
    ]
    body_field_bytes = 0
    first_item = items[0] if items else None
    remaining_items = items
    if isinstance(first_item, Field):
        if first_item.size != 1:
            raise ValueError("first fixed reply field must be 1 byte")
        locals_lines.append(f"        const {zig_name(first_item.name)} = {decode_field_expr(first_item, xid_like_types)};")
        remaining_items = items[1:]
    elif isinstance(first_item, PadBytes):
        if first_item.bytes != 1:
            raise ValueError("first fixed reply pad must be 1 byte")
        locals_lines.append("        _ = try reader.takeByte();")
        remaining_items = items[1:]
    else:
        locals_lines.append("        _ = try reader.takeByte();")
    locals_lines.extend([
        "        _ = try reader.takeInt(u16, .little);",
        "        _ = try reader.takeInt(u32, .little);",
    ])
    for item in remaining_items:
        if isinstance(item, Field):
            locals_lines.append(f"        const {zig_name(item.name)} = {decode_field_expr(item, xid_like_types)};")
            body_field_bytes += item.size
        elif isinstance(item, PadBytes):
            locals_lines.append(f"        _ = try reader.take({item.bytes});")
            body_field_bytes += item.bytes
        elif isinstance(item, PadAlign):
            raise ValueError("reply align pad unsupported")
        elif isinstance(item, ListField):
            raise ValueError("fixed reply cannot contain list")
    trailing = 24 - body_field_bytes
    if trailing > 0:
        locals_lines.append(f"        _ = try reader.take({trailing});")
    locals_lines.append("        return .{")
    for field in scalar_fields:
        locals_lines.append(f"            .{zig_name(field.name)} = {zig_name(field.name)},")
    locals_lines.append("        };")
    locals_lines.append("    }")
    return locals_lines


def emit_reply_decode_variable(items: list[Item], xid_like_types: set[str]) -> list[str]:
    scalar_fields = [item for item in items if isinstance(item, Field)]
    list_field = next(item for item in items if isinstance(item, ListField))
    body_lines = [
        "    pub fn decode(reader: *std.Io.Reader, scratch: []u8) wire.Error!@This() {",
        "        if (try reader.takeByte() != 1) return error.UnexpectedReplyType;",
        "        const format = try reader.takeByte();",
        "        _ = try reader.takeInt(u16, .little);",
        "        const reply_len = @as(usize, try reader.takeInt(u32, .little)) * 4;",
        "        const type_atom = @as(Atom, @enumFromInt(try reader.takeInt(u32, .little)));",
        "        const bytes_after = try reader.takeInt(u32, .little);",
        "        const value_len = try reader.takeInt(u32, .little);",
        "        _ = try reader.take(12);",
        "        const value_bytes = try wire.valueByteLen(format, value_len);",
        "        if (reply_len < value_bytes) return error.MalformedPacket;",
        "        if (scratch.len < value_bytes) return error.BufferTooSmall;",
        "        @memcpy(scratch[0..value_bytes], try reader.take(value_bytes));",
        "        _ = try reader.take(reply_len - value_bytes);",
        "        return .{",
        "            .format = format,",
        "            .type_atom = type_atom,",
        f"            .{zig_name('bytes_after')} = bytes_after,",
        f"            .{zig_name('value_len')} = value_len,",
        f"            .{zig_name(list_field.name)} = scratch[0..value_bytes],",
        "        };",
        "    }",
    ]
    return body_lines


def emit_event_module(event: EventDef, xid_like_types: set[str]) -> list[str]:
    lines = [f"pub const {event.name}Event = struct {{"]
    for item in event.items:
        if isinstance(item, Field):
            lines.append(f"    {zig_name(item.name)}: {item.zig_type},")
    lines.append("")
    lines.extend(emit_event_decode(event, xid_like_types))
    lines.append("};")
    return lines


def emit_event_decode(event: EventDef, xid_like_types: set[str]) -> list[str]:
    scalar_fields = [item for item in event.items if isinstance(item, Field)]
    lines: list[str] = [
        "    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {",
        f"        if ((try reader.takeByte()) & 0x7f != {event.number}) return error.UnexpectedEventType;",
    ]
    body_field_bytes = 0
    first_item = event.items[0] if event.items else None
    remaining_items = event.items
    if isinstance(first_item, Field):
        if first_item.size != 1:
            raise ValueError("first fixed event field must be 1 byte")
        lines.append(f"        const {zig_name(first_item.name)} = {decode_field_expr(first_item, xid_like_types)};")
        remaining_items = event.items[1:]
    elif isinstance(first_item, PadBytes):
        if first_item.bytes != 1:
            raise ValueError("first fixed event pad must be 1 byte")
        lines.append("        _ = try reader.takeByte();")
        remaining_items = event.items[1:]
    else:
        lines.append("        _ = try reader.takeByte();")
    lines.append("        _ = try reader.takeInt(u16, .little);")
    for item in remaining_items:
        if isinstance(item, Field):
            lines.append(f"        const {zig_name(item.name)} = {decode_field_expr(item, xid_like_types)};")
            body_field_bytes += item.size
        elif isinstance(item, PadBytes):
            lines.append(f"        _ = try reader.take({item.bytes});")
            body_field_bytes += item.bytes
        elif isinstance(item, PadAlign):
            raise ValueError("event align pad unsupported")
        elif isinstance(item, ListField):
            raise ValueError("fixed event cannot contain list")
    trailing = 28 - body_field_bytes
    if trailing > 0:
        lines.append(f"        _ = try reader.take({trailing});")
    lines.append("        return .{")
    for field in scalar_fields:
        lines.append(f"            .{zig_name(field.name)} = {zig_name(field.name)},")
    lines.append("        };")
    lines.append("    }")
    return lines


def event_tag(name: str) -> str:
    out: list[str] = []
    for i, ch in enumerate(name):
        if ch.isupper() and i > 0:
            out.append("_")
        out.append(ch.lower())
    return "".join(out)


def emit_event_union(events: list[EventDef]) -> list[str]:
    lines = [
        "pub const UnknownEvent = struct {",
        "    code: u8,",
        "    sequence: u16,",
        "    raw: [32]u8,",
        "};",
        "",
        "pub const Event = union(enum) {",
        "    unknown: UnknownEvent,",
    ]
    for event in events:
        lines.append(f"    {event_tag(event.name)}: {event.name}Event,")
    lines.append("};")
    lines.append("")
    lines.append("pub fn decodeEvent(reader: *std.Io.Reader) wire.Error!Event {")
    lines.append("    const code = (try reader.peek(1))[0] & 0x7f;")
    lines.append("    return switch (code) {")
    for event in events:
        lines.append(f"        {event.number} => .{{ .{event_tag(event.name)} = try {event.name}Event.decode(reader) }},")
    lines.append("        else => blk: {")
    lines.append("            const packet = try reader.take(32);")
    lines.append("            var raw: [32]u8 = undefined;")
    lines.append("            @memcpy(raw[0..], packet);")
    lines.append("            break :blk .{ .unknown = .{")
    lines.append("                .code = packet[0] & 0x7f,")
    lines.append("                .sequence = std.mem.readInt(u16, packet[2..4], .little),")
    lines.append("                .raw = raw,")
    lines.append("            } };")
    lines.append("        },")
    lines.append("    };")
    lines.append("}")
    return lines


def zig_name(name: str) -> str:
    if name == "type":
        return "type_atom"
    if name == "delete":
        return "delete_value"
    return name


if __name__ == "__main__":
    main()
