#!/usr/bin/env python3

from __future__ import annotations

import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path


XML_PATH = Path("/usr/share/xcb/xproto.xml")
OUT_PATH = Path("src/gen/xproto.zig")
TARGET_REQUESTS = ("InternAtom", "GetProperty", "GetInputFocus")

SCALAR_TYPES = {
    "BOOL": ("bool", 1),
    "BYTE": ("u8", 1),
    "CARD8": ("u8", 1),
    "CARD16": ("u16", 2),
    "CARD32": ("u32", 4),
    "char": ("u8", 1),
}


@dataclass(frozen=True)
class Field:
    kind: str
    name: str
    x_type: str
    zig_type: str
    size: int


@dataclass(frozen=True)
class Pad:
    bytes: int


@dataclass(frozen=True)
class ListField:
    name: str
    x_type: str
    zig_elem_type: str
    elem_size: int


@dataclass(frozen=True)
class ReplyField:
    name: str
    zig_type: str
    size: int
    offset: int


@dataclass(frozen=True)
class DerivedLengthField:
    name: str
    target_list: str
    size: int


def main() -> None:
    root = ET.parse(XML_PATH).getroot()
    requests = {child.attrib["name"]: child for child in root if child.tag == "request"}
    enums = {child.attrib["name"]: child for child in root if child.tag == "enum"}

    out = []
    emit(out, "// This file is generated by tools/gen_xproto.py.")
    emit(out, f"// Source: {XML_PATH}")
    emit(out, "")
    emit(out, 'const std = @import("std");')
    emit(out, 'const wire = @import("../wire.zig");')
    emit(out, "")
    emit(out, "pub const Atom = u32;")
    emit(out, "pub const Window = u32;")
    emit(out, "")

    emit_setup_types(out)
    emit(out, "")

    emit_enum(out, "GetPropertyType", enums["GetPropertyType"])
    emit(out, "")

    for request_name in TARGET_REQUESTS:
        emit_request_module(out, requests[request_name])
        emit(out, "")

    OUT_PATH.write_text("".join(out), encoding="utf-8")


def emit(buf: list[str], line: str) -> None:
    buf.append(line + "\n")


def emit_enum(buf: list[str], name: str, node: ET.Element) -> None:
    value = 0
    emit(buf, f"pub const {name} = enum(u32) {{")
    for item in node.findall("item"):
        item_name = item.attrib["name"]
        value_node = item.find("value")
        if value_node is not None and value_node.text is not None:
            value = int(value_node.text.strip(), 0)
        emit(buf, f"    {zig_name(item_name)} = {value},")
        value += 1
    emit(buf, "    _,")
    emit(buf, "};")


def emit_setup_types(buf: list[str]) -> None:
    emit(buf, "pub const SetupRequest = struct {")
    emit(buf, "    byteOrder: u8,")
    emit(buf, "    protocolMajorVersion: u16,")
    emit(buf, "    protocolMinorVersion: u16,")
    emit(buf, "    authorizationProtocolName: []const u8,")
    emit(buf, "    authorizationProtocolData: []const u8,")
    emit(buf, "")
    emit(buf, "    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {")
    emit(buf, "        try writer.writeByte(self.byteOrder);")
    emit(buf, "        try writer.writeByte(0);")
    emit(buf, "        try writer.writeInt(u16, self.protocolMajorVersion, .little);")
    emit(buf, "        try writer.writeInt(u16, self.protocolMinorVersion, .little);")
    emit(buf, "        try writer.writeInt(u16, @intCast(self.authorizationProtocolName.len), .little);")
    emit(buf, "        try writer.writeInt(u16, @intCast(self.authorizationProtocolData.len), .little);")
    emit(buf, "        try writer.writeInt(u16, 0, .little);")
    emit(buf, "        try writer.writeAll(self.authorizationProtocolName);")
    emit(buf, "        try writer.splatByteAll(0, wire.pad4(self.authorizationProtocolName.len));")
    emit(buf, "        try writer.writeAll(self.authorizationProtocolData);")
    emit(buf, "        try writer.splatByteAll(0, wire.pad4(self.authorizationProtocolData.len));")
    emit(buf, "    }")
    emit(buf, "};")
    emit(buf, "")

    emit(buf, "pub const Setup = struct {")
    emit(buf, "    status: u8,")
    emit(buf, "    protocolMajorVersion: u16,")
    emit(buf, "    protocolMinorVersion: u16,")
    emit(buf, "    releaseNumber: u32,")
    emit(buf, "    resourceIdBase: u32,")
    emit(buf, "    resourceIdMask: u32,")
    emit(buf, "    motionBufferSize: u32,")
    emit(buf, "    maximumRequestLength: u16,")
    emit(buf, "    rootsLen: u8,")
    emit(buf, "    pixmapFormatsLen: u8,")
    emit(buf, "    imageByteOrder: u8,")
    emit(buf, "    bitmapFormatBitOrder: u8,")
    emit(buf, "    bitmapFormatScanlineUnit: u8,")
    emit(buf, "    bitmapFormatScanlinePad: u8,")
    emit(buf, "    minKeycode: u8,")
    emit(buf, "    maxKeycode: u8,")
    emit(buf, "    root: Window,")
    emit(buf, "")
    emit(buf, "    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {")
    emit(buf, "        const status = try reader.takeByte();")
    emit(buf, "        if (status != 1) return error.UnexpectedReplyType;")
    emit(buf, "        _ = try reader.takeByte();")
    emit(buf, "        const protocol_major_version = try reader.takeInt(u16, .little);")
    emit(buf, "        const protocol_minor_version = try reader.takeInt(u16, .little);")
    emit(buf, "        const length_words = try reader.takeInt(u16, .little);")
    emit(buf, "        const extra_len = @as(usize, length_words) * 4;")
    emit(buf, "        const release_number = try reader.takeInt(u32, .little);")
    emit(buf, "        const resource_id_base = try reader.takeInt(u32, .little);")
    emit(buf, "        const resource_id_mask = try reader.takeInt(u32, .little);")
    emit(buf, "        const motion_buffer_size = try reader.takeInt(u32, .little);")
    emit(buf, "        const vendor_len = try reader.takeInt(u16, .little);")
    emit(buf, "        const maximum_request_length = try reader.takeInt(u16, .little);")
    emit(buf, "        const roots_len = try reader.takeByte();")
    emit(buf, "        const pixmap_formats_len = try reader.takeByte();")
    emit(buf, "        const image_byte_order = try reader.takeByte();")
    emit(buf, "        const bitmap_format_bit_order = try reader.takeByte();")
    emit(buf, "        const bitmap_format_scanline_unit = try reader.takeByte();")
    emit(buf, "        const bitmap_format_scanline_pad = try reader.takeByte();")
    emit(buf, "        const min_keycode = try reader.takeByte();")
    emit(buf, "        const max_keycode = try reader.takeByte();")
    emit(buf, "        _ = try reader.take(4);")
    emit(buf, "        if (roots_len == 0) return error.MalformedPacket;")
    emit(buf, "        const vendor_pad = wire.pad4(vendor_len);")
    emit(buf, "        _ = try reader.take(vendor_len);")
    emit(buf, "        _ = try reader.take(vendor_pad);")
    emit(buf, "        _ = try reader.take(@as(usize, pixmap_formats_len) * 8);")
    emit(buf, "        const root = try reader.takeInt(Window, .little);")
    emit(buf, "        const consumed: usize = 32 + vendor_len + vendor_pad + (@as(usize, pixmap_formats_len) * 8) + 4;")
    emit(buf, "        if (consumed > extra_len) return error.MalformedPacket;")
    emit(buf, "        _ = try reader.take(extra_len - consumed);")
    emit(buf, "        return .{")
    emit(buf, "            .status = status,")
    emit(buf, "            .protocolMajorVersion = protocol_major_version,")
    emit(buf, "            .protocolMinorVersion = protocol_minor_version,")
    emit(buf, "            .releaseNumber = release_number,")
    emit(buf, "            .resourceIdBase = resource_id_base,")
    emit(buf, "            .resourceIdMask = resource_id_mask,")
    emit(buf, "            .motionBufferSize = motion_buffer_size,")
    emit(buf, "            .maximumRequestLength = maximum_request_length,")
    emit(buf, "            .rootsLen = roots_len,")
    emit(buf, "            .pixmapFormatsLen = pixmap_formats_len,")
    emit(buf, "            .imageByteOrder = image_byte_order,")
    emit(buf, "            .bitmapFormatBitOrder = bitmap_format_bit_order,")
    emit(buf, "            .bitmapFormatScanlineUnit = bitmap_format_scanline_unit,")
    emit(buf, "            .bitmapFormatScanlinePad = bitmap_format_scanline_pad,")
    emit(buf, "            .minKeycode = min_keycode,")
    emit(buf, "            .maxKeycode = max_keycode,")
    emit(buf, "            .root = root,")
    emit(buf, "        };")
    emit(buf, "    }")
    emit(buf, "};")
    emit(buf, "")

    emit(buf, "pub const SetupFailed = struct {")
    emit(buf, "    status: u8,")
    emit(buf, "    protocolMajorVersion: u16,")
    emit(buf, "    protocolMinorVersion: u16,")
    emit(buf, "")
    emit(buf, "    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {")
    emit(buf, "        const status = try reader.takeByte();")
    emit(buf, "        const reason_len = try reader.takeByte();")
    emit(buf, "        const protocol_major_version = try reader.takeInt(u16, .little);")
    emit(buf, "        const protocol_minor_version = try reader.takeInt(u16, .little);")
    emit(buf, "        const length_words = try reader.takeInt(u16, .little);")
    emit(buf, "        const extra_len = @as(usize, length_words) * 4;")
    emit(buf, "        if (extra_len < reason_len) return error.MalformedPacket;")
    emit(buf, "        _ = try reader.take(reason_len);")
    emit(buf, "        _ = try reader.take(extra_len - reason_len);")
    emit(buf, "        return .{")
    emit(buf, "            .status = status,")
    emit(buf, "            .protocolMajorVersion = protocol_major_version,")
    emit(buf, "            .protocolMinorVersion = protocol_minor_version,")
    emit(buf, "        };")
    emit(buf, "    }")
    emit(buf, "};")
    emit(buf, "")

    emit(buf, "pub const SetupAuthenticate = struct {")
    emit(buf, "    status: u8,")
    emit(buf, "")
    emit(buf, "    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {")
    emit(buf, "        const status = try reader.takeByte();")
    emit(buf, "        _ = try reader.take(5);")
    emit(buf, "        const length_words = try reader.takeInt(u16, .little);")
    emit(buf, "        _ = try reader.take(@as(usize, length_words) * 4);")
    emit(buf, "        return .{ .status = status };")
    emit(buf, "    }")
    emit(buf, "};")


def emit_request_module(buf: list[str], request: ET.Element) -> None:
    name = request.attrib["name"]
    opcode = int(request.attrib["opcode"])
    body_nodes = [node for node in request if node.tag in {"field", "pad", "list"}]
    reply = request.find("reply")
    request_model = parse_request_body(body_nodes)

    emit(buf, f"pub const {name}Request = struct {{")
    emit(buf, f"    pub const opcode: u8 = {opcode};")
    emit(buf, "")
    for line in request_field_lines(request_model):
        emit(buf, line)
    if request_field_lines(request_model):
        emit(buf, "")
    for line in request_encode_lines(request_model):
        emit(buf, line)
    emit(buf, "};")

    if reply is not None:
        emit(buf, "")
        for line in reply_lines(
            name,
            parse_reply_body([node for node in reply if node.tag in {"field", "pad", "list"}]),
        ):
            emit(buf, line)


def request_field_lines(model: dict) -> list[str]:
    lines: list[str] = []
    if model["header_field"] is not None:
        field: Field = model["header_field"]
        lines.append(f"    {zig_name(field.name)}: {field.zig_type},")
    for item in model["body"]:
        if isinstance(item, Field):
            lines.append(f"    {zig_name(item.name)}: {item.zig_type},")
        elif isinstance(item, DerivedLengthField):
            continue
        elif isinstance(item, ListField):
            lines.append(f"    {zig_name(item.name)}: []const {item.zig_elem_type},")
    return lines


def request_encode_lines(model: dict) -> list[str]:
    body_bytes_expr: list[str] = []
    byte_len_uses_self = False
    for item in model["body"]:
        if isinstance(item, Field):
            body_bytes_expr.append(str(item.size))
        elif isinstance(item, DerivedLengthField):
            body_bytes_expr.append(str(item.size))
        elif isinstance(item, Pad):
            body_bytes_expr.append(str(item.bytes))
        elif isinstance(item, ListField):
            name = zig_name(item.name)
            body_bytes_expr.append(f"self.{name}.len")
            body_bytes_expr.append(f"wire.pad4(self.{name}.len)")
            byte_len_uses_self = True

    lines = [
        "    pub fn byteLen(self: @This()) usize {",
    ]
    if not byte_len_uses_self:
        lines.append("        _ = self;")
    lines.extend([
        f"        return 4 + {' + '.join(body_bytes_expr) if body_bytes_expr else '0'};",
        "    }",
        "",
        "    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {",
        "        try writer.writeByte(opcode);",
    ])
    header_field: Field | None = model["header_field"]
    if header_field is None:
        lines.append("        try writer.writeByte(0);")
    elif header_field.zig_type == "bool":
        lines.append(f"        try writer.writeByte(@intFromBool(self.{zig_name(header_field.name)}));")
    else:
        lines.append(f"        try writer.writeByte(self.{zig_name(header_field.name)});")
    lines.append("        try writer.writeInt(u16, @intCast(self.byteLen() / 4), .little);")
    if not model["body"]:
        lines.append("        return;")
        lines.append("    }")
        return lines
    for item in model["body"]:
        if isinstance(item, Field):
            name = zig_name(item.name)
            if item.zig_type == "bool":
                lines.append(f"        try writer.writeByte(@intFromBool(self.{name}));")
            elif item.size == 1:
                lines.append(f"        try writer.writeByte(self.{name});")
            elif item.size == 2:
                lines.append(f"        try writer.writeInt(u16, self.{name}, .little);")
            elif item.size == 4:
                lines.append(f"        try writer.writeInt(u32, self.{name}, .little);")
        elif isinstance(item, DerivedLengthField):
            list_name = zig_name(item.target_list)
            if item.size == 2:
                lines.append(f"        try writer.writeInt(u16, @intCast(self.{list_name}.len), .little);")
            elif item.size == 4:
                lines.append(f"        try writer.writeInt(u32, @intCast(self.{list_name}.len), .little);")
            else:
                raise AssertionError(item)
        elif isinstance(item, Pad):
            lines.append(f"        try writer.splatByteAll(0, {item.bytes});")
        elif isinstance(item, ListField):
            list_name = zig_name(item.name)
            lines.append(f"        try writer.writeAll(self.{list_name});")
            lines.append(f"        try writer.splatByteAll(0, wire.pad4(self.{list_name}.len));")
    lines.append("    }")
    return lines


def reply_lines(name: str, model: dict) -> list[str]:
    lines: list[str] = [f"pub const {name}Reply = struct {{"]
    for field in model["fields"]:
        lines.append(f"    {zig_name(field.name)}: {field.zig_type},")
    if model["list"] is not None:
        list_field: ListField = model["list"]
        lines.append(f"    {zig_name(list_field.name)}: []const {list_field.zig_elem_type},")
    lines.append("")
    if model["list"] is None:
        lines.extend(reply_decode_fixed_lines(model))
    else:
        lines.extend(reply_decode_variable_lines(model))
    lines.append("};")
    return lines


def reply_decode_fixed_lines(model: dict) -> list[str]:
    lines = [
        "    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {",
        "        if (try reader.takeByte() != 1) return error.UnexpectedReplyType;",
        "        _ = try reader.takeByte();",
        "        _ = try reader.takeInt(u16, .little);",
        "        _ = try reader.takeInt(u32, .little);",
        "        const result: @This() = .{",
    ]
    for field in model["fields"]:
        accessor = reply_field_accessor(field)
        lines.append(f"            .{zig_name(field.name)} = {accessor},")
    fixed_field_bytes = sum(field.size for field in model["fields"])
    trailing = 24 - fixed_field_bytes
    lines.append("        };")
    if trailing > 0:
        lines.append(f"        _ = try reader.take({trailing});")
    lines.append("        return result;")
    lines.append("    }")
    return lines


def reply_decode_variable_lines(model: dict) -> list[str]:
    list_field: ListField = model["list"]
    lines = [
        "    pub fn decode(reader: *std.Io.Reader, scratch: []u8) wire.Error!@This() {",
        "        if (try reader.takeByte() != 1) return error.UnexpectedReplyType;",
        "        const format = try reader.takeByte();",
        "        _ = try reader.takeInt(u16, .little);",
        "        const reply_len = @as(usize, try reader.takeInt(u32, .little)) * 4;",
        "        const type_atom = try reader.takeInt(Atom, .little);",
        "        const bytes_after = try reader.takeInt(u32, .little);",
        "        const value_len = try reader.takeInt(u32, .little);",
        "        _ = try reader.take(12);",
        "        const value_bytes = try wire.valueByteLen(format, value_len);",
        "        if (reply_len < value_bytes) return error.MalformedPacket;",
        "        if (scratch.len < value_bytes) return error.BufferTooSmall;",
        "        @memcpy(scratch[0..value_bytes], try reader.take(value_bytes));",
        "        _ = try reader.take(reply_len - value_bytes);",
        "        return .{",
        "            .format = format,",
        "            .type_atom = type_atom,",
        "            .bytesAfter = bytes_after,",
        "            .valueLen = value_len,",
        f"            .{zig_name(list_field.name)} = scratch[0..value_bytes],",
        "        };",
        "    }",
    ]
    return lines


def reply_field_accessor(field: ReplyField) -> str:
    if field.name == "format":
        return "try reader.takeByte()"
    if field.name == "revert_to":
        return "try reader.takeByte()"
    if field.size == 1:
        return "try reader.takeByte()"
    if field.size == 2:
        return "try reader.takeInt(u16, .little)"
    if field.size == 4:
        return f"try reader.takeInt({field.zig_type}, .little)"
    raise AssertionError(field)


def parse_request_body(nodes: list[ET.Element]) -> dict:
    header_field: Field | None = None
    body: list[Field | Pad | ListField | DerivedLengthField] = []
    index = 0
    if nodes and nodes[0].tag == "field":
        field = parse_field(nodes[0])
        if field.size == 1:
            header_field = field
            index = 1
    while index < len(nodes):
        node = nodes[index]
        if node.tag == "field":
            field = parse_field(node)
            target_list = inferred_list_name(field.name, nodes[index + 1 :])
            if target_list is not None:
                body.append(DerivedLengthField(name=field.name, target_list=target_list, size=field.size))
            else:
                body.append(field)
        elif node.tag == "pad":
            body.append(Pad(bytes=pad_bytes(node)))
        elif node.tag == "list":
            body.append(parse_list(node))
        index += 1
    return {"header_field": header_field, "body": body}


def parse_reply_body(nodes: list[ET.Element]) -> dict:
    fields: list[ReplyField] = []
    list_field: ListField | None = None
    offset = 8
    if nodes:
        first = nodes[0]
        if first.tag == "field" and scalar_size(first.attrib["type"]) == 1:
            field = parse_field(first)
            fields.append(ReplyField(name=field.name, zig_type=field.zig_type, size=field.size, offset=1))
            nodes = nodes[1:]
        elif first.tag == "pad" and pad_bytes(first) == 1:
            nodes = nodes[1:]
    for node in nodes:
        if node.tag == "field":
            field = parse_field(node)
            fields.append(ReplyField(name=field.name, zig_type=field.zig_type, size=field.size, offset=offset))
            offset += field.size
        elif node.tag == "pad":
            offset += pad_bytes(node)
        elif node.tag == "list":
            list_field = parse_list(node)
    return {"fields": fields, "list": list_field}


def parse_field(node: ET.Element) -> Field:
    x_type = node.attrib["type"]
    zig_type, size = zig_scalar_type(x_type)
    return Field(kind="field", name=node.attrib["name"], x_type=x_type, zig_type=zig_type, size=size)


def parse_list(node: ET.Element) -> ListField:
    x_type = node.attrib["type"]
    zig_type, size = zig_scalar_type(x_type)
    return ListField(name=node.attrib["name"], x_type=x_type, zig_elem_type=zig_type, elem_size=size)


def zig_scalar_type(x_type: str) -> tuple[str, int]:
    if x_type in {"ATOM", "WINDOW"}:
        return x_type.title().replace("_", ""), 4
    if x_type == "void":
        return "u8", 1
    if x_type in SCALAR_TYPES:
        return SCALAR_TYPES[x_type]
    raise ValueError(f"unsupported scalar type: {x_type}")


def scalar_size(x_type: str) -> int:
    return zig_scalar_type(x_type)[1]


def pad_bytes(node: ET.Element) -> int:
    if "bytes" in node.attrib:
        return int(node.attrib["bytes"], 0)
    raise ValueError(f"unsupported pad node: {ET.tostring(node, encoding='unicode')}")


def inferred_list_name(field_name: str, later_nodes: list[ET.Element]) -> str | None:
    if not field_name.endswith("_len"):
        return None
    candidate = field_name[: -len("_len")]
    for node in later_nodes:
        if node.tag == "list" and node.attrib["name"] == candidate:
            return candidate
    return None


def zig_name(name: str) -> str:
    if name == "type":
        return "type_atom"
    if name == "delete":
        return "delete_value"
    parts = name.split("_")
    return parts[0] + "".join(part.capitalize() for part in parts[1:])


if __name__ == "__main__":
    main()
