#!/usr/bin/env python3

from __future__ import annotations

import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path


XML_PATH = Path("/usr/share/xcb/xproto.xml")
OUT_PATH = Path("src/gen/xproto.zig")
TARGET_REQUESTS = ("InternAtom", "GetProperty", "GetInputFocus")

SCALAR_TYPES = {
    "BOOL": ("bool", 1),
    "BYTE": ("u8", 1),
    "CARD8": ("u8", 1),
    "CARD16": ("u16", 2),
    "CARD32": ("u32", 4),
    "char": ("u8", 1),
}


@dataclass(frozen=True)
class Field:
    name: str
    x_type: str
    zig_type: str
    size: int


@dataclass(frozen=True)
class PadBytes:
    bytes: int


@dataclass(frozen=True)
class PadAlign:
    align: int


@dataclass(frozen=True)
class FieldRefExpr:
    field_name: str


@dataclass(frozen=True)
class ValueExpr:
    value: int


@dataclass(frozen=True)
class MultiplyExpr:
    lhs: "Expr"
    rhs: "Expr"


@dataclass(frozen=True)
class DivideExpr:
    lhs: "Expr"
    rhs: "Expr"


Expr = FieldRefExpr | ValueExpr | MultiplyExpr | DivideExpr


@dataclass(frozen=True)
class LengthExpr:
    expr: Expr


@dataclass(frozen=True)
class ListField:
    name: str
    x_type: str
    elem_size: int | None
    length_expr: LengthExpr | None
    is_last: bool


Item = Field | PadBytes | PadAlign | ListField


@dataclass(frozen=True)
class StructDef:
    name: str
    items: list[Item]


@dataclass(frozen=True)
class RequestDef:
    name: str
    opcode: int
    header_field: Field | None
    body: list[Item]
    reply_items: list[Item] | None


def main() -> None:
    root = ET.parse(XML_PATH).getroot()
    requests_xml = {child.attrib["name"]: child for child in root if child.tag == "request"}
    structs_xml = {child.attrib["name"]: child for child in root if child.tag == "struct"}
    enums = {child.attrib["name"]: child for child in root if child.tag == "enum"}
    typedefs = {child.attrib["newname"]: child.attrib["oldname"] for child in root if child.tag == "typedef"}
    xidtypes = {child.attrib["name"] for child in root if child.tag == "xidtype"}

    requests = [
        parse_request(requests_xml[name], structs_xml, typedefs, xidtypes)
        for name in TARGET_REQUESTS
    ]

    struct_defs: dict[str, StructDef] = {}
    for name, node in structs_xml.items():
        try:
            struct_defs[name] = parse_struct(node, structs_xml, typedefs, xidtypes)
        except ValueError:
            continue
    emitted_structs = [
        struct_defs[name]
        for name in struct_defs
        if struct_supported(struct_defs[name], struct_defs)
    ]

    out: list[str] = []
    emit(out, "// This file is generated by tools/gen_xproto.py.")
    emit(out, f"// Source: {XML_PATH}")
    emit(out, "")
    emit(out, 'const std = @import("std");')
    emit(out, 'const wire = @import("../wire.zig");')
    emit(out, "")
    emit(out, "pub const Atom = u32;")
    emit(out, "pub const Window = u32;")
    emit(out, "")

    for struct_def in emitted_structs:
        for line in emit_plain_struct(struct_def, struct_defs):
            emit(out, line)
        emit(out, "")

    emit_enum(out, "GetPropertyType", enums["GetPropertyType"])
    emit(out, "")

    for request in requests:
        for line in emit_request_module(request):
            emit(out, line)
        emit(out, "")

    OUT_PATH.write_text("".join(out), encoding="utf-8")


def emit(buf: list[str], line: str) -> None:
    buf.append(line + "\n")


def emit_enum(buf: list[str], name: str, node: ET.Element) -> None:
    value = 0
    emit(buf, f"pub const {name} = enum(u32) {{")
    for item in node.findall("item"):
        item_name = item.attrib["name"]
        value_node = item.find("value")
        if value_node is not None and value_node.text is not None:
            value = int(value_node.text.strip(), 0)
        emit(buf, f"    {zig_name(item_name)} = {value},")
        value += 1
    emit(buf, "    _,")
    emit(buf, "};")


def parse_request(
    node: ET.Element,
    structs_xml: dict[str, ET.Element],
    typedefs: dict[str, str],
    xidtypes: set[str],
) -> RequestDef:
    body_nodes = [child for child in node if child.tag in {"field", "pad", "list"}]
    header_field: Field | None = None
    index = 0
    if body_nodes and body_nodes[0].tag == "field":
        first = parse_field(body_nodes[0], typedefs, xidtypes)
        if first.size == 1:
            header_field = first
            index = 1
    body = parse_items(body_nodes[index:], structs_xml, typedefs, xidtypes)
    reply = node.find("reply")
    reply_items = None
    if reply is not None:
        reply_items = parse_items([child for child in reply if child.tag in {"field", "pad", "list"}], structs_xml, typedefs, xidtypes)
    return RequestDef(
        name=node.attrib["name"],
        opcode=int(node.attrib["opcode"]),
        header_field=header_field,
        body=body,
        reply_items=reply_items,
    )


def parse_struct(
    node: ET.Element,
    structs_xml: dict[str, ET.Element],
    typedefs: dict[str, str],
    xidtypes: set[str],
) -> StructDef:
    items = parse_items([child for child in node if child.tag in {"field", "pad", "list"}], structs_xml, typedefs, xidtypes)
    return StructDef(name=node.attrib["name"], items=items)


def parse_items(
    nodes: list[ET.Element],
    structs_xml: dict[str, ET.Element],
    typedefs: dict[str, str],
    xidtypes: set[str],
) -> list[Item]:
    items: list[Item] = []
    for index, node in enumerate(nodes):
        if node.tag == "field":
            items.append(parse_field(node, typedefs, xidtypes))
        elif node.tag == "pad":
            if "bytes" in node.attrib:
                items.append(PadBytes(bytes=int(node.attrib["bytes"], 0)))
            elif "align" in node.attrib:
                items.append(PadAlign(align=int(node.attrib["align"], 0)))
            else:
                raise ValueError(f"unsupported pad node: {ET.tostring(node, encoding='unicode')}")
        elif node.tag == "list":
            x_type = node.attrib["type"]
            items.append(
                ListField(
                    name=node.attrib["name"],
                    x_type=x_type,
                    elem_size=resolve_type_size(x_type, structs_xml, typedefs, xidtypes),
                    length_expr=parse_length_expr(node),
                    is_last=index == len(nodes) - 1,
                )
            )
        else:
            raise ValueError(node.tag)
    return items


def parse_field(node: ET.Element, typedefs: dict[str, str], xidtypes: set[str]) -> Field:
    zig_type, size = zig_scalar_type(node.attrib["type"], typedefs, xidtypes)
    return Field(
        name=node.attrib["name"],
        x_type=node.attrib["type"],
        zig_type=zig_type,
        size=size,
    )


def resolve_type_size(
    x_type: str,
    structs_xml: dict[str, ET.Element],
    typedefs: dict[str, str],
    xidtypes: set[str],
) -> int | None:
    if x_type == "void":
        return 1
    if x_type in structs_xml:
        return None
    _, size = zig_scalar_type(x_type, typedefs, xidtypes)
    return size


def zig_scalar_type(x_type: str, typedefs: dict[str, str], xidtypes: set[str]) -> tuple[str, int]:
    if x_type in xidtypes:
        return "u32", 4
    while x_type in typedefs:
        x_type = typedefs[x_type]
    if x_type in {"ATOM", "WINDOW"}:
        return x_type.title().replace("_", ""), 4
    if x_type == "void":
        return "u8", 1
    if x_type in SCALAR_TYPES:
        return SCALAR_TYPES[x_type]
    raise ValueError(f"unsupported scalar type: {x_type}")


def strip_len_suffix(name: str) -> str:
    if name.endswith("_len"):
        return name[: -len("_len")]
    return name


def parse_length_expr(node: ET.Element) -> LengthExpr | None:
    if len(node) == 0:
        return None
    if len(node) != 1:
        raise ValueError(f"unsupported list expression: {ET.tostring(node, encoding='unicode')}")
    return LengthExpr(expr=parse_expr(node[0]))


def parse_expr(node: ET.Element) -> Expr:
    if node.tag == "fieldref":
        if node.text is None:
            raise ValueError(f"empty fieldref: {ET.tostring(node, encoding='unicode')}")
        return FieldRefExpr(field_name=node.text.strip())
    if node.tag == "value":
        if node.text is None:
            raise ValueError(f"empty value: {ET.tostring(node, encoding='unicode')}")
        return ValueExpr(value=int(node.text.strip(), 0))
    if node.tag == "op":
        if len(node) != 2:
            raise ValueError(f"unsupported op arity: {ET.tostring(node, encoding='unicode')}")
        lhs = parse_expr(node[0])
        rhs = parse_expr(node[1])
        op = node.attrib.get("op")
        if op == "*":
            return MultiplyExpr(lhs=lhs, rhs=rhs)
        if op == "/":
            return DivideExpr(lhs=lhs, rhs=rhs)
    raise ValueError(f"unsupported expression: {ET.tostring(node, encoding='unicode')}")


def struct_supported(struct_def: StructDef, structs: dict[str, StructDef]) -> bool:
    for item in struct_def.items:
        if isinstance(item, ListField):
            if is_struct_list(item, structs):
                if item.length_expr is None:
                    return False
                if simple_fieldref_name(item.length_expr.expr) is None:
                    return False
                continue
            if item.length_expr is None and not item.is_last:
                return False
            if item.elem_size is None and not item.is_last:
                return False
    return True


def emit_plain_struct(struct_def: StructDef, structs: dict[str, StructDef]) -> list[str]:
    derived_fields = derived_length_fields(struct_def.items)
    lines = [f"pub const {struct_def.name} = struct {{"]
    lines.append("    pub const View = wire.StructView(@This());")
    lines.append("")
    for item in struct_def.items:
        if isinstance(item, Field) and item.name not in derived_fields:
            lines.append(f"    {zig_name(item.name)}: {item.zig_type},")
        elif isinstance(item, ListField):
            lines.append(f"    {zig_name(item.name)}: {list_field_zig_type(item, structs)},")
    lines.append("")
    lines.extend(emit_plain_struct_encode(struct_def, structs))
    lines.append("")
    lines.extend(emit_plain_struct_decode(struct_def, structs))
    lines.append("};")
    return lines


def emit_plain_struct_encode(struct_def: StructDef, structs: dict[str, StructDef]) -> list[str]:
    uses_self_for_len = any(isinstance(item, ListField) for item in struct_def.items)
    byte_len_terms: list[str] = []
    for item in struct_def.items:
        if isinstance(item, Field):
            byte_len_terms.append(str(item.size))
        elif isinstance(item, PadBytes):
            byte_len_terms.append(str(item.bytes))
        elif isinstance(item, PadAlign):
            prev = previous_list(struct_def.items, item)
            assert prev is not None
            byte_len_terms.append(f"wire.pad4({list_field_len_expr(prev, structs)})")
        elif isinstance(item, ListField):
            byte_len_terms.append(list_field_len_expr(item, structs))
    lines = [
        "    pub fn byteLen(self: @This()) usize {",
    ]
    if not uses_self_for_len:
        lines.append("        _ = self;")
    lines.append(f"        return {' + '.join(byte_len_terms) if byte_len_terms else '0'};")
    lines.append("    }")
    lines.append("")
    lines.append("    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {")
    derived_fields = derived_length_fields(struct_def.items)
    for item in struct_def.items:
        if isinstance(item, Field):
            field_name = zig_name(item.name)
            if item.name in derived_fields:
                list_item = derived_fields[item.name]
                assert list_item.length_expr is not None
                if list_is_view(list_item, structs):
                    count_expr = f"self.{zig_name(list_item.name)}.count"
                    value_expr = f"@intCast({count_expr})"
                else:
                    byte_len_expr = list_field_len_expr(list_item, structs)
                    divisor = scalar_list_elem_size(list_item)
                    if divisor != 1:
                        lines.append(f"        std.debug.assert({byte_len_expr} % {divisor} == 0);")
                        value_expr = f"@intCast(@divExact({byte_len_expr}, {divisor}))"
                    else:
                        value_expr = f"@intCast({byte_len_expr})"
                if item.size == 1:
                    lines.append(f"        try writer.writeByte({value_expr});")
                elif item.size == 2:
                    lines.append(f"        try writer.writeInt(u16, {value_expr}, .little);")
                elif item.size == 4:
                    lines.append(f"        try writer.writeInt(u32, {value_expr}, .little);")
                continue
            if item.zig_type == "bool":
                lines.append(f"        try writer.writeByte(@intFromBool(self.{field_name}));")
            elif item.size == 1:
                lines.append(f"        try writer.writeByte(self.{field_name});")
            elif item.size == 2:
                lines.append(f"        try writer.writeInt(u16, self.{field_name}, .little);")
            elif item.size == 4:
                lines.append(f"        try writer.writeInt(u32, self.{field_name}, .little);")
        elif isinstance(item, PadBytes):
            lines.append(f"        try writer.splatByteAll(0, {item.bytes});")
        elif isinstance(item, PadAlign):
            prev = previous_list(struct_def.items, item)
            assert prev is not None
            lines.append(f"        try writer.splatByteAll(0, wire.pad4({list_field_len_expr(prev, structs)}));")
        elif isinstance(item, ListField):
            if (
                item.length_expr is not None
                and not is_struct_list(item, structs)
                and simple_fieldref_name(item.length_expr.expr) not in derived_fields
            ):
                lines.append(
                    f"        std.debug.assert({list_field_len_expr(item, structs)} == {scalar_list_byte_len_expr(item, 'self.')});"
                )
            lines.append(f"        try writer.writeAll({list_field_bytes_expr(item, structs)});")
    lines.append("    }")
    return lines


def emit_plain_struct_decode(struct_def: StructDef, structs: dict[str, StructDef]) -> list[str]:
    derived_fields = derived_length_fields(struct_def.items)
    locals_lines: list[str] = []
    result_lines: list[str] = []
    count_sizes: dict[str, int] = {}
    for item in struct_def.items:
        if isinstance(item, Field):
            value_expr = decode_field_expr(item)
            locals_lines.append(f"        const {zig_name(item.name)} = {value_expr};")
            if item.name not in derived_fields:
                result_lines.append(f"            .{zig_name(item.name)} = {zig_name(item.name)},")
            if item.name.endswith("_len"):
                count_sizes[item.name] = item.size
        elif isinstance(item, PadBytes):
            locals_lines.append(f"        _ = try reader.take({item.bytes});")
        elif isinstance(item, PadAlign):
            prev = previous_list(struct_def.items, item)
            assert prev is not None
            locals_lines.append(f"        _ = try reader.take(wire.pad4({decoded_list_len_expr(prev, structs)}));")
        elif isinstance(item, ListField):
            if list_is_view(item, structs):
                locals_lines.append(
                    f"        const {zig_name(item.name)} = try wire.take_struct_view({item.x_type}, reader, {view_count_expr(item)});"
                )
            else:
                if item.is_last and item.elem_size is None:
                    locals_lines.append(f"        const {zig_name(item.name)} = reader.buffered();")
                    locals_lines.append(f"        _ = try reader.take({zig_name(item.name)}.len);")
                else:
                    byte_len_expr = scalar_list_byte_len_expr(item)
                    locals_lines.append(f"        const {zig_name(item.name)} = try reader.take({byte_len_expr});")
            result_lines.append(
                f"            .{zig_name(item.name)} = {decoded_list_value_expr(item, structs)},"
            )
    lines = [
        "    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {",
    ]
    lines.extend(locals_lines)
    lines.append("        return .{")
    lines.extend(result_lines)
    lines.append("        };")
    lines.append("    }")
    return lines


def previous_list(items: list[Item], target: PadAlign) -> ListField | None:
    prev: ListField | None = None
    for item in items:
        if item is target:
            return prev
        if isinstance(item, ListField):
            prev = item
    return None


def derived_length_fields(items: list[Item]) -> dict[str, ListField]:
    derived: dict[str, ListField] = {}
    for item in items:
        if isinstance(item, ListField) and item.length_expr is not None:
            field_name = simple_fieldref_name(item.length_expr.expr)
            if field_name is not None and field_name.endswith("_len"):
                derived[field_name] = item
    return derived

def list_is_view(item: ListField, structs: dict[str, StructDef]) -> bool:
    return is_struct_list(item, structs)


def is_struct_list(item: ListField, structs: dict[str, StructDef]) -> bool:
    return item.x_type in structs


def list_field_zig_type(item: ListField, structs: dict[str, StructDef]) -> str:
    if list_is_view(item, structs):
        return f"{item.x_type}.View"
    return "[]const u8"


def list_field_len_expr(item: ListField, structs: dict[str, StructDef]) -> str:
    if list_is_view(item, structs):
        return f"self.{zig_name(item.name)}.bytes.len"
    return f"self.{zig_name(item.name)}.len"


def list_field_bytes_expr(item: ListField, structs: dict[str, StructDef]) -> str:
    if list_is_view(item, structs):
        return f"self.{zig_name(item.name)}.bytes"
    return f"self.{zig_name(item.name)}"


def decoded_list_len_expr(item: ListField, structs: dict[str, StructDef]) -> str:
    if list_is_view(item, structs):
        return f"{zig_name(item.name)}.bytes.len"
    return f"{zig_name(item.name)}.len"


def decoded_list_value_expr(item: ListField, structs: dict[str, StructDef]) -> str:
    if list_is_view(item, structs):
        return zig_name(item.name)
    return zig_name(item.name)


def view_count_expr(item: ListField) -> str:
    if item.length_expr is None:
        raise ValueError(f"struct view without count expression: {item.name}")
    field_name = simple_fieldref_name(item.length_expr.expr)
    if field_name is None:
        raise ValueError(f"struct view count must be direct fieldref: {item.name}")
    return f"@as(usize, {zig_name(field_name)})"


def scalar_list_byte_len_expr(item: ListField, prefix: str = "") -> str:
    if item.length_expr is None:
        return "reader.buffered().len"
    elem_size = scalar_list_elem_size(item)
    count_expr = expr_to_zig(item.length_expr.expr, prefix)
    if elem_size == 1:
        return count_expr
    return f"({count_expr}) * {elem_size}"


def scalar_list_elem_size(item: ListField) -> int:
    if item.elem_size is None:
        raise ValueError(f"scalar list without fixed element size: {item.name}")
    return item.elem_size


def expr_to_zig(expr: Expr, prefix: str = "") -> str:
    if isinstance(expr, FieldRefExpr):
        return f"@as(usize, {prefix}{zig_name(expr.field_name)})"
    if isinstance(expr, ValueExpr):
        return str(expr.value)
    if isinstance(expr, MultiplyExpr):
        return f"({expr_to_zig(expr.lhs, prefix)} * {expr_to_zig(expr.rhs, prefix)})"
    if isinstance(expr, DivideExpr):
        return f"@divExact({expr_to_zig(expr.lhs, prefix)}, {expr_to_zig(expr.rhs, prefix)})"
    raise AssertionError(expr)


def simple_fieldref_name(expr: Expr) -> str | None:
    if isinstance(expr, FieldRefExpr):
        return expr.field_name
    return None


def decode_field_expr(item: Field) -> str:
    if item.zig_type == "bool":
        return "(try reader.takeByte()) != 0"
    if item.size == 1:
        return "try reader.takeByte()"
    if item.size == 2:
        return "try reader.takeInt(u16, .little)"
    if item.size == 4:
        return f"try reader.takeInt({item.zig_type}, .little)"
    raise AssertionError(item)


def emit_request_module(request: RequestDef) -> list[str]:
    derived_fields = derived_length_fields(request.body)
    lines = [f"pub const {request.name}Request = struct {{"]
    lines.append(f"    pub const opcode: u8 = {request.opcode};")
    lines.append("")
    if request.header_field is not None:
        lines.append(f"    {zig_name(request.header_field.name)}: {request.header_field.zig_type},")
    for item in request.body:
        if isinstance(item, Field) and item.name not in derived_fields:
            lines.append(f"    {zig_name(item.name)}: {item.zig_type},")
        elif isinstance(item, ListField):
            lines.append(f"    {zig_name(item.name)}: []const u8,")
    lines.append("")
    lines.extend(emit_request_encode(request))
    lines.append("};")

    if request.reply_items is not None:
        lines.append("")
        lines.extend(emit_reply_struct(request.name, request.reply_items))
    return lines


def emit_request_encode(request: RequestDef) -> list[str]:
    body_terms: list[str] = []
    uses_self = False
    for item in request.body:
        if isinstance(item, Field):
            body_terms.append(str(item.size))
        elif isinstance(item, PadBytes):
            body_terms.append(str(item.bytes))
        elif isinstance(item, PadAlign):
            prev = previous_list(request.body, item)
            assert prev is not None
            body_terms.append(f"wire.pad4(self.{zig_name(prev.name)}.len)")
            uses_self = True
        elif isinstance(item, ListField):
            body_terms.append(f"self.{zig_name(item.name)}.len")
            uses_self = True
    lines = [
        "    pub fn byteLen(self: @This()) usize {",
    ]
    if not uses_self:
        lines.append("        _ = self;")
    raw_len = f"4 + {' + '.join(body_terms) if body_terms else '0'}"
    lines.append(f"        const raw_len = {raw_len};")
    lines.append("        return raw_len + wire.pad4(raw_len);")
    lines.append("    }")
    lines.append("")
    lines.append("    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {")
    derived_fields = derived_length_fields(request.body)
    lines.append(f"        const raw_len = {raw_len};")
    lines.append("        try writer.writeByte(opcode);")
    if request.header_field is None:
        lines.append("        try writer.writeByte(0);")
    elif request.header_field.zig_type == "bool":
        lines.append(f"        try writer.writeByte(@intFromBool(self.{zig_name(request.header_field.name)}));")
    else:
        lines.append(f"        try writer.writeByte(self.{zig_name(request.header_field.name)});")
    lines.append("        try writer.writeInt(u16, @intCast(self.byteLen() / 4), .little);")
    for item in request.body:
        if isinstance(item, Field):
            field_name = zig_name(item.name)
            if item.name in derived_fields:
                list_item = derived_fields[item.name]
                assert list_item.length_expr is not None
                byte_len_expr = f"self.{zig_name(list_item.name)}.len"
                divisor = list_item.elem_size or 1
                if divisor != 1:
                    lines.append(f"        std.debug.assert({byte_len_expr} % {divisor} == 0);")
                    value_expr = f"@intCast(@divExact({byte_len_expr}, {divisor}))"
                else:
                    value_expr = f"@intCast({byte_len_expr})"
                if item.size == 1:
                    lines.append(f"        try writer.writeByte({value_expr});")
                elif item.size == 2:
                    lines.append(f"        try writer.writeInt(u16, {value_expr}, .little);")
                elif item.size == 4:
                    lines.append(f"        try writer.writeInt(u32, {value_expr}, .little);")
                continue
            if item.zig_type == "bool":
                lines.append(f"        try writer.writeByte(@intFromBool(self.{field_name}));")
            elif item.size == 1:
                lines.append(f"        try writer.writeByte(self.{field_name});")
            elif item.size == 2:
                lines.append(f"        try writer.writeInt(u16, self.{field_name}, .little);")
            elif item.size == 4:
                lines.append(f"        try writer.writeInt(u32, self.{field_name}, .little);")
        elif isinstance(item, PadBytes):
            lines.append(f"        try writer.splatByteAll(0, {item.bytes});")
        elif isinstance(item, PadAlign):
            prev = previous_list(request.body, item)
            assert prev is not None
            lines.append(f"        try writer.splatByteAll(0, wire.pad4(self.{zig_name(prev.name)}.len));")
        elif isinstance(item, ListField):
            if (
                item.length_expr is not None
                and item.elem_size is not None
                and simple_fieldref_name(item.length_expr.expr) not in derived_fields
            ):
                lines.append(
                    f"        std.debug.assert(self.{zig_name(item.name)}.len == {list_byte_len_expr(item, 'self.')});"
                )
            lines.append(f"        try writer.writeAll(self.{zig_name(item.name)});")
    lines.append("        try writer.splatByteAll(0, wire.pad4(raw_len));")
    lines.append("    }")
    return lines


def emit_reply_struct(name: str, items: list[Item]) -> list[str]:
    scalar_fields = [item for item in items if isinstance(item, Field)]
    list_fields = [item for item in items if isinstance(item, ListField)]
    lines = [f"pub const {name}Reply = struct {{"]
    for field in scalar_fields:
        lines.append(f"    {zig_name(field.name)}: {field.zig_type},")
    for list_field in list_fields:
        lines.append(f"    {zig_name(list_field.name)}: []const u8,")
    lines.append("")
    if list_fields:
        lines.extend(emit_reply_decode_variable(items))
    else:
        lines.extend(emit_reply_decode_fixed(items))
    lines.append("};")
    return lines


def emit_reply_decode_fixed(items: list[Item]) -> list[str]:
    scalar_fields = [item for item in items if isinstance(item, Field)]
    locals_lines: list[str] = [
        "    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {",
        "        if (try reader.takeByte() != 1) return error.UnexpectedReplyType;",
    ]
    body_field_bytes = 0
    first_item = items[0] if items else None
    remaining_items = items
    if isinstance(first_item, Field):
        if first_item.size != 1:
            raise ValueError("first fixed reply field must be 1 byte")
        locals_lines.append(f"        const {zig_name(first_item.name)} = {decode_field_expr(first_item)};")
        remaining_items = items[1:]
    elif isinstance(first_item, PadBytes):
        if first_item.bytes != 1:
            raise ValueError("first fixed reply pad must be 1 byte")
        locals_lines.append("        _ = try reader.takeByte();")
        remaining_items = items[1:]
    else:
        locals_lines.append("        _ = try reader.takeByte();")
    locals_lines.extend([
        "        _ = try reader.takeInt(u16, .little);",
        "        _ = try reader.takeInt(u32, .little);",
    ])
    for item in remaining_items:
        if isinstance(item, Field):
            locals_lines.append(f"        const {zig_name(item.name)} = {decode_field_expr(item)};")
            body_field_bytes += item.size
        elif isinstance(item, PadBytes):
            locals_lines.append(f"        _ = try reader.take({item.bytes});")
            body_field_bytes += item.bytes
        elif isinstance(item, PadAlign):
            raise ValueError("reply align pad unsupported")
        elif isinstance(item, ListField):
            raise ValueError("fixed reply cannot contain list")
    trailing = 24 - body_field_bytes
    if trailing > 0:
        locals_lines.append(f"        _ = try reader.take({trailing});")
    locals_lines.append("        return .{")
    for field in scalar_fields:
        locals_lines.append(f"            .{zig_name(field.name)} = {zig_name(field.name)},")
    locals_lines.append("        };")
    locals_lines.append("    }")
    return locals_lines


def emit_reply_decode_variable(items: list[Item]) -> list[str]:
    scalar_fields = [item for item in items if isinstance(item, Field)]
    list_field = next(item for item in items if isinstance(item, ListField))
    body_lines = [
        "    pub fn decode(reader: *std.Io.Reader, scratch: []u8) wire.Error!@This() {",
        "        if (try reader.takeByte() != 1) return error.UnexpectedReplyType;",
        "        const format = try reader.takeByte();",
        "        _ = try reader.takeInt(u16, .little);",
        "        const reply_len = @as(usize, try reader.takeInt(u32, .little)) * 4;",
        "        const type_atom = try reader.takeInt(Atom, .little);",
        "        const bytes_after = try reader.takeInt(u32, .little);",
        "        const value_len = try reader.takeInt(u32, .little);",
        "        _ = try reader.take(12);",
        "        const value_bytes = try wire.valueByteLen(format, value_len);",
        "        if (reply_len < value_bytes) return error.MalformedPacket;",
        "        if (scratch.len < value_bytes) return error.BufferTooSmall;",
        "        @memcpy(scratch[0..value_bytes], try reader.take(value_bytes));",
        "        _ = try reader.take(reply_len - value_bytes);",
        "        return .{",
        "            .format = format,",
        "            .type_atom = type_atom,",
        f"            .{zig_name('bytes_after')} = bytes_after,",
        f"            .{zig_name('value_len')} = value_len,",
        f"            .{zig_name(list_field.name)} = scratch[0..value_bytes],",
        "        };",
        "    }",
    ]
    return body_lines


def zig_name(name: str) -> str:
    if name == "type":
        return "type_atom"
    if name == "delete":
        return "delete_value"
    return name


if __name__ == "__main__":
    main()
