// zig fmt: off
// This file is generated by tools/genproto.py

const std = @import("std");
const wire = @import("wire.zig");
const errors = @import("errors.zig");
const extensions = @import("extensions.zig");
const xproto = @import("xproto.zig");
const EncodeError = errors.EncodeError;
const DecodeError = errors.DecodeError;
const AllocDecodeError = errors.AllocDecodeError;
const BufferDecodeError = errors.BufferDecodeError;

pub const Seg = enum(u32) { _ };

pub const Error = enum(u32) {
    BadSeg = 0,
    _,
};

pub const Attach = struct {
    pub const opcode: u8 = 1;
    pub const extension: ?extensions.Extension = .MIT_SHM;
    pub const Reply = void;

    shmseg: Seg,
    shmid: u32,
    read_only: bool,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 4 + 1 + 3;
    }

    pub fn headerByte1(self: @This()) u8 {
        _ = self;
        return 0;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) EncodeError!void {
        try writer.writeInt(u32, @intFromEnum(self.shmseg), .little);
        try writer.writeInt(u32, self.shmid, .little);
        try writer.writeByte(@intFromBool(self.read_only));
        try writer.splatByteAll(0, 3);
    }

};

pub const CreatePixmap = struct {
    pub const opcode: u8 = 5;
    pub const extension: ?extensions.Extension = .MIT_SHM;
    pub const Reply = void;

    pid: xproto.Pixmap,
    drawable: xproto.Drawable,
    width: u16,
    height: u16,
    depth: u8,
    shmseg: Seg,
    offset: u32,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 4 + 2 + 2 + 1 + 3 + 4 + 4;
    }

    pub fn headerByte1(self: @This()) u8 {
        _ = self;
        return 0;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) EncodeError!void {
        try writer.writeInt(u32, @intFromEnum(self.pid), .little);
        try self.drawable.encode(writer);
        try writer.writeInt(u16, self.width, .little);
        try writer.writeInt(u16, self.height, .little);
        try writer.writeByte(self.depth);
        try writer.splatByteAll(0, 3);
        try writer.writeInt(u32, @intFromEnum(self.shmseg), .little);
        try writer.writeInt(u32, self.offset, .little);
    }

};

pub const Detach = struct {
    pub const opcode: u8 = 2;
    pub const extension: ?extensions.Extension = .MIT_SHM;
    pub const Reply = void;

    shmseg: Seg,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4;
    }

    pub fn headerByte1(self: @This()) u8 {
        _ = self;
        return 0;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) EncodeError!void {
        try writer.writeInt(u32, @intFromEnum(self.shmseg), .little);
    }

};

pub const GetImageReply = struct {
    depth: u8,
    visual: u32,
    size: u32,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 1 + 4 + 4;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) EncodeError!void {
        try writer.writeByte(self.depth);
        try writer.writeInt(u32, self.visual, .little);
        try writer.writeInt(u32, self.size, .little);
    }

    pub fn decode(reader: *std.Io.Reader) DecodeError!@This() {
        _ = try reader.takeByte();
        const depth = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        _ = try reader.takeInt(u32, .little);
        const visual = try reader.takeInt(u32, .little);
        const size = try reader.takeInt(u32, .little);
        return .{
            .depth = depth,
            .visual = visual,
            .size = size,
        };
    }

};

pub const GetImage = struct {
    pub const opcode: u8 = 4;
    pub const extension: ?extensions.Extension = .MIT_SHM;
    pub const Reply = GetImageReply;

    drawable: xproto.Drawable,
    x: i16,
    y: i16,
    width: u16,
    height: u16,
    plane_mask: u32,
    format: u8,
    shmseg: Seg,
    offset: u32,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 2 + 2 + 2 + 2 + 4 + 1 + 3 + 4 + 4;
    }

    pub fn headerByte1(self: @This()) u8 {
        _ = self;
        return 0;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) EncodeError!void {
        try self.drawable.encode(writer);
        try writer.writeInt(i16, self.x, .little);
        try writer.writeInt(i16, self.y, .little);
        try writer.writeInt(u16, self.width, .little);
        try writer.writeInt(u16, self.height, .little);
        try writer.writeInt(u32, self.plane_mask, .little);
        try writer.writeByte(self.format);
        try writer.splatByteAll(0, 3);
        try writer.writeInt(u32, @intFromEnum(self.shmseg), .little);
        try writer.writeInt(u32, self.offset, .little);
    }

};

pub const PutImage = struct {
    pub const opcode: u8 = 3;
    pub const extension: ?extensions.Extension = .MIT_SHM;
    pub const Reply = void;

    drawable: xproto.Drawable,
    gc: xproto.Gcontext,
    total_width: u16,
    total_height: u16,
    src_x: u16,
    src_y: u16,
    src_width: u16,
    src_height: u16,
    dst_x: i16,
    dst_y: i16,
    depth: u8,
    format: u8,
    send_event: bool,
    shmseg: Seg,
    offset: u32,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 4 + 2 + 2 + 2 + 2 + 2 + 2 + 2 + 2 + 1 + 1 + 1 + 1 + 4 + 4;
    }

    pub fn headerByte1(self: @This()) u8 {
        _ = self;
        return 0;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) EncodeError!void {
        try self.drawable.encode(writer);
        try writer.writeInt(u32, @intFromEnum(self.gc), .little);
        try writer.writeInt(u16, self.total_width, .little);
        try writer.writeInt(u16, self.total_height, .little);
        try writer.writeInt(u16, self.src_x, .little);
        try writer.writeInt(u16, self.src_y, .little);
        try writer.writeInt(u16, self.src_width, .little);
        try writer.writeInt(u16, self.src_height, .little);
        try writer.writeInt(i16, self.dst_x, .little);
        try writer.writeInt(i16, self.dst_y, .little);
        try writer.writeByte(self.depth);
        try writer.writeByte(self.format);
        try writer.writeByte(@intFromBool(self.send_event));
        try writer.splatByteAll(0, 1);
        try writer.writeInt(u32, @intFromEnum(self.shmseg), .little);
        try writer.writeInt(u32, self.offset, .little);
    }

};

pub const QueryVersionReply = struct {
    shared_pixmaps: bool,
    major_version: u16,
    minor_version: u16,
    uid: u16,
    gid: u16,
    pixmap_format: u8,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 1 + 2 + 2 + 2 + 2 + 1 + 15;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) EncodeError!void {
        try writer.writeByte(@intFromBool(self.shared_pixmaps));
        try writer.writeInt(u16, self.major_version, .little);
        try writer.writeInt(u16, self.minor_version, .little);
        try writer.writeInt(u16, self.uid, .little);
        try writer.writeInt(u16, self.gid, .little);
        try writer.writeByte(self.pixmap_format);
        try writer.splatByteAll(0, 15);
    }

    pub fn decode(reader: *std.Io.Reader) DecodeError!@This() {
        _ = try reader.takeByte();
        const shared_pixmaps = (try reader.takeByte()) != 0;
        _ = try reader.takeInt(u16, .little);
        _ = try reader.takeInt(u32, .little);
        const major_version = try reader.takeInt(u16, .little);
        const minor_version = try reader.takeInt(u16, .little);
        const uid = try reader.takeInt(u16, .little);
        const gid = try reader.takeInt(u16, .little);
        const pixmap_format = try reader.takeByte();
        _ = try reader.take(15);
        return .{
            .shared_pixmaps = shared_pixmaps,
            .major_version = major_version,
            .minor_version = minor_version,
            .uid = uid,
            .gid = gid,
            .pixmap_format = pixmap_format,
        };
    }

};

pub const QueryVersion = struct {
    pub const opcode: u8 = 0;
    pub const extension: ?extensions.Extension = .MIT_SHM;
    pub const Reply = QueryVersionReply;


    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 0;
    }

    pub fn headerByte1(self: @This()) u8 {
        _ = self;
        return 0;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) EncodeError!void {
        _ = self;
        _ = writer;
    }

};

pub const CompletionEvent = struct {
    drawable: xproto.Drawable,
    minor_event: u16,
    major_event: u8,
    shmseg: Seg,
    offset: u32,

    pub fn toBytes(self: @This()) EncodeError![32]u8 {
        var packet: [32]u8 = std.mem.zeroes([32]u8);
        var writer_impl: std.Io.Writer = .fixed(&packet);
        const writer = &writer_impl;
        try writer.writeByte(0);
        try writer.writeByte(0);
        try writer.writeInt(u16, 0, .little);
        try self.drawable.encode(writer);
        try writer.writeInt(u16, self.minor_event, .little);
        try writer.writeByte(self.major_event);
        try writer.splatByteAll(0, 1);
        try writer.writeInt(u32, @intFromEnum(self.shmseg), .little);
        try writer.writeInt(u32, self.offset, .little);
        return packet;
    }

    pub fn decode(reader: *std.Io.Reader) DecodeError!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const drawable = try xproto.Drawable.decode(reader);
        const minor_event = try reader.takeInt(u16, .little);
        const major_event = try reader.takeByte();
        _ = try reader.take(1);
        const shmseg = @as(Seg, @enumFromInt(try reader.takeInt(u32, .little)));
        const offset = try reader.takeInt(u32, .little);
        return .{
            .drawable = drawable,
            .minor_event = minor_event,
            .major_event = major_event,
            .shmseg = shmseg,
            .offset = offset,
        };
    }
};

pub const UnknownEvent = struct {
    code: u8,
    sequence: u16,
    raw: [32]u8,
};

pub const Event = union(enum) {
    unknown: UnknownEvent,
    Completion: CompletionEvent,
};

pub fn decodeEvent(reader: *std.Io.Reader) DecodeError!Event {
    const code = (try reader.peek(1))[0] & 0x7f;
    return switch (code) {
        0 => .{ .Completion = try CompletionEvent.decode(reader) },
        else => blk: {
            const packet = try reader.take(32);
            var raw: [32]u8 = undefined;
            @memcpy(raw[0..], packet);
            break :blk .{ .unknown = .{
                .code = packet[0] & 0x7f,
                .sequence = std.mem.readInt(u16, packet[2..4], .little),
                .raw = raw,
            } };
        },
    };
}

