// This file is generated by tools/gen_xproto.py.
// Source: /usr/share/xcb/xproto.xml

const std = @import("std");
const wire = @import("wire.zig");

pub const Atom = u32;
pub const Window = u32;

pub const CHAR2B = struct {
    byte1: u8,
    byte2: u8,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 1 + 1;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.byte1);
        try writer.writeByte(self.byte2);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const byte1 = try reader.takeByte();
        const byte2 = try reader.takeByte();
        return .{
            .byte1 = byte1,
            .byte2 = byte2,
        };
    }
};

pub const FORMAT = struct {
    depth: u8,
    bits_per_pixel: u8,
    scanline_pad: u8,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 1 + 1 + 1 + 5;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.depth);
        try writer.writeByte(self.bits_per_pixel);
        try writer.writeByte(self.scanline_pad);
        try writer.splatByteAll(0, 5);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const depth = try reader.takeByte();
        const bits_per_pixel = try reader.takeByte();
        const scanline_pad = try reader.takeByte();
        _ = try reader.take(5);
        return .{
            .depth = depth,
            .bits_per_pixel = bits_per_pixel,
            .scanline_pad = scanline_pad,
        };
    }
};

pub const VISUALTYPE = struct {
    visual_id: u32,
    class: u8,
    bits_per_rgb_value: u8,
    colormap_entries: u16,
    red_mask: u32,
    green_mask: u32,
    blue_mask: u32,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 1 + 1 + 2 + 4 + 4 + 4 + 4;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(u32, self.visual_id, .little);
        try writer.writeByte(self.class);
        try writer.writeByte(self.bits_per_rgb_value);
        try writer.writeInt(u16, self.colormap_entries, .little);
        try writer.writeInt(u32, self.red_mask, .little);
        try writer.writeInt(u32, self.green_mask, .little);
        try writer.writeInt(u32, self.blue_mask, .little);
        try writer.splatByteAll(0, 4);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const visual_id = try reader.takeInt(u32, .little);
        const class = try reader.takeByte();
        const bits_per_rgb_value = try reader.takeByte();
        const colormap_entries = try reader.takeInt(u16, .little);
        const red_mask = try reader.takeInt(u32, .little);
        const green_mask = try reader.takeInt(u32, .little);
        const blue_mask = try reader.takeInt(u32, .little);
        _ = try reader.take(4);
        return .{
            .visual_id = visual_id,
            .class = class,
            .bits_per_rgb_value = bits_per_rgb_value,
            .colormap_entries = colormap_entries,
            .red_mask = red_mask,
            .green_mask = green_mask,
            .blue_mask = blue_mask,
        };
    }
};

pub const DEPTH = struct {
    depth: u8,
    visuals: []VISUALTYPE,

    pub fn byteLen(self: @This()) usize {
        return 1 + 1 + 2 + 4 + wire.structListByteLen(self.visuals);
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.depth);
        try writer.splatByteAll(0, 1);
        try writer.writeInt(u16, @intCast(self.visuals.len), .little);
        try writer.splatByteAll(0, 4);
        for (self.visuals) |elem| try elem.encode(writer);
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const depth = try reader.takeByte();
        _ = try reader.take(1);
        const visuals_len = try reader.takeInt(u16, .little);
        _ = try reader.take(4);
        const visuals = try allocator.alloc(VISUALTYPE, @as(usize, visuals_len));
        errdefer allocator.free(visuals);
        var visuals_decoded: usize = 0;
        for (visuals) |*elem| {
            elem.* = try VISUALTYPE.decode(reader);
            visuals_decoded += 1;
        }
        return .{
            .depth = depth,
            .visuals = visuals,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.visuals);
    }
};

pub const SCREEN = struct {
    root: u32,
    default_colormap: u32,
    white_pixel: u32,
    black_pixel: u32,
    current_input_masks: u32,
    width_in_pixels: u16,
    height_in_pixels: u16,
    width_in_millimeters: u16,
    height_in_millimeters: u16,
    min_installed_maps: u16,
    max_installed_maps: u16,
    root_visual: u32,
    backing_stores: u8,
    save_unders: bool,
    root_depth: u8,
    allowed_depths: []DEPTH,

    pub fn byteLen(self: @This()) usize {
        return 4 + 4 + 4 + 4 + 4 + 2 + 2 + 2 + 2 + 2 + 2 + 4 + 1 + 1 + 1 + 1 + wire.structListByteLen(self.allowed_depths);
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(u32, self.root, .little);
        try writer.writeInt(u32, self.default_colormap, .little);
        try writer.writeInt(u32, self.white_pixel, .little);
        try writer.writeInt(u32, self.black_pixel, .little);
        try writer.writeInt(u32, self.current_input_masks, .little);
        try writer.writeInt(u16, self.width_in_pixels, .little);
        try writer.writeInt(u16, self.height_in_pixels, .little);
        try writer.writeInt(u16, self.width_in_millimeters, .little);
        try writer.writeInt(u16, self.height_in_millimeters, .little);
        try writer.writeInt(u16, self.min_installed_maps, .little);
        try writer.writeInt(u16, self.max_installed_maps, .little);
        try writer.writeInt(u32, self.root_visual, .little);
        try writer.writeByte(self.backing_stores);
        try writer.writeByte(@intFromBool(self.save_unders));
        try writer.writeByte(self.root_depth);
        try writer.writeByte(@intCast(self.allowed_depths.len));
        for (self.allowed_depths) |elem| try elem.encode(writer);
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const root = try reader.takeInt(u32, .little);
        const default_colormap = try reader.takeInt(u32, .little);
        const white_pixel = try reader.takeInt(u32, .little);
        const black_pixel = try reader.takeInt(u32, .little);
        const current_input_masks = try reader.takeInt(u32, .little);
        const width_in_pixels = try reader.takeInt(u16, .little);
        const height_in_pixels = try reader.takeInt(u16, .little);
        const width_in_millimeters = try reader.takeInt(u16, .little);
        const height_in_millimeters = try reader.takeInt(u16, .little);
        const min_installed_maps = try reader.takeInt(u16, .little);
        const max_installed_maps = try reader.takeInt(u16, .little);
        const root_visual = try reader.takeInt(u32, .little);
        const backing_stores = try reader.takeByte();
        const save_unders = (try reader.takeByte()) != 0;
        const root_depth = try reader.takeByte();
        const allowed_depths_len = try reader.takeByte();
        const allowed_depths = try allocator.alloc(DEPTH, @as(usize, allowed_depths_len));
        errdefer allocator.free(allowed_depths);
        var allowed_depths_decoded: usize = 0;
        errdefer for (allowed_depths[0..allowed_depths_decoded]) |*elem| elem.deinit(allocator);
        for (allowed_depths) |*elem| {
            elem.* = try DEPTH.decode(allocator, reader);
            allowed_depths_decoded += 1;
        }
        return .{
            .root = root,
            .default_colormap = default_colormap,
            .white_pixel = white_pixel,
            .black_pixel = black_pixel,
            .current_input_masks = current_input_masks,
            .width_in_pixels = width_in_pixels,
            .height_in_pixels = height_in_pixels,
            .width_in_millimeters = width_in_millimeters,
            .height_in_millimeters = height_in_millimeters,
            .min_installed_maps = min_installed_maps,
            .max_installed_maps = max_installed_maps,
            .root_visual = root_visual,
            .backing_stores = backing_stores,
            .save_unders = save_unders,
            .root_depth = root_depth,
            .allowed_depths = allowed_depths,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        for (self.allowed_depths) |*elem| elem.deinit(allocator);
        allocator.free(self.allowed_depths);
    }
};

pub const SetupRequest = struct {
    byte_order: u8,
    protocol_major_version: u16,
    protocol_minor_version: u16,
    authorization_protocol_name: []const u8,
    authorization_protocol_data: []const u8,

    pub fn byteLen(self: @This()) usize {
        return 1 + 1 + 2 + 2 + 2 + 2 + 2 + self.authorization_protocol_name.len + wire.pad4(self.authorization_protocol_name.len) + self.authorization_protocol_data.len + wire.pad4(self.authorization_protocol_data.len);
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.byte_order);
        try writer.splatByteAll(0, 1);
        try writer.writeInt(u16, self.protocol_major_version, .little);
        try writer.writeInt(u16, self.protocol_minor_version, .little);
        try writer.writeInt(u16, @intCast(self.authorization_protocol_name.len), .little);
        try writer.writeInt(u16, @intCast(self.authorization_protocol_data.len), .little);
        try writer.splatByteAll(0, 2);
        try writer.writeAll(self.authorization_protocol_name);
        try writer.splatByteAll(0, wire.pad4(self.authorization_protocol_name.len));
        try writer.writeAll(self.authorization_protocol_data);
        try writer.splatByteAll(0, wire.pad4(self.authorization_protocol_data.len));
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const byte_order = try reader.takeByte();
        _ = try reader.take(1);
        const protocol_major_version = try reader.takeInt(u16, .little);
        const protocol_minor_version = try reader.takeInt(u16, .little);
        const authorization_protocol_name_len = try reader.takeInt(u16, .little);
        const authorization_protocol_data_len = try reader.takeInt(u16, .little);
        _ = try reader.take(2);
        const authorization_protocol_name_wire = try reader.take(@as(usize, authorization_protocol_name_len));
        const authorization_protocol_name = try allocator.dupe(u8, authorization_protocol_name_wire);
        _ = try reader.take(wire.pad4(authorization_protocol_name.len));
        const authorization_protocol_data_wire = try reader.take(@as(usize, authorization_protocol_data_len));
        const authorization_protocol_data = try allocator.dupe(u8, authorization_protocol_data_wire);
        _ = try reader.take(wire.pad4(authorization_protocol_data.len));
        return .{
            .byte_order = byte_order,
            .protocol_major_version = protocol_major_version,
            .protocol_minor_version = protocol_minor_version,
            .authorization_protocol_name = authorization_protocol_name,
            .authorization_protocol_data = authorization_protocol_data,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.authorization_protocol_name);
        allocator.free(self.authorization_protocol_data);
    }
};

pub const SetupFailed = struct {
    status: u8,
    protocol_major_version: u16,
    protocol_minor_version: u16,
    length: u16,
    reason: []const u8,

    pub fn byteLen(self: @This()) usize {
        return 1 + 1 + 2 + 2 + 2 + self.reason.len;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.status);
        try writer.writeByte(@intCast(self.reason.len));
        try writer.writeInt(u16, self.protocol_major_version, .little);
        try writer.writeInt(u16, self.protocol_minor_version, .little);
        try writer.writeInt(u16, self.length, .little);
        try writer.writeAll(self.reason);
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const status = try reader.takeByte();
        const reason_len = try reader.takeByte();
        const protocol_major_version = try reader.takeInt(u16, .little);
        const protocol_minor_version = try reader.takeInt(u16, .little);
        const length = try reader.takeInt(u16, .little);
        const reason_wire = try reader.take(@as(usize, reason_len));
        const reason = try allocator.dupe(u8, reason_wire);
        return .{
            .status = status,
            .protocol_major_version = protocol_major_version,
            .protocol_minor_version = protocol_minor_version,
            .length = length,
            .reason = reason,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.reason);
    }
};

pub const SetupAuthenticate = struct {
    status: u8,
    length: u16,
    reason: []const u8,

    pub fn byteLen(self: @This()) usize {
        return 1 + 5 + 2 + self.reason.len;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.status);
        try writer.splatByteAll(0, 5);
        try writer.writeInt(u16, self.length, .little);
        std.debug.assert(self.reason.len == (@as(usize, self.length) * 4));
        try writer.writeAll(self.reason);
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const status = try reader.takeByte();
        _ = try reader.take(5);
        const length = try reader.takeInt(u16, .little);
        const reason_wire = try reader.take((@as(usize, length) * 4));
        const reason = try allocator.dupe(u8, reason_wire);
        return .{
            .status = status,
            .length = length,
            .reason = reason,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.reason);
    }
};

pub const Setup = struct {
    status: u8,
    protocol_major_version: u16,
    protocol_minor_version: u16,
    length: u16,
    release_number: u32,
    resource_id_base: u32,
    resource_id_mask: u32,
    motion_buffer_size: u32,
    maximum_request_length: u16,
    image_byte_order: u8,
    bitmap_format_bit_order: u8,
    bitmap_format_scanline_unit: u8,
    bitmap_format_scanline_pad: u8,
    min_keycode: u8,
    max_keycode: u8,
    vendor: []const u8,
    pixmap_formats: []FORMAT,
    roots: []SCREEN,

    pub fn byteLen(self: @This()) usize {
        return 1 + 1 + 2 + 2 + 2 + 4 + 4 + 4 + 4 + 2 + 2 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 4 + self.vendor.len + wire.pad4(self.vendor.len) + wire.structListByteLen(self.pixmap_formats) + wire.structListByteLen(self.roots);
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.status);
        try writer.splatByteAll(0, 1);
        try writer.writeInt(u16, self.protocol_major_version, .little);
        try writer.writeInt(u16, self.protocol_minor_version, .little);
        try writer.writeInt(u16, self.length, .little);
        try writer.writeInt(u32, self.release_number, .little);
        try writer.writeInt(u32, self.resource_id_base, .little);
        try writer.writeInt(u32, self.resource_id_mask, .little);
        try writer.writeInt(u32, self.motion_buffer_size, .little);
        try writer.writeInt(u16, @intCast(self.vendor.len), .little);
        try writer.writeInt(u16, self.maximum_request_length, .little);
        try writer.writeByte(@intCast(self.roots.len));
        try writer.writeByte(@intCast(self.pixmap_formats.len));
        try writer.writeByte(self.image_byte_order);
        try writer.writeByte(self.bitmap_format_bit_order);
        try writer.writeByte(self.bitmap_format_scanline_unit);
        try writer.writeByte(self.bitmap_format_scanline_pad);
        try writer.writeByte(self.min_keycode);
        try writer.writeByte(self.max_keycode);
        try writer.splatByteAll(0, 4);
        try writer.writeAll(self.vendor);
        try writer.splatByteAll(0, wire.pad4(self.vendor.len));
        for (self.pixmap_formats) |elem| try elem.encode(writer);
        for (self.roots) |elem| try elem.encode(writer);
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const status = try reader.takeByte();
        _ = try reader.take(1);
        const protocol_major_version = try reader.takeInt(u16, .little);
        const protocol_minor_version = try reader.takeInt(u16, .little);
        const length = try reader.takeInt(u16, .little);
        const release_number = try reader.takeInt(u32, .little);
        const resource_id_base = try reader.takeInt(u32, .little);
        const resource_id_mask = try reader.takeInt(u32, .little);
        const motion_buffer_size = try reader.takeInt(u32, .little);
        const vendor_len = try reader.takeInt(u16, .little);
        const maximum_request_length = try reader.takeInt(u16, .little);
        const roots_len = try reader.takeByte();
        const pixmap_formats_len = try reader.takeByte();
        const image_byte_order = try reader.takeByte();
        const bitmap_format_bit_order = try reader.takeByte();
        const bitmap_format_scanline_unit = try reader.takeByte();
        const bitmap_format_scanline_pad = try reader.takeByte();
        const min_keycode = try reader.takeByte();
        const max_keycode = try reader.takeByte();
        _ = try reader.take(4);
        const vendor_wire = try reader.take(@as(usize, vendor_len));
        const vendor = try allocator.dupe(u8, vendor_wire);
        _ = try reader.take(wire.pad4(vendor.len));
        const pixmap_formats = try allocator.alloc(FORMAT, @as(usize, pixmap_formats_len));
        errdefer allocator.free(pixmap_formats);
        var pixmap_formats_decoded: usize = 0;
        for (pixmap_formats) |*elem| {
            elem.* = try FORMAT.decode(reader);
            pixmap_formats_decoded += 1;
        }
        const roots = try allocator.alloc(SCREEN, @as(usize, roots_len));
        errdefer allocator.free(roots);
        var roots_decoded: usize = 0;
        errdefer for (roots[0..roots_decoded]) |*elem| elem.deinit(allocator);
        for (roots) |*elem| {
            elem.* = try SCREEN.decode(allocator, reader);
            roots_decoded += 1;
        }
        return .{
            .status = status,
            .protocol_major_version = protocol_major_version,
            .protocol_minor_version = protocol_minor_version,
            .length = length,
            .release_number = release_number,
            .resource_id_base = resource_id_base,
            .resource_id_mask = resource_id_mask,
            .motion_buffer_size = motion_buffer_size,
            .maximum_request_length = maximum_request_length,
            .image_byte_order = image_byte_order,
            .bitmap_format_bit_order = bitmap_format_bit_order,
            .bitmap_format_scanline_unit = bitmap_format_scanline_unit,
            .bitmap_format_scanline_pad = bitmap_format_scanline_pad,
            .min_keycode = min_keycode,
            .max_keycode = max_keycode,
            .vendor = vendor,
            .pixmap_formats = pixmap_formats,
            .roots = roots,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.vendor);
        allocator.free(self.pixmap_formats);
        for (self.roots) |*elem| elem.deinit(allocator);
        allocator.free(self.roots);
    }
};

pub const FONTPROP = struct {
    name: u32,
    value: u32,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 4;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(u32, self.name, .little);
        try writer.writeInt(u32, self.value, .little);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const name = try reader.takeInt(u32, .little);
        const value = try reader.takeInt(u32, .little);
        return .{
            .name = name,
            .value = value,
        };
    }
};

pub const STR = struct {
    name: []const u8,

    pub fn byteLen(self: @This()) usize {
        return 1 + self.name.len;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(@intCast(self.name.len));
        try writer.writeAll(self.name);
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const name_len = try reader.takeByte();
        const name_wire = try reader.take(@as(usize, name_len));
        const name = try allocator.dupe(u8, name_wire);
        return .{
            .name = name,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.name);
    }
};

pub const COLORITEM = struct {
    pixel: u32,
    red: u16,
    green: u16,
    blue: u16,
    flags: u8,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 2 + 2 + 2 + 1 + 1;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(u32, self.pixel, .little);
        try writer.writeInt(u16, self.red, .little);
        try writer.writeInt(u16, self.green, .little);
        try writer.writeInt(u16, self.blue, .little);
        try writer.writeByte(self.flags);
        try writer.splatByteAll(0, 1);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const pixel = try reader.takeInt(u32, .little);
        const red = try reader.takeInt(u16, .little);
        const green = try reader.takeInt(u16, .little);
        const blue = try reader.takeInt(u16, .little);
        const flags = try reader.takeByte();
        _ = try reader.take(1);
        return .{
            .pixel = pixel,
            .red = red,
            .green = green,
            .blue = blue,
            .flags = flags,
        };
    }
};

pub const RGB = struct {
    red: u16,
    green: u16,
    blue: u16,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 2 + 2 + 2 + 2;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(u16, self.red, .little);
        try writer.writeInt(u16, self.green, .little);
        try writer.writeInt(u16, self.blue, .little);
        try writer.splatByteAll(0, 2);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const red = try reader.takeInt(u16, .little);
        const green = try reader.takeInt(u16, .little);
        const blue = try reader.takeInt(u16, .little);
        _ = try reader.take(2);
        return .{
            .red = red,
            .green = green,
            .blue = blue,
        };
    }
};

pub const HOST = struct {
    family: u8,
    address: []const u8,

    pub fn byteLen(self: @This()) usize {
        return 1 + 1 + 2 + self.address.len + wire.pad4(self.address.len);
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.family);
        try writer.splatByteAll(0, 1);
        try writer.writeInt(u16, @intCast(self.address.len), .little);
        try writer.writeAll(self.address);
        try writer.splatByteAll(0, wire.pad4(self.address.len));
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const family = try reader.takeByte();
        _ = try reader.take(1);
        const address_len = try reader.takeInt(u16, .little);
        const address_wire = try reader.take(@as(usize, address_len));
        const address = try allocator.dupe(u8, address_wire);
        _ = try reader.take(wire.pad4(address.len));
        return .{
            .family = family,
            .address = address,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.address);
    }
};

pub const GetPropertyType = enum(u32) {
    Any = 0,
    _,
};

pub const InternAtomRequest = struct {
    pub const opcode: u8 = 16;
    pub const Reply = InternAtomReply;

    only_if_exists: bool,
    name: []const u8,

    pub fn byteLen(self: @This()) usize {
        return 4 + 2 + 2 + self.name.len;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        const len = self.byteLen();
        const pad = wire.pad4(len);
        try writer.writeByte(opcode);
        try writer.writeByte(@intFromBool(self.only_if_exists));
        try writer.writeInt(u16, @intCast((len + pad) / 4), .little);
        try writer.writeInt(u16, @intCast(self.name.len), .little);
        try writer.splatByteAll(0, 2);
        try writer.writeAll(self.name);
        try writer.splatByteAll(0, pad);
    }
};

pub const InternAtomReply = struct {
    atom: u32,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        if (try reader.takeByte() != 1) return error.UnexpectedReplyType;
        _ = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        _ = try reader.takeInt(u32, .little);
        const atom = try reader.takeInt(u32, .little);
        _ = try reader.take(20);
        return .{
            .atom = atom,
        };
    }
};

pub const GetPropertyRequest = struct {
    pub const opcode: u8 = 20;
    pub const Reply = GetPropertyReply;

    delete_value: bool,
    window: u32,
    property: u32,
    type_atom: u32,
    long_offset: u32,
    long_length: u32,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 4 + 4 + 4 + 4 + 4;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        const len = self.byteLen();
        const pad = wire.pad4(len);
        try writer.writeByte(opcode);
        try writer.writeByte(@intFromBool(self.delete_value));
        try writer.writeInt(u16, @intCast((len + pad) / 4), .little);
        try writer.writeInt(u32, self.window, .little);
        try writer.writeInt(u32, self.property, .little);
        try writer.writeInt(u32, self.type_atom, .little);
        try writer.writeInt(u32, self.long_offset, .little);
        try writer.writeInt(u32, self.long_length, .little);
        try writer.splatByteAll(0, pad);
    }
};

pub const GetPropertyReply = struct {
    format: u8,
    type_atom: u32,
    bytes_after: u32,
    value_len: u32,
    value: []const u8,

    pub fn decode(reader: *std.Io.Reader, scratch: []u8) wire.Error!@This() {
        if (try reader.takeByte() != 1) return error.UnexpectedReplyType;
        const format = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        const reply_len = @as(usize, try reader.takeInt(u32, .little)) * 4;
        const type_atom = try reader.takeInt(Atom, .little);
        const bytes_after = try reader.takeInt(u32, .little);
        const value_len = try reader.takeInt(u32, .little);
        _ = try reader.take(12);
        const value_bytes = try wire.valueByteLen(format, value_len);
        if (reply_len < value_bytes) return error.MalformedPacket;
        if (scratch.len < value_bytes) return error.BufferTooSmall;
        @memcpy(scratch[0..value_bytes], try reader.take(value_bytes));
        _ = try reader.take(reply_len - value_bytes);
        return .{
            .format = format,
            .type_atom = type_atom,
            .bytes_after = bytes_after,
            .value_len = value_len,
            .value = scratch[0..value_bytes],
        };
    }
};

pub const GetInputFocusRequest = struct {
    pub const opcode: u8 = 43;
    pub const Reply = GetInputFocusReply;


    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 0;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        const len = self.byteLen();
        const pad = wire.pad4(len);
        try writer.writeByte(opcode);
        try writer.writeByte(0);
        try writer.writeInt(u16, @intCast((len + pad) / 4), .little);
        try writer.splatByteAll(0, pad);
    }
};

pub const GetInputFocusReply = struct {
    revert_to: u8,
    focus: u32,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        if (try reader.takeByte() != 1) return error.UnexpectedReplyType;
        const revert_to = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        _ = try reader.takeInt(u32, .little);
        const focus = try reader.takeInt(u32, .little);
        _ = try reader.take(20);
        return .{
            .revert_to = revert_to,
            .focus = focus,
        };
    }
};

