// This file is generated by tools/gen_xproto.py.
// Source: /usr/share/xcb/xproto.xml

const std = @import("std");
const wire = @import("wire.zig");

pub const Atom = enum(u32) { _ };
pub const Colormap = enum(u32) { _ };
pub const Cursor = enum(u32) { _ };
pub const Font = enum(u32) { _ };
pub const Gcontext = enum(u32) { _ };
pub const Pixmap = enum(u32) { _ };
pub const Window = enum(u32) { _ };
pub const Drawable = enum(u32) { _ };
pub const Fontable = enum(u32) { _ };

pub const CHAR2B = struct {
    byte1: u8,
    byte2: u8,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 1 + 1;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.byte1);
        try writer.writeByte(self.byte2);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const byte1 = try reader.takeByte();
        const byte2 = try reader.takeByte();
        return .{
            .byte1 = byte1,
            .byte2 = byte2,
        };
    }
};

pub const POINT = struct {
    x: i16,
    y: i16,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 2 + 2;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(i16, self.x, .little);
        try writer.writeInt(i16, self.y, .little);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const x = try reader.takeInt(i16, .little);
        const y = try reader.takeInt(i16, .little);
        return .{
            .x = x,
            .y = y,
        };
    }
};

pub const RECTANGLE = struct {
    x: i16,
    y: i16,
    width: u16,
    height: u16,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 2 + 2 + 2 + 2;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(i16, self.x, .little);
        try writer.writeInt(i16, self.y, .little);
        try writer.writeInt(u16, self.width, .little);
        try writer.writeInt(u16, self.height, .little);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const x = try reader.takeInt(i16, .little);
        const y = try reader.takeInt(i16, .little);
        const width = try reader.takeInt(u16, .little);
        const height = try reader.takeInt(u16, .little);
        return .{
            .x = x,
            .y = y,
            .width = width,
            .height = height,
        };
    }
};

pub const ARC = struct {
    x: i16,
    y: i16,
    width: u16,
    height: u16,
    angle1: i16,
    angle2: i16,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 2 + 2 + 2 + 2 + 2 + 2;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(i16, self.x, .little);
        try writer.writeInt(i16, self.y, .little);
        try writer.writeInt(u16, self.width, .little);
        try writer.writeInt(u16, self.height, .little);
        try writer.writeInt(i16, self.angle1, .little);
        try writer.writeInt(i16, self.angle2, .little);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const x = try reader.takeInt(i16, .little);
        const y = try reader.takeInt(i16, .little);
        const width = try reader.takeInt(u16, .little);
        const height = try reader.takeInt(u16, .little);
        const angle1 = try reader.takeInt(i16, .little);
        const angle2 = try reader.takeInt(i16, .little);
        return .{
            .x = x,
            .y = y,
            .width = width,
            .height = height,
            .angle1 = angle1,
            .angle2 = angle2,
        };
    }
};

pub const FORMAT = struct {
    depth: u8,
    bits_per_pixel: u8,
    scanline_pad: u8,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 1 + 1 + 1 + 5;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.depth);
        try writer.writeByte(self.bits_per_pixel);
        try writer.writeByte(self.scanline_pad);
        try writer.splatByteAll(0, 5);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const depth = try reader.takeByte();
        const bits_per_pixel = try reader.takeByte();
        const scanline_pad = try reader.takeByte();
        _ = try reader.take(5);
        return .{
            .depth = depth,
            .bits_per_pixel = bits_per_pixel,
            .scanline_pad = scanline_pad,
        };
    }
};

pub const VISUALTYPE = struct {
    visual_id: u32,
    class: u8,
    bits_per_rgb_value: u8,
    colormap_entries: u16,
    red_mask: u32,
    green_mask: u32,
    blue_mask: u32,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 1 + 1 + 2 + 4 + 4 + 4 + 4;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(u32, self.visual_id, .little);
        try writer.writeByte(self.class);
        try writer.writeByte(self.bits_per_rgb_value);
        try writer.writeInt(u16, self.colormap_entries, .little);
        try writer.writeInt(u32, self.red_mask, .little);
        try writer.writeInt(u32, self.green_mask, .little);
        try writer.writeInt(u32, self.blue_mask, .little);
        try writer.splatByteAll(0, 4);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const visual_id = try reader.takeInt(u32, .little);
        const class = try reader.takeByte();
        const bits_per_rgb_value = try reader.takeByte();
        const colormap_entries = try reader.takeInt(u16, .little);
        const red_mask = try reader.takeInt(u32, .little);
        const green_mask = try reader.takeInt(u32, .little);
        const blue_mask = try reader.takeInt(u32, .little);
        _ = try reader.take(4);
        return .{
            .visual_id = visual_id,
            .class = class,
            .bits_per_rgb_value = bits_per_rgb_value,
            .colormap_entries = colormap_entries,
            .red_mask = red_mask,
            .green_mask = green_mask,
            .blue_mask = blue_mask,
        };
    }
};

pub const DEPTH = struct {
    depth: u8,
    visuals: []VISUALTYPE,

    pub fn byteLen(self: @This()) usize {
        return 1 + 1 + 2 + 4 + wire.structListByteLen(self.visuals);
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.depth);
        try writer.splatByteAll(0, 1);
        try writer.writeInt(u16, @intCast(self.visuals.len), .little);
        try writer.splatByteAll(0, 4);
        for (self.visuals) |elem| try elem.encode(writer);
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const depth = try reader.takeByte();
        _ = try reader.take(1);
        const visuals_len = try reader.takeInt(u16, .little);
        _ = try reader.take(4);
        const visuals = try allocator.alloc(VISUALTYPE, @as(usize, visuals_len));
        errdefer allocator.free(visuals);
        var visuals_decoded: usize = 0;
        for (visuals) |*elem| {
            elem.* = try VISUALTYPE.decode(reader);
            visuals_decoded += 1;
        }
        return .{
            .depth = depth,
            .visuals = visuals,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.visuals);
    }
};

pub const SCREEN = struct {
    root: Window,
    default_colormap: Colormap,
    white_pixel: u32,
    black_pixel: u32,
    current_input_masks: u32,
    width_in_pixels: u16,
    height_in_pixels: u16,
    width_in_millimeters: u16,
    height_in_millimeters: u16,
    min_installed_maps: u16,
    max_installed_maps: u16,
    root_visual: u32,
    backing_stores: u8,
    save_unders: bool,
    root_depth: u8,
    allowed_depths: []DEPTH,

    pub fn byteLen(self: @This()) usize {
        return 4 + 4 + 4 + 4 + 4 + 2 + 2 + 2 + 2 + 2 + 2 + 4 + 1 + 1 + 1 + 1 + wire.structListByteLen(self.allowed_depths);
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(u32, @intFromEnum(self.root), .little);
        try writer.writeInt(u32, @intFromEnum(self.default_colormap), .little);
        try writer.writeInt(u32, self.white_pixel, .little);
        try writer.writeInt(u32, self.black_pixel, .little);
        try writer.writeInt(u32, self.current_input_masks, .little);
        try writer.writeInt(u16, self.width_in_pixels, .little);
        try writer.writeInt(u16, self.height_in_pixels, .little);
        try writer.writeInt(u16, self.width_in_millimeters, .little);
        try writer.writeInt(u16, self.height_in_millimeters, .little);
        try writer.writeInt(u16, self.min_installed_maps, .little);
        try writer.writeInt(u16, self.max_installed_maps, .little);
        try writer.writeInt(u32, self.root_visual, .little);
        try writer.writeByte(self.backing_stores);
        try writer.writeByte(@intFromBool(self.save_unders));
        try writer.writeByte(self.root_depth);
        try writer.writeByte(@intCast(self.allowed_depths.len));
        for (self.allowed_depths) |elem| try elem.encode(writer);
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const root = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const default_colormap = @as(Colormap, @enumFromInt(try reader.takeInt(u32, .little)));
        const white_pixel = try reader.takeInt(u32, .little);
        const black_pixel = try reader.takeInt(u32, .little);
        const current_input_masks = try reader.takeInt(u32, .little);
        const width_in_pixels = try reader.takeInt(u16, .little);
        const height_in_pixels = try reader.takeInt(u16, .little);
        const width_in_millimeters = try reader.takeInt(u16, .little);
        const height_in_millimeters = try reader.takeInt(u16, .little);
        const min_installed_maps = try reader.takeInt(u16, .little);
        const max_installed_maps = try reader.takeInt(u16, .little);
        const root_visual = try reader.takeInt(u32, .little);
        const backing_stores = try reader.takeByte();
        const save_unders = (try reader.takeByte()) != 0;
        const root_depth = try reader.takeByte();
        const allowed_depths_len = try reader.takeByte();
        const allowed_depths = try allocator.alloc(DEPTH, @as(usize, allowed_depths_len));
        errdefer allocator.free(allowed_depths);
        var allowed_depths_decoded: usize = 0;
        errdefer for (allowed_depths[0..allowed_depths_decoded]) |*elem| elem.deinit(allocator);
        for (allowed_depths) |*elem| {
            elem.* = try DEPTH.decode(allocator, reader);
            allowed_depths_decoded += 1;
        }
        return .{
            .root = root,
            .default_colormap = default_colormap,
            .white_pixel = white_pixel,
            .black_pixel = black_pixel,
            .current_input_masks = current_input_masks,
            .width_in_pixels = width_in_pixels,
            .height_in_pixels = height_in_pixels,
            .width_in_millimeters = width_in_millimeters,
            .height_in_millimeters = height_in_millimeters,
            .min_installed_maps = min_installed_maps,
            .max_installed_maps = max_installed_maps,
            .root_visual = root_visual,
            .backing_stores = backing_stores,
            .save_unders = save_unders,
            .root_depth = root_depth,
            .allowed_depths = allowed_depths,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        for (self.allowed_depths) |*elem| elem.deinit(allocator);
        allocator.free(self.allowed_depths);
    }
};

pub const SetupRequest = struct {
    byte_order: u8,
    protocol_major_version: u16,
    protocol_minor_version: u16,
    authorization_protocol_name: []const u8,
    authorization_protocol_data: []const u8,

    pub fn byteLen(self: @This()) usize {
        return 1 + 1 + 2 + 2 + 2 + 2 + 2 + self.authorization_protocol_name.len + wire.pad4(self.authorization_protocol_name.len) + self.authorization_protocol_data.len + wire.pad4(self.authorization_protocol_data.len);
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.byte_order);
        try writer.splatByteAll(0, 1);
        try writer.writeInt(u16, self.protocol_major_version, .little);
        try writer.writeInt(u16, self.protocol_minor_version, .little);
        try writer.writeInt(u16, @intCast(self.authorization_protocol_name.len), .little);
        try writer.writeInt(u16, @intCast(self.authorization_protocol_data.len), .little);
        try writer.splatByteAll(0, 2);
        try writer.writeAll(self.authorization_protocol_name);
        try writer.splatByteAll(0, wire.pad4(self.authorization_protocol_name.len));
        try writer.writeAll(self.authorization_protocol_data);
        try writer.splatByteAll(0, wire.pad4(self.authorization_protocol_data.len));
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const byte_order = try reader.takeByte();
        _ = try reader.take(1);
        const protocol_major_version = try reader.takeInt(u16, .little);
        const protocol_minor_version = try reader.takeInt(u16, .little);
        const authorization_protocol_name_len = try reader.takeInt(u16, .little);
        const authorization_protocol_data_len = try reader.takeInt(u16, .little);
        _ = try reader.take(2);
        const authorization_protocol_name_wire = try reader.take(@as(usize, authorization_protocol_name_len));
        const authorization_protocol_name = try allocator.dupe(u8, authorization_protocol_name_wire);
        _ = try reader.take(wire.pad4(authorization_protocol_name.len));
        const authorization_protocol_data_wire = try reader.take(@as(usize, authorization_protocol_data_len));
        const authorization_protocol_data = try allocator.dupe(u8, authorization_protocol_data_wire);
        _ = try reader.take(wire.pad4(authorization_protocol_data.len));
        return .{
            .byte_order = byte_order,
            .protocol_major_version = protocol_major_version,
            .protocol_minor_version = protocol_minor_version,
            .authorization_protocol_name = authorization_protocol_name,
            .authorization_protocol_data = authorization_protocol_data,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.authorization_protocol_name);
        allocator.free(self.authorization_protocol_data);
    }
};

pub const SetupFailed = struct {
    status: u8,
    protocol_major_version: u16,
    protocol_minor_version: u16,
    length: u16,
    reason: []const u8,

    pub fn byteLen(self: @This()) usize {
        return 1 + 1 + 2 + 2 + 2 + self.reason.len;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.status);
        try writer.writeByte(@intCast(self.reason.len));
        try writer.writeInt(u16, self.protocol_major_version, .little);
        try writer.writeInt(u16, self.protocol_minor_version, .little);
        try writer.writeInt(u16, self.length, .little);
        try writer.writeAll(self.reason);
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const status = try reader.takeByte();
        const reason_len = try reader.takeByte();
        const protocol_major_version = try reader.takeInt(u16, .little);
        const protocol_minor_version = try reader.takeInt(u16, .little);
        const length = try reader.takeInt(u16, .little);
        const reason_wire = try reader.take(@as(usize, reason_len));
        const reason = try allocator.dupe(u8, reason_wire);
        return .{
            .status = status,
            .protocol_major_version = protocol_major_version,
            .protocol_minor_version = protocol_minor_version,
            .length = length,
            .reason = reason,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.reason);
    }
};

pub const SetupAuthenticate = struct {
    status: u8,
    length: u16,
    reason: []const u8,

    pub fn byteLen(self: @This()) usize {
        return 1 + 5 + 2 + self.reason.len;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.status);
        try writer.splatByteAll(0, 5);
        try writer.writeInt(u16, self.length, .little);
        std.debug.assert(self.reason.len == (@as(usize, self.length) * 4));
        try writer.writeAll(self.reason);
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const status = try reader.takeByte();
        _ = try reader.take(5);
        const length = try reader.takeInt(u16, .little);
        const reason_wire = try reader.take((@as(usize, length) * 4));
        const reason = try allocator.dupe(u8, reason_wire);
        return .{
            .status = status,
            .length = length,
            .reason = reason,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.reason);
    }
};

pub const Setup = struct {
    status: u8,
    protocol_major_version: u16,
    protocol_minor_version: u16,
    length: u16,
    release_number: u32,
    resource_id_base: u32,
    resource_id_mask: u32,
    motion_buffer_size: u32,
    maximum_request_length: u16,
    image_byte_order: u8,
    bitmap_format_bit_order: u8,
    bitmap_format_scanline_unit: u8,
    bitmap_format_scanline_pad: u8,
    min_keycode: u8,
    max_keycode: u8,
    vendor: []const u8,
    pixmap_formats: []FORMAT,
    roots: []SCREEN,

    pub fn byteLen(self: @This()) usize {
        return 1 + 1 + 2 + 2 + 2 + 4 + 4 + 4 + 4 + 2 + 2 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 4 + self.vendor.len + wire.pad4(self.vendor.len) + wire.structListByteLen(self.pixmap_formats) + wire.structListByteLen(self.roots);
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.status);
        try writer.splatByteAll(0, 1);
        try writer.writeInt(u16, self.protocol_major_version, .little);
        try writer.writeInt(u16, self.protocol_minor_version, .little);
        try writer.writeInt(u16, self.length, .little);
        try writer.writeInt(u32, self.release_number, .little);
        try writer.writeInt(u32, self.resource_id_base, .little);
        try writer.writeInt(u32, self.resource_id_mask, .little);
        try writer.writeInt(u32, self.motion_buffer_size, .little);
        try writer.writeInt(u16, @intCast(self.vendor.len), .little);
        try writer.writeInt(u16, self.maximum_request_length, .little);
        try writer.writeByte(@intCast(self.roots.len));
        try writer.writeByte(@intCast(self.pixmap_formats.len));
        try writer.writeByte(self.image_byte_order);
        try writer.writeByte(self.bitmap_format_bit_order);
        try writer.writeByte(self.bitmap_format_scanline_unit);
        try writer.writeByte(self.bitmap_format_scanline_pad);
        try writer.writeByte(self.min_keycode);
        try writer.writeByte(self.max_keycode);
        try writer.splatByteAll(0, 4);
        try writer.writeAll(self.vendor);
        try writer.splatByteAll(0, wire.pad4(self.vendor.len));
        for (self.pixmap_formats) |elem| try elem.encode(writer);
        for (self.roots) |elem| try elem.encode(writer);
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const status = try reader.takeByte();
        _ = try reader.take(1);
        const protocol_major_version = try reader.takeInt(u16, .little);
        const protocol_minor_version = try reader.takeInt(u16, .little);
        const length = try reader.takeInt(u16, .little);
        const release_number = try reader.takeInt(u32, .little);
        const resource_id_base = try reader.takeInt(u32, .little);
        const resource_id_mask = try reader.takeInt(u32, .little);
        const motion_buffer_size = try reader.takeInt(u32, .little);
        const vendor_len = try reader.takeInt(u16, .little);
        const maximum_request_length = try reader.takeInt(u16, .little);
        const roots_len = try reader.takeByte();
        const pixmap_formats_len = try reader.takeByte();
        const image_byte_order = try reader.takeByte();
        const bitmap_format_bit_order = try reader.takeByte();
        const bitmap_format_scanline_unit = try reader.takeByte();
        const bitmap_format_scanline_pad = try reader.takeByte();
        const min_keycode = try reader.takeByte();
        const max_keycode = try reader.takeByte();
        _ = try reader.take(4);
        const vendor_wire = try reader.take(@as(usize, vendor_len));
        const vendor = try allocator.dupe(u8, vendor_wire);
        _ = try reader.take(wire.pad4(vendor.len));
        const pixmap_formats = try allocator.alloc(FORMAT, @as(usize, pixmap_formats_len));
        errdefer allocator.free(pixmap_formats);
        var pixmap_formats_decoded: usize = 0;
        for (pixmap_formats) |*elem| {
            elem.* = try FORMAT.decode(reader);
            pixmap_formats_decoded += 1;
        }
        const roots = try allocator.alloc(SCREEN, @as(usize, roots_len));
        errdefer allocator.free(roots);
        var roots_decoded: usize = 0;
        errdefer for (roots[0..roots_decoded]) |*elem| elem.deinit(allocator);
        for (roots) |*elem| {
            elem.* = try SCREEN.decode(allocator, reader);
            roots_decoded += 1;
        }
        return .{
            .status = status,
            .protocol_major_version = protocol_major_version,
            .protocol_minor_version = protocol_minor_version,
            .length = length,
            .release_number = release_number,
            .resource_id_base = resource_id_base,
            .resource_id_mask = resource_id_mask,
            .motion_buffer_size = motion_buffer_size,
            .maximum_request_length = maximum_request_length,
            .image_byte_order = image_byte_order,
            .bitmap_format_bit_order = bitmap_format_bit_order,
            .bitmap_format_scanline_unit = bitmap_format_scanline_unit,
            .bitmap_format_scanline_pad = bitmap_format_scanline_pad,
            .min_keycode = min_keycode,
            .max_keycode = max_keycode,
            .vendor = vendor,
            .pixmap_formats = pixmap_formats,
            .roots = roots,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.vendor);
        allocator.free(self.pixmap_formats);
        for (self.roots) |*elem| elem.deinit(allocator);
        allocator.free(self.roots);
    }
};

pub const TIMECOORD = struct {
    time: u32,
    x: i16,
    y: i16,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 2 + 2;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(u32, self.time, .little);
        try writer.writeInt(i16, self.x, .little);
        try writer.writeInt(i16, self.y, .little);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const time = try reader.takeInt(u32, .little);
        const x = try reader.takeInt(i16, .little);
        const y = try reader.takeInt(i16, .little);
        return .{
            .time = time,
            .x = x,
            .y = y,
        };
    }
};

pub const FONTPROP = struct {
    name: Atom,
    value: u32,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 4;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(u32, @intFromEnum(self.name), .little);
        try writer.writeInt(u32, self.value, .little);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const name = @as(Atom, @enumFromInt(try reader.takeInt(u32, .little)));
        const value = try reader.takeInt(u32, .little);
        return .{
            .name = name,
            .value = value,
        };
    }
};

pub const CHARINFO = struct {
    left_side_bearing: i16,
    right_side_bearing: i16,
    character_width: i16,
    ascent: i16,
    descent: i16,
    attributes: u16,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 2 + 2 + 2 + 2 + 2 + 2;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(i16, self.left_side_bearing, .little);
        try writer.writeInt(i16, self.right_side_bearing, .little);
        try writer.writeInt(i16, self.character_width, .little);
        try writer.writeInt(i16, self.ascent, .little);
        try writer.writeInt(i16, self.descent, .little);
        try writer.writeInt(u16, self.attributes, .little);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const left_side_bearing = try reader.takeInt(i16, .little);
        const right_side_bearing = try reader.takeInt(i16, .little);
        const character_width = try reader.takeInt(i16, .little);
        const ascent = try reader.takeInt(i16, .little);
        const descent = try reader.takeInt(i16, .little);
        const attributes = try reader.takeInt(u16, .little);
        return .{
            .left_side_bearing = left_side_bearing,
            .right_side_bearing = right_side_bearing,
            .character_width = character_width,
            .ascent = ascent,
            .descent = descent,
            .attributes = attributes,
        };
    }
};

pub const STR = struct {
    name: []const u8,

    pub fn byteLen(self: @This()) usize {
        return 1 + self.name.len;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(@intCast(self.name.len));
        try writer.writeAll(self.name);
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const name_len = try reader.takeByte();
        const name_wire = try reader.take(@as(usize, name_len));
        const name = try allocator.dupe(u8, name_wire);
        return .{
            .name = name,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.name);
    }
};

pub const SEGMENT = struct {
    x1: i16,
    y1: i16,
    x2: i16,
    y2: i16,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 2 + 2 + 2 + 2;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(i16, self.x1, .little);
        try writer.writeInt(i16, self.y1, .little);
        try writer.writeInt(i16, self.x2, .little);
        try writer.writeInt(i16, self.y2, .little);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const x1 = try reader.takeInt(i16, .little);
        const y1 = try reader.takeInt(i16, .little);
        const x2 = try reader.takeInt(i16, .little);
        const y2 = try reader.takeInt(i16, .little);
        return .{
            .x1 = x1,
            .y1 = y1,
            .x2 = x2,
            .y2 = y2,
        };
    }
};

pub const COLORITEM = struct {
    pixel: u32,
    red: u16,
    green: u16,
    blue: u16,
    flags: u8,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 2 + 2 + 2 + 1 + 1;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(u32, self.pixel, .little);
        try writer.writeInt(u16, self.red, .little);
        try writer.writeInt(u16, self.green, .little);
        try writer.writeInt(u16, self.blue, .little);
        try writer.writeByte(self.flags);
        try writer.splatByteAll(0, 1);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const pixel = try reader.takeInt(u32, .little);
        const red = try reader.takeInt(u16, .little);
        const green = try reader.takeInt(u16, .little);
        const blue = try reader.takeInt(u16, .little);
        const flags = try reader.takeByte();
        _ = try reader.take(1);
        return .{
            .pixel = pixel,
            .red = red,
            .green = green,
            .blue = blue,
            .flags = flags,
        };
    }
};

pub const RGB = struct {
    red: u16,
    green: u16,
    blue: u16,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 2 + 2 + 2 + 2;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(u16, self.red, .little);
        try writer.writeInt(u16, self.green, .little);
        try writer.writeInt(u16, self.blue, .little);
        try writer.splatByteAll(0, 2);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const red = try reader.takeInt(u16, .little);
        const green = try reader.takeInt(u16, .little);
        const blue = try reader.takeInt(u16, .little);
        _ = try reader.take(2);
        return .{
            .red = red,
            .green = green,
            .blue = blue,
        };
    }
};

pub const HOST = struct {
    family: u8,
    address: []const u8,

    pub fn byteLen(self: @This()) usize {
        return 1 + 1 + 2 + self.address.len + wire.pad4(self.address.len);
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.family);
        try writer.splatByteAll(0, 1);
        try writer.writeInt(u16, @intCast(self.address.len), .little);
        try writer.writeAll(self.address);
        try writer.splatByteAll(0, wire.pad4(self.address.len));
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const family = try reader.takeByte();
        _ = try reader.take(1);
        const address_len = try reader.takeInt(u16, .little);
        const address_wire = try reader.take(@as(usize, address_len));
        const address = try allocator.dupe(u8, address_wire);
        _ = try reader.take(wire.pad4(address.len));
        return .{
            .family = family,
            .address = address,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.address);
    }
};

pub const GetPropertyType = enum(u32) {
    Any = 0,
    _,
};

pub const WindowClass = enum(u32) {
    CopyFromParent = 0,
    InputOutput = 1,
    InputOnly = 2,
    _,
};

pub const CW = enum(u32) {
    BackPixmap = 1,
    BackPixel = 2,
    BorderPixmap = 4,
    BorderPixel = 8,
    BitGravity = 16,
    WinGravity = 32,
    BackingStore = 64,
    BackingPlanes = 128,
    BackingPixel = 256,
    OverrideRedirect = 512,
    SaveUnder = 1024,
    EventMask = 2048,
    DontPropagate = 4096,
    Colormap = 8192,
    Cursor = 16384,
    _,

    pub fn of(flags: []const @This()) u32 {
        return wire.maskOf(@This(), flags);
    }
};

pub const EventMask = enum(u32) {
    NoEvent = 0,
    KeyPress = 1,
    KeyRelease = 2,
    ButtonPress = 4,
    ButtonRelease = 8,
    EnterWindow = 16,
    LeaveWindow = 32,
    PointerMotion = 64,
    PointerMotionHint = 128,
    Button1Motion = 256,
    Button2Motion = 512,
    Button3Motion = 1024,
    Button4Motion = 2048,
    Button5Motion = 4096,
    ButtonMotion = 8192,
    KeymapState = 16384,
    Exposure = 32768,
    VisibilityChange = 65536,
    StructureNotify = 131072,
    ResizeRedirect = 262144,
    SubstructureNotify = 524288,
    SubstructureRedirect = 1048576,
    FocusChange = 2097152,
    PropertyChange = 4194304,
    ColorMapChange = 8388608,
    OwnerGrabButton = 16777216,
    _,

    pub fn of(flags: []const @This()) u32 {
        return wire.maskOf(@This(), flags);
    }
};

pub const InternAtomRequest = struct {
    pub const opcode: u8 = 16;
    pub const Reply = InternAtomReply;

    only_if_exists: bool,
    name: []const u8,

    pub fn byteLen(self: @This()) usize {
        return 4 + 2 + 2 + self.name.len;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        const len = self.byteLen();
        const pad = wire.pad4(len);
        try writer.writeByte(opcode);
        try writer.writeByte(@intFromBool(self.only_if_exists));
        try writer.writeInt(u16, @intCast((len + pad) / 4), .little);
        try writer.writeInt(u16, @intCast(self.name.len), .little);
        try writer.splatByteAll(0, 2);
        try writer.writeAll(self.name);
        try writer.splatByteAll(0, pad);
    }
};

pub const InternAtomReply = struct {
    atom: Atom,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        if (try reader.takeByte() != 1) return error.UnexpectedReplyType;
        _ = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        _ = try reader.takeInt(u32, .little);
        const atom = @as(Atom, @enumFromInt(try reader.takeInt(u32, .little)));
        _ = try reader.take(20);
        return .{
            .atom = atom,
        };
    }
};

pub const GetPropertyRequest = struct {
    pub const opcode: u8 = 20;
    pub const Reply = GetPropertyReply;

    delete_value: bool,
    window: Window,
    property: Atom,
    type_atom: Atom,
    long_offset: u32,
    long_length: u32,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 4 + 4 + 4 + 4 + 4;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        const len = self.byteLen();
        const pad = wire.pad4(len);
        try writer.writeByte(opcode);
        try writer.writeByte(@intFromBool(self.delete_value));
        try writer.writeInt(u16, @intCast((len + pad) / 4), .little);
        try writer.writeInt(u32, @intFromEnum(self.window), .little);
        try writer.writeInt(u32, @intFromEnum(self.property), .little);
        try writer.writeInt(u32, @intFromEnum(self.type_atom), .little);
        try writer.writeInt(u32, self.long_offset, .little);
        try writer.writeInt(u32, self.long_length, .little);
        try writer.splatByteAll(0, pad);
    }
};

pub const GetPropertyReply = struct {
    format: u8,
    type_atom: Atom,
    bytes_after: u32,
    value_len: u32,
    value: []const u8,

    pub fn decode(reader: *std.Io.Reader, scratch: []u8) wire.Error!@This() {
        if (try reader.takeByte() != 1) return error.UnexpectedReplyType;
        const format = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        const reply_len = @as(usize, try reader.takeInt(u32, .little)) * 4;
        const type_atom = @as(Atom, @enumFromInt(try reader.takeInt(u32, .little)));
        const bytes_after = try reader.takeInt(u32, .little);
        const value_len = try reader.takeInt(u32, .little);
        _ = try reader.take(12);
        const value_bytes = try wire.valueByteLen(format, value_len);
        if (reply_len < value_bytes) return error.MalformedPacket;
        if (scratch.len < value_bytes) return error.BufferTooSmall;
        @memcpy(scratch[0..value_bytes], try reader.take(value_bytes));
        _ = try reader.take(reply_len - value_bytes);
        return .{
            .format = format,
            .type_atom = type_atom,
            .bytes_after = bytes_after,
            .value_len = value_len,
            .value = scratch[0..value_bytes],
        };
    }
};

pub const GetInputFocusRequest = struct {
    pub const opcode: u8 = 43;
    pub const Reply = GetInputFocusReply;


    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 0;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        const len = self.byteLen();
        const pad = wire.pad4(len);
        try writer.writeByte(opcode);
        try writer.writeByte(0);
        try writer.writeInt(u16, @intCast((len + pad) / 4), .little);
        try writer.splatByteAll(0, pad);
    }
};

pub const GetInputFocusReply = struct {
    revert_to: u8,
    focus: Window,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        if (try reader.takeByte() != 1) return error.UnexpectedReplyType;
        const revert_to = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        _ = try reader.takeInt(u32, .little);
        const focus = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        _ = try reader.take(20);
        return .{
            .revert_to = revert_to,
            .focus = focus,
        };
    }
};

pub const CreateWindowValueList = struct {
    background_pixmap: ?Pixmap = null,
    background_pixel: ?u32 = null,
    border_pixmap: ?Pixmap = null,
    border_pixel: ?u32 = null,
    bit_gravity: ?u32 = null,
    win_gravity: ?u32 = null,
    backing_store: ?u32 = null,
    backing_planes: ?u32 = null,
    backing_pixel: ?u32 = null,
    override_redirect: ?u32 = null,
    save_under: ?u32 = null,
    event_mask: ?u32 = null,
    do_not_propogate_mask: ?u32 = null,
    colormap: ?Colormap = null,
    cursor: ?Cursor = null,
};

pub const CreateWindowValueListSpec = struct {
    pub const fields = .{
        .{ .name = "background_pixmap", .bit = @intFromEnum(CW.BackPixmap), .value_type = Pixmap },
        .{ .name = "background_pixel", .bit = @intFromEnum(CW.BackPixel), .value_type = u32 },
        .{ .name = "border_pixmap", .bit = @intFromEnum(CW.BorderPixmap), .value_type = Pixmap },
        .{ .name = "border_pixel", .bit = @intFromEnum(CW.BorderPixel), .value_type = u32 },
        .{ .name = "bit_gravity", .bit = @intFromEnum(CW.BitGravity), .value_type = u32 },
        .{ .name = "win_gravity", .bit = @intFromEnum(CW.WinGravity), .value_type = u32 },
        .{ .name = "backing_store", .bit = @intFromEnum(CW.BackingStore), .value_type = u32 },
        .{ .name = "backing_planes", .bit = @intFromEnum(CW.BackingPlanes), .value_type = u32 },
        .{ .name = "backing_pixel", .bit = @intFromEnum(CW.BackingPixel), .value_type = u32 },
        .{ .name = "override_redirect", .bit = @intFromEnum(CW.OverrideRedirect), .value_type = u32 },
        .{ .name = "save_under", .bit = @intFromEnum(CW.SaveUnder), .value_type = u32 },
        .{ .name = "event_mask", .bit = @intFromEnum(CW.EventMask), .value_type = u32 },
        .{ .name = "do_not_propogate_mask", .bit = @intFromEnum(CW.DontPropagate), .value_type = u32 },
        .{ .name = "colormap", .bit = @intFromEnum(CW.Colormap), .value_type = Colormap },
        .{ .name = "cursor", .bit = @intFromEnum(CW.Cursor), .value_type = Cursor },
    };
};

pub const CreateWindowRequest = struct {
    pub const opcode: u8 = 1;
    pub const Reply = void;

    depth: u8,
    wid: Window,
    parent: Window,
    x: i16,
    y: i16,
    width: u16,
    height: u16,
    border_width: u16,
    class: u16,
    visual: u32,
    value_list: CreateWindowValueList,

    pub fn byteLen(self: @This()) usize {
        return 4 + 4 + 4 + 2 + 2 + 2 + 2 + 2 + 2 + 4 + 4 + wire.valueListByteLen(CreateWindowValueListSpec, self.value_list);
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        const len = self.byteLen();
        const pad = wire.pad4(len);
        try writer.writeByte(opcode);
        try writer.writeByte(self.depth);
        try writer.writeInt(u16, @intCast((len + pad) / 4), .little);
        const value_mask = wire.computeValueMask(CreateWindowValueListSpec, self.value_list);
        try writer.writeInt(u32, @intFromEnum(self.wid), .little);
        try writer.writeInt(u32, @intFromEnum(self.parent), .little);
        try writer.writeInt(i16, self.x, .little);
        try writer.writeInt(i16, self.y, .little);
        try writer.writeInt(u16, self.width, .little);
        try writer.writeInt(u16, self.height, .little);
        try writer.writeInt(u16, self.border_width, .little);
        try writer.writeInt(u16, self.class, .little);
        try writer.writeInt(u32, self.visual, .little);
        try writer.writeInt(u32, value_mask, .little);
        try wire.writeValueList(CreateWindowValueListSpec, self.value_list, writer);
        try writer.splatByteAll(0, pad);
    }
};

pub const MapWindowRequest = struct {
    pub const opcode: u8 = 8;
    pub const Reply = void;

    window: Window,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 4;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        const len = self.byteLen();
        const pad = wire.pad4(len);
        try writer.writeByte(opcode);
        try writer.writeByte(0);
        try writer.writeInt(u16, @intCast((len + pad) / 4), .little);
        try writer.writeInt(u32, @intFromEnum(self.window), .little);
        try writer.splatByteAll(0, pad);
    }
};

pub const ButtonPressEvent = struct {
    detail: u8,
    time: u32,
    root: Window,
    event: Window,
    child: Window,
    root_x: i16,
    root_y: i16,
    event_x: i16,
    event_y: i16,
    state: u16,
    same_screen: bool,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        if ((try reader.takeByte()) & 0x7f != 4) return error.UnexpectedEventType;
        const detail = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        const time = try reader.takeInt(u32, .little);
        const root = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const child = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const root_x = try reader.takeInt(i16, .little);
        const root_y = try reader.takeInt(i16, .little);
        const event_x = try reader.takeInt(i16, .little);
        const event_y = try reader.takeInt(i16, .little);
        const state = try reader.takeInt(u16, .little);
        const same_screen = (try reader.takeByte()) != 0;
        _ = try reader.take(1);
        return .{
            .detail = detail,
            .time = time,
            .root = root,
            .event = event,
            .child = child,
            .root_x = root_x,
            .root_y = root_y,
            .event_x = event_x,
            .event_y = event_y,
            .state = state,
            .same_screen = same_screen,
        };
    }
};

pub const ExposeEvent = struct {
    window: Window,
    x: u16,
    y: u16,
    width: u16,
    height: u16,
    count: u16,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        if ((try reader.takeByte()) & 0x7f != 12) return error.UnexpectedEventType;
        _ = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const x = try reader.takeInt(u16, .little);
        const y = try reader.takeInt(u16, .little);
        const width = try reader.takeInt(u16, .little);
        const height = try reader.takeInt(u16, .little);
        const count = try reader.takeInt(u16, .little);
        _ = try reader.take(2);
        _ = try reader.take(12);
        return .{
            .window = window,
            .x = x,
            .y = y,
            .width = width,
            .height = height,
            .count = count,
        };
    }
};

pub const MapNotifyEvent = struct {
    event: Window,
    window: Window,
    override_redirect: bool,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        if ((try reader.takeByte()) & 0x7f != 19) return error.UnexpectedEventType;
        _ = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const override_redirect = (try reader.takeByte()) != 0;
        _ = try reader.take(3);
        _ = try reader.take(16);
        return .{
            .event = event,
            .window = window,
            .override_redirect = override_redirect,
        };
    }
};

pub const ConfigureNotifyEvent = struct {
    event: Window,
    window: Window,
    above_sibling: Window,
    x: i16,
    y: i16,
    width: u16,
    height: u16,
    border_width: u16,
    override_redirect: bool,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        if ((try reader.takeByte()) & 0x7f != 22) return error.UnexpectedEventType;
        _ = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const above_sibling = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const x = try reader.takeInt(i16, .little);
        const y = try reader.takeInt(i16, .little);
        const width = try reader.takeInt(u16, .little);
        const height = try reader.takeInt(u16, .little);
        const border_width = try reader.takeInt(u16, .little);
        const override_redirect = (try reader.takeByte()) != 0;
        _ = try reader.take(1);
        _ = try reader.take(4);
        return .{
            .event = event,
            .window = window,
            .above_sibling = above_sibling,
            .x = x,
            .y = y,
            .width = width,
            .height = height,
            .border_width = border_width,
            .override_redirect = override_redirect,
        };
    }
};

pub const ReparentNotifyEvent = struct {
    event: Window,
    window: Window,
    parent: Window,
    x: i16,
    y: i16,
    override_redirect: bool,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        if ((try reader.takeByte()) & 0x7f != 21) return error.UnexpectedEventType;
        _ = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const parent = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const x = try reader.takeInt(i16, .little);
        const y = try reader.takeInt(i16, .little);
        const override_redirect = (try reader.takeByte()) != 0;
        _ = try reader.take(3);
        _ = try reader.take(8);
        return .{
            .event = event,
            .window = window,
            .parent = parent,
            .x = x,
            .y = y,
            .override_redirect = override_redirect,
        };
    }
};

pub const UnknownEvent = struct {
    code: u8,
    sequence: u16,
    raw: [32]u8,
};

pub const Event = union(enum) {
    unknown: UnknownEvent,
    button_press: ButtonPressEvent,
    expose: ExposeEvent,
    map_notify: MapNotifyEvent,
    configure_notify: ConfigureNotifyEvent,
    reparent_notify: ReparentNotifyEvent,
};

pub fn decodeEvent(reader: *std.Io.Reader) wire.Error!Event {
    const code = (try reader.peek(1))[0] & 0x7f;
    return switch (code) {
        4 => .{ .button_press = try ButtonPressEvent.decode(reader) },
        12 => .{ .expose = try ExposeEvent.decode(reader) },
        19 => .{ .map_notify = try MapNotifyEvent.decode(reader) },
        22 => .{ .configure_notify = try ConfigureNotifyEvent.decode(reader) },
        21 => .{ .reparent_notify = try ReparentNotifyEvent.decode(reader) },
        else => blk: {
            const packet = try reader.take(32);
            var raw: [32]u8 = undefined;
            @memcpy(raw[0..], packet);
            break :blk .{ .unknown = .{
                .code = packet[0] & 0x7f,
                .sequence = std.mem.readInt(u16, packet[2..4], .little),
                .raw = raw,
            } };
        },
    };
}

