// This file is generated by tools/gennew.py

const std = @import("std");
const wire = @import("wire.zig");

// selected requests: CreateWindow, GetInputFocus, GetProperty, InternAtom, MapWindow
// selected structs: DEPTH, FORMAT, SCREEN, Setup, SetupAuthenticate, SetupFailed, SetupRequest, VISUALTYPE

pub const Atom = enum(u32) { _ };

pub const Colormap = enum(u32) { _ };

pub const Cursor = enum(u32) { _ };

pub const Font = enum(u32) { _ };

pub const Gcontext = enum(u32) { _ };

pub const Pixmap = enum(u32) { _ };

pub const Window = enum(u32) { _ };

pub const Drawable = enum(u32) { _ };

pub const Fontable = enum(u32) { _ };

pub const ClientMessageData = struct {
    raw: [20]u8,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 20;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeAll(self.raw[0..]);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        var raw: [20]u8 = undefined;
        @memcpy(raw[0..], try reader.take(20));
        return .{ .raw = raw };
    }
};

pub const Error = enum(u32) {
    Request = 1,
    Value = 2,
    Window = 3,
    Pixmap = 4,
    Atom = 5,
    Cursor = 6,
    Font = 7,
    Match = 8,
    Drawable = 9,
    Access = 10,
    Alloc = 11,
    Colormap = 12,
    GContext = 13,
    IDChoice = 14,
    Name = 15,
    Length = 16,
    Implementation = 17,
    _,
};

pub const AccessControl = enum(u32) {
    Disable = 0,
    Enable = 1,
    _,
};

pub const Allow = enum(u32) {
    AsyncPointer = 0,
    SyncPointer = 1,
    ReplayPointer = 2,
    AsyncKeyboard = 3,
    SyncKeyboard = 4,
    ReplayKeyboard = 5,
    AsyncBoth = 6,
    SyncBoth = 7,
    _,
};

pub const ArcMode = enum(u32) {
    Chord = 0,
    PieSlice = 1,
    _,
};

pub const AutoRepeatMode = enum(u32) {
    Off = 0,
    On = 1,
    Default = 2,
    _,
};

pub const BackPixmap = enum(u32) {
    None = 0,
    ParentRelative = 1,
    _,
};

pub const BackingStore = enum(u32) {
    NotUseful = 0,
    WhenMapped = 1,
    Always = 2,
    _,
};

pub const Blanking = enum(u32) {
    NotPreferred = 0,
    Preferred = 1,
    Default = 2,
    _,
};

pub const ButtonIndex = enum(u32) {
    Any = 0,
    @"1" = 1,
    @"2" = 2,
    @"3" = 3,
    @"4" = 4,
    @"5" = 5,
    _,
};

pub const ButtonMask = enum(u32) {
    @"1" = 256,
    @"2" = 512,
    @"3" = 1024,
    @"4" = 2048,
    @"5" = 4096,
    Any = 32768,
    _,
};

pub const CW = enum(u32) {
    BackPixmap = 1,
    BackPixel = 2,
    BorderPixmap = 4,
    BorderPixel = 8,
    BitGravity = 16,
    WinGravity = 32,
    BackingStore = 64,
    BackingPlanes = 128,
    BackingPixel = 256,
    OverrideRedirect = 512,
    SaveUnder = 1024,
    EventMask = 2048,
    DontPropagate = 4096,
    Colormap = 8192,
    Cursor = 16384,
    _,

    pub fn of(flags: []const @This()) u32 {
        return wire.maskOf(@This(), flags);
    }
};

pub const CapStyle = enum(u32) {
    NotLast = 0,
    Butt = 1,
    Round = 2,
    Projecting = 3,
    _,
};

pub const Circulate = enum(u32) {
    RaiseLowest = 0,
    LowerHighest = 1,
    _,
};

pub const ClipOrdering = enum(u32) {
    Unsorted = 0,
    YSorted = 1,
    YXSorted = 2,
    YXBanded = 3,
    _,
};

pub const CloseDown = enum(u32) {
    DestroyAll = 0,
    RetainPermanent = 1,
    RetainTemporary = 2,
    _,
};

pub const ColorFlag = enum(u32) {
    Red = 1,
    Green = 2,
    Blue = 4,
    _,

    pub fn of(flags: []const @This()) u32 {
        return wire.maskOf(@This(), flags);
    }
};

pub const ColormapAlloc = enum(u32) {
    None = 0,
    All = 1,
    _,
};

pub const ColormapState = enum(u32) {
    Uninstalled = 0,
    Installed = 1,
    _,
};

pub const ConfigWindow = enum(u32) {
    X = 1,
    Y = 2,
    Width = 4,
    Height = 8,
    BorderWidth = 16,
    Sibling = 32,
    StackMode = 64,
    _,

    pub fn of(flags: []const @This()) u32 {
        return wire.maskOf(@This(), flags);
    }
};

pub const CoordMode = enum(u32) {
    Origin = 0,
    Previous = 1,
    _,
};

pub const EventMask = enum(u32) {
    NoEvent = 0,
    KeyPress = 1,
    KeyRelease = 2,
    ButtonPress = 4,
    ButtonRelease = 8,
    EnterWindow = 16,
    LeaveWindow = 32,
    PointerMotion = 64,
    PointerMotionHint = 128,
    Button1Motion = 256,
    Button2Motion = 512,
    Button3Motion = 1024,
    Button4Motion = 2048,
    Button5Motion = 4096,
    ButtonMotion = 8192,
    KeymapState = 16384,
    Exposure = 32768,
    VisibilityChange = 65536,
    StructureNotify = 131072,
    ResizeRedirect = 262144,
    SubstructureNotify = 524288,
    SubstructureRedirect = 1048576,
    FocusChange = 2097152,
    PropertyChange = 4194304,
    ColorMapChange = 8388608,
    OwnerGrabButton = 16777216,
    _,

    pub fn of(flags: []const @This()) u32 {
        return wire.maskOf(@This(), flags);
    }
};

pub const Exposures = enum(u32) {
    NotAllowed = 0,
    Allowed = 1,
    Default = 2,
    _,
};

pub const Family = enum(u32) {
    Internet = 0,
    DECnet = 1,
    Chaos = 2,
    ServerInterpreted = 5,
    Internet6 = 6,
    _,
};

pub const FillRule = enum(u32) {
    EvenOdd = 0,
    Winding = 1,
    _,
};

pub const FillStyle = enum(u32) {
    Solid = 0,
    Tiled = 1,
    Stippled = 2,
    OpaqueStippled = 3,
    _,
};

pub const FontDraw = enum(u32) {
    LeftToRight = 0,
    RightToLeft = 1,
    _,
};

pub const GC = enum(u32) {
    Function = 1,
    PlaneMask = 2,
    Foreground = 4,
    Background = 8,
    LineWidth = 16,
    LineStyle = 32,
    CapStyle = 64,
    JoinStyle = 128,
    FillStyle = 256,
    FillRule = 512,
    Tile = 1024,
    Stipple = 2048,
    TileStippleOriginX = 4096,
    TileStippleOriginY = 8192,
    Font = 16384,
    SubwindowMode = 32768,
    GraphicsExposures = 65536,
    ClipOriginX = 131072,
    ClipOriginY = 262144,
    ClipMask = 524288,
    DashOffset = 1048576,
    DashList = 2097152,
    ArcMode = 4194304,
    _,

    pub fn of(flags: []const @This()) u32 {
        return wire.maskOf(@This(), flags);
    }
};

pub const GX = enum(u32) {
    Clear = 0,
    And = 1,
    AndReverse = 2,
    Copy = 3,
    AndInverted = 4,
    Noop = 5,
    Xor = 6,
    Or = 7,
    Nor = 8,
    Equiv = 9,
    Invert = 10,
    OrReverse = 11,
    CopyInverted = 12,
    OrInverted = 13,
    Nand = 14,
    Set = 15,
    _,
};

pub const GetPropertyType = enum(u32) {
    Any = 0,
    _,
};

pub const Grab = enum(u32) {
    Any = 0,
    _,
};

pub const GrabMode = enum(u32) {
    Sync = 0,
    Async = 1,
    _,
};

pub const GrabStatus = enum(u32) {
    Success = 0,
    AlreadyGrabbed = 1,
    InvalidTime = 2,
    NotViewable = 3,
    Frozen = 4,
    _,
};

pub const Gravity = enum(u32) {
    BitForget = 0,
    NorthWest = 1,
    North = 2,
    NorthEast = 3,
    West = 4,
    Center = 5,
    East = 6,
    SouthWest = 7,
    South = 8,
    SouthEast = 9,
    Static = 10,
    _,

    pub const WinUnmap = @This().BitForget;
};

pub const HostMode = enum(u32) {
    Insert = 0,
    Delete = 1,
    _,
};

pub const ImageFormat = enum(u32) {
    XYBitmap = 0,
    XYPixmap = 1,
    ZPixmap = 2,
    _,
};

pub const ImageOrder = enum(u32) {
    LSBFirst = 0,
    MSBFirst = 1,
    _,
};

pub const InputFocus = enum(u32) {
    None = 0,
    PointerRoot = 1,
    Parent = 2,
    FollowKeyboard = 3,
    _,
};

pub const JoinStyle = enum(u32) {
    Miter = 0,
    Round = 1,
    Bevel = 2,
    _,
};

pub const KB = enum(u32) {
    KeyClickPercent = 1,
    BellPercent = 2,
    BellPitch = 4,
    BellDuration = 8,
    Led = 16,
    LedMode = 32,
    Key = 64,
    AutoRepeatMode = 128,
    _,

    pub fn of(flags: []const @This()) u32 {
        return wire.maskOf(@This(), flags);
    }
};

pub const KeyButMask = enum(u32) {
    Shift = 1,
    Lock = 2,
    Control = 4,
    Mod1 = 8,
    Mod2 = 16,
    Mod3 = 32,
    Mod4 = 64,
    Mod5 = 128,
    Button1 = 256,
    Button2 = 512,
    Button3 = 1024,
    Button4 = 2048,
    Button5 = 4096,
    _,

    pub fn of(flags: []const @This()) u32 {
        return wire.maskOf(@This(), flags);
    }
};

pub const Kill = enum(u32) {
    AllTemporary = 0,
    _,
};

pub const LedMode = enum(u32) {
    Off = 0,
    On = 1,
    _,
};

pub const LineStyle = enum(u32) {
    Solid = 0,
    OnOffDash = 1,
    DoubleDash = 2,
    _,
};

pub const MapIndex = enum(u32) {
    Shift = 0,
    Lock = 1,
    Control = 2,
    @"1" = 3,
    @"2" = 4,
    @"3" = 5,
    @"4" = 6,
    @"5" = 7,
    _,
};

pub const MapState = enum(u32) {
    Unmapped = 0,
    Unviewable = 1,
    Viewable = 2,
    _,
};

pub const Mapping = enum(u32) {
    Modifier = 0,
    Keyboard = 1,
    Pointer = 2,
    _,
};

pub const MappingStatus = enum(u32) {
    Success = 0,
    Busy = 1,
    Failure = 2,
    _,
};

pub const ModMask = enum(u32) {
    Shift = 1,
    Lock = 2,
    Control = 4,
    @"1" = 8,
    @"2" = 16,
    @"3" = 32,
    @"4" = 64,
    @"5" = 128,
    Any = 32768,
    _,

    pub fn of(flags: []const @This()) u32 {
        return wire.maskOf(@This(), flags);
    }
};

pub const Motion = enum(u32) {
    Normal = 0,
    Hint = 1,
    _,
};

pub const NotifyDetail = enum(u32) {
    Ancestor = 0,
    Virtual = 1,
    Inferior = 2,
    Nonlinear = 3,
    NonlinearVirtual = 4,
    Pointer = 5,
    PointerRoot = 6,
    None = 7,
    _,
};

pub const NotifyMode = enum(u32) {
    Normal = 0,
    Grab = 1,
    Ungrab = 2,
    WhileGrabbed = 3,
    _,
};

pub const Place = enum(u32) {
    OnTop = 0,
    OnBottom = 1,
    _,
};

pub const PolyShape = enum(u32) {
    Complex = 0,
    Nonconvex = 1,
    Convex = 2,
    _,
};

pub const PropMode = enum(u32) {
    Replace = 0,
    Prepend = 1,
    Append = 2,
    _,
};

pub const Property = enum(u32) {
    NewValue = 0,
    Delete = 1,
    _,
};

pub const QueryShapeOf = enum(u32) {
    LargestCursor = 0,
    FastestTile = 1,
    FastestStipple = 2,
    _,
};

pub const ScreenSaver = enum(u32) {
    Reset = 0,
    Active = 1,
    _,
};

pub const SendEventDest = enum(u32) {
    PointerWindow = 0,
    ItemFocus = 1,
    _,
};

pub const SetMode = enum(u32) {
    Insert = 0,
    Delete = 1,
    _,
};

pub const StackMode = enum(u32) {
    Above = 0,
    Below = 1,
    TopIf = 2,
    BottomIf = 3,
    Opposite = 4,
    _,
};

pub const SubwindowMode = enum(u32) {
    ClipByChildren = 0,
    IncludeInferiors = 1,
    _,
};

pub const Time = enum(u32) {
    CurrentTime = 0,
    _,
};

pub const Visibility = enum(u32) {
    Unobscured = 0,
    PartiallyObscured = 1,
    FullyObscured = 2,
    _,
};

pub const VisualClass = enum(u32) {
    StaticGray = 0,
    GrayScale = 1,
    StaticColor = 2,
    PseudoColor = 3,
    TrueColor = 4,
    DirectColor = 5,
    _,
};

pub const WindowClass = enum(u32) {
    CopyFromParent = 0,
    InputOutput = 1,
    InputOnly = 2,
    _,
};

pub const DEPTH = struct {
    depth: u8,
    visuals: []VISUALTYPE,

    pub fn byteLen(self: @This()) usize {
        return 1 + 1 + 2 + 4 + wire.structListByteLen(self.visuals);
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.depth);
        try writer.splatByteAll(0, 1);
        try writer.writeInt(u16, @intCast(self.visuals.len), .little);
        try writer.splatByteAll(0, 4);
        for (self.visuals) |elem| {
            try elem.encode(writer);
        }
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const depth = try reader.takeByte();
        _ = try reader.take(1);
        const visuals_len = try reader.takeInt(u16, .little);
        _ = try reader.take(4);
        const visuals = try allocator.alloc(VISUALTYPE, @as(usize, visuals_len));
        errdefer allocator.free(visuals);
        var visuals_decoded: usize = 0;
        for (visuals) |*elem| {
            const elem_value = try VISUALTYPE.decode(reader);
            elem.* = elem_value;
            visuals_decoded += 1;
        }
        return .{
            .depth = depth,
            .visuals = visuals,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.visuals);
    }
};

pub const FORMAT = struct {
    depth: u8,
    bits_per_pixel: u8,
    scanline_pad: u8,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 1 + 1 + 1 + 5;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.depth);
        try writer.writeByte(self.bits_per_pixel);
        try writer.writeByte(self.scanline_pad);
        try writer.splatByteAll(0, 5);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const depth = try reader.takeByte();
        const bits_per_pixel = try reader.takeByte();
        const scanline_pad = try reader.takeByte();
        _ = try reader.take(5);
        return .{
            .depth = depth,
            .bits_per_pixel = bits_per_pixel,
            .scanline_pad = scanline_pad,
        };
    }
};

pub const SCREEN = struct {
    root: Window,
    default_colormap: Colormap,
    white_pixel: u32,
    black_pixel: u32,
    current_input_masks: u32,
    width_in_pixels: u16,
    height_in_pixels: u16,
    width_in_millimeters: u16,
    height_in_millimeters: u16,
    min_installed_maps: u16,
    max_installed_maps: u16,
    root_visual: u32,
    backing_stores: BackingStore,
    save_unders: bool,
    root_depth: u8,
    allowed_depths: []DEPTH,

    pub fn byteLen(self: @This()) usize {
        return 4 + 4 + 4 + 4 + 4 + 2 + 2 + 2 + 2 + 2 + 2 + 4 + 1 + 1 + 1 + 1 + wire.structListByteLen(self.allowed_depths);
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(u32, @intFromEnum(self.root), .little);
        try writer.writeInt(u32, @intFromEnum(self.default_colormap), .little);
        try writer.writeInt(u32, self.white_pixel, .little);
        try writer.writeInt(u32, self.black_pixel, .little);
        try writer.writeInt(u32, self.current_input_masks, .little);
        try writer.writeInt(u16, self.width_in_pixels, .little);
        try writer.writeInt(u16, self.height_in_pixels, .little);
        try writer.writeInt(u16, self.width_in_millimeters, .little);
        try writer.writeInt(u16, self.height_in_millimeters, .little);
        try writer.writeInt(u16, self.min_installed_maps, .little);
        try writer.writeInt(u16, self.max_installed_maps, .little);
        try writer.writeInt(u32, self.root_visual, .little);
        try writer.writeByte(@intCast(@intFromEnum(self.backing_stores)));
        try writer.writeByte(@intFromBool(self.save_unders));
        try writer.writeByte(self.root_depth);
        try writer.writeByte(@intCast(self.allowed_depths.len));
        for (self.allowed_depths) |elem| {
            try elem.encode(writer);
        }
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const root = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const default_colormap = @as(Colormap, @enumFromInt(try reader.takeInt(u32, .little)));
        const white_pixel = try reader.takeInt(u32, .little);
        const black_pixel = try reader.takeInt(u32, .little);
        const current_input_masks = try reader.takeInt(u32, .little);
        const width_in_pixels = try reader.takeInt(u16, .little);
        const height_in_pixels = try reader.takeInt(u16, .little);
        const width_in_millimeters = try reader.takeInt(u16, .little);
        const height_in_millimeters = try reader.takeInt(u16, .little);
        const min_installed_maps = try reader.takeInt(u16, .little);
        const max_installed_maps = try reader.takeInt(u16, .little);
        const root_visual = try reader.takeInt(u32, .little);
        const backing_stores = @as(BackingStore, @enumFromInt(try reader.takeInt(u8, .little)));
        const save_unders = (try reader.takeByte()) != 0;
        const root_depth = try reader.takeByte();
        const allowed_depths_len = try reader.takeByte();
        const allowed_depths = try allocator.alloc(DEPTH, @as(usize, allowed_depths_len));
        errdefer allocator.free(allowed_depths);
        var allowed_depths_decoded: usize = 0;
        errdefer for (allowed_depths[0..allowed_depths_decoded]) |*elem| elem.deinit(allocator);
        for (allowed_depths) |*elem| {
            const elem_value = try DEPTH.decode(allocator, reader);
            elem.* = elem_value;
            allowed_depths_decoded += 1;
        }
        return .{
            .root = root,
            .default_colormap = default_colormap,
            .white_pixel = white_pixel,
            .black_pixel = black_pixel,
            .current_input_masks = current_input_masks,
            .width_in_pixels = width_in_pixels,
            .height_in_pixels = height_in_pixels,
            .width_in_millimeters = width_in_millimeters,
            .height_in_millimeters = height_in_millimeters,
            .min_installed_maps = min_installed_maps,
            .max_installed_maps = max_installed_maps,
            .root_visual = root_visual,
            .backing_stores = backing_stores,
            .save_unders = save_unders,
            .root_depth = root_depth,
            .allowed_depths = allowed_depths,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        for (self.allowed_depths) |*elem| elem.deinit(allocator);
        allocator.free(self.allowed_depths);
    }
};

pub const Setup = struct {
    status: u8,
    protocol_major_version: u16,
    protocol_minor_version: u16,
    length: u16,
    release_number: u32,
    resource_id_base: u32,
    resource_id_mask: u32,
    motion_buffer_size: u32,
    maximum_request_length: u16,
    image_byte_order: ImageOrder,
    bitmap_format_bit_order: ImageOrder,
    bitmap_format_scanline_unit: u8,
    bitmap_format_scanline_pad: u8,
    min_keycode: u8,
    max_keycode: u8,
    vendor: []const u8,
    pixmap_formats: []FORMAT,
    roots: []SCREEN,

    pub fn byteLen(self: @This()) usize {
        return 1 + 1 + 2 + 2 + 2 + 4 + 4 + 4 + 4 + 2 + 2 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 1 + 4 + self.vendor.len + wire.pad4(self.vendor.len) + wire.structListByteLen(self.pixmap_formats) + wire.structListByteLen(self.roots);
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.status);
        try writer.splatByteAll(0, 1);
        try writer.writeInt(u16, self.protocol_major_version, .little);
        try writer.writeInt(u16, self.protocol_minor_version, .little);
        try writer.writeInt(u16, self.length, .little);
        try writer.writeInt(u32, self.release_number, .little);
        try writer.writeInt(u32, self.resource_id_base, .little);
        try writer.writeInt(u32, self.resource_id_mask, .little);
        try writer.writeInt(u32, self.motion_buffer_size, .little);
        try writer.writeInt(u16, @intCast(self.vendor.len), .little);
        try writer.writeInt(u16, self.maximum_request_length, .little);
        try writer.writeByte(@intCast(self.roots.len));
        try writer.writeByte(@intCast(self.pixmap_formats.len));
        try writer.writeByte(@intCast(@intFromEnum(self.image_byte_order)));
        try writer.writeByte(@intCast(@intFromEnum(self.bitmap_format_bit_order)));
        try writer.writeByte(self.bitmap_format_scanline_unit);
        try writer.writeByte(self.bitmap_format_scanline_pad);
        try writer.writeByte(self.min_keycode);
        try writer.writeByte(self.max_keycode);
        try writer.splatByteAll(0, 4);
        try writer.writeAll(self.vendor);
        try writer.splatByteAll(0, wire.pad4(self.vendor.len));
        for (self.pixmap_formats) |elem| {
            try elem.encode(writer);
        }
        for (self.roots) |elem| {
            try elem.encode(writer);
        }
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const status = try reader.takeByte();
        _ = try reader.take(1);
        const protocol_major_version = try reader.takeInt(u16, .little);
        const protocol_minor_version = try reader.takeInt(u16, .little);
        const length = try reader.takeInt(u16, .little);
        const release_number = try reader.takeInt(u32, .little);
        const resource_id_base = try reader.takeInt(u32, .little);
        const resource_id_mask = try reader.takeInt(u32, .little);
        const motion_buffer_size = try reader.takeInt(u32, .little);
        const vendor_len = try reader.takeInt(u16, .little);
        const maximum_request_length = try reader.takeInt(u16, .little);
        const roots_len = try reader.takeByte();
        const pixmap_formats_len = try reader.takeByte();
        const image_byte_order = @as(ImageOrder, @enumFromInt(try reader.takeInt(u8, .little)));
        const bitmap_format_bit_order = @as(ImageOrder, @enumFromInt(try reader.takeInt(u8, .little)));
        const bitmap_format_scanline_unit = try reader.takeByte();
        const bitmap_format_scanline_pad = try reader.takeByte();
        const min_keycode = try reader.takeByte();
        const max_keycode = try reader.takeByte();
        _ = try reader.take(4);
        const vendor_byte_len = @as(usize, vendor_len);
        const vendor_temp = try reader.take(vendor_byte_len);
        const vendor = try allocator.dupe(u8, vendor_temp);
        _ = try reader.take(wire.pad4(vendor.len));
        const pixmap_formats = try allocator.alloc(FORMAT, @as(usize, pixmap_formats_len));
        errdefer allocator.free(pixmap_formats);
        var pixmap_formats_decoded: usize = 0;
        for (pixmap_formats) |*elem| {
            const elem_value = try FORMAT.decode(reader);
            elem.* = elem_value;
            pixmap_formats_decoded += 1;
        }
        const roots = try allocator.alloc(SCREEN, @as(usize, roots_len));
        errdefer allocator.free(roots);
        var roots_decoded: usize = 0;
        errdefer for (roots[0..roots_decoded]) |*elem| elem.deinit(allocator);
        for (roots) |*elem| {
            const elem_value = try SCREEN.decode(allocator, reader);
            elem.* = elem_value;
            roots_decoded += 1;
        }
        return .{
            .status = status,
            .protocol_major_version = protocol_major_version,
            .protocol_minor_version = protocol_minor_version,
            .length = length,
            .release_number = release_number,
            .resource_id_base = resource_id_base,
            .resource_id_mask = resource_id_mask,
            .motion_buffer_size = motion_buffer_size,
            .maximum_request_length = maximum_request_length,
            .image_byte_order = image_byte_order,
            .bitmap_format_bit_order = bitmap_format_bit_order,
            .bitmap_format_scanline_unit = bitmap_format_scanline_unit,
            .bitmap_format_scanline_pad = bitmap_format_scanline_pad,
            .min_keycode = min_keycode,
            .max_keycode = max_keycode,
            .vendor = vendor,
            .pixmap_formats = pixmap_formats,
            .roots = roots,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.vendor);
        allocator.free(self.pixmap_formats);
        for (self.roots) |*elem| elem.deinit(allocator);
        allocator.free(self.roots);
    }
};

pub const SetupAuthenticate = struct {
    status: u8,
    length: u16,
    reason: []const u8,

    pub fn byteLen(self: @This()) usize {
        return 1 + 5 + 2 + self.reason.len;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.status);
        try writer.splatByteAll(0, 5);
        try writer.writeInt(u16, self.length, .little);
        try writer.writeAll(self.reason);
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const status = try reader.takeByte();
        _ = try reader.take(5);
        const length = try reader.takeInt(u16, .little);
        const reason_byte_len = @as(usize, (length * 4));
        const reason_temp = try reader.take(reason_byte_len);
        const reason = try allocator.dupe(u8, reason_temp);
        return .{
            .status = status,
            .length = length,
            .reason = reason,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.reason);
    }
};

pub const SetupFailed = struct {
    status: u8,
    protocol_major_version: u16,
    protocol_minor_version: u16,
    length: u16,
    reason: []const u8,

    pub fn byteLen(self: @This()) usize {
        return 1 + 1 + 2 + 2 + 2 + self.reason.len;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.status);
        try writer.writeByte(@intCast(self.reason.len));
        try writer.writeInt(u16, self.protocol_major_version, .little);
        try writer.writeInt(u16, self.protocol_minor_version, .little);
        try writer.writeInt(u16, self.length, .little);
        try writer.writeAll(self.reason);
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const status = try reader.takeByte();
        const reason_len = try reader.takeByte();
        const protocol_major_version = try reader.takeInt(u16, .little);
        const protocol_minor_version = try reader.takeInt(u16, .little);
        const length = try reader.takeInt(u16, .little);
        const reason_byte_len = @as(usize, reason_len);
        const reason_temp = try reader.take(reason_byte_len);
        const reason = try allocator.dupe(u8, reason_temp);
        return .{
            .status = status,
            .protocol_major_version = protocol_major_version,
            .protocol_minor_version = protocol_minor_version,
            .length = length,
            .reason = reason,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.reason);
    }
};

pub const SetupRequest = struct {
    byte_order: u8,
    protocol_major_version: u16,
    protocol_minor_version: u16,
    authorization_protocol_name: []const u8,
    authorization_protocol_data: []const u8,

    pub fn byteLen(self: @This()) usize {
        return 1 + 1 + 2 + 2 + 2 + 2 + 2 + self.authorization_protocol_name.len + wire.pad4(self.authorization_protocol_name.len) + self.authorization_protocol_data.len + wire.pad4(self.authorization_protocol_data.len);
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.byte_order);
        try writer.splatByteAll(0, 1);
        try writer.writeInt(u16, self.protocol_major_version, .little);
        try writer.writeInt(u16, self.protocol_minor_version, .little);
        try writer.writeInt(u16, @intCast(self.authorization_protocol_name.len), .little);
        try writer.writeInt(u16, @intCast(self.authorization_protocol_data.len), .little);
        try writer.splatByteAll(0, 2);
        try writer.writeAll(self.authorization_protocol_name);
        try writer.splatByteAll(0, wire.pad4(self.authorization_protocol_name.len));
        try writer.writeAll(self.authorization_protocol_data);
        try writer.splatByteAll(0, wire.pad4(self.authorization_protocol_data.len));
    }

    pub fn decode(allocator: std.mem.Allocator, reader: *std.Io.Reader) wire.Error!@This() {
        const byte_order = try reader.takeByte();
        _ = try reader.take(1);
        const protocol_major_version = try reader.takeInt(u16, .little);
        const protocol_minor_version = try reader.takeInt(u16, .little);
        const authorization_protocol_name_len = try reader.takeInt(u16, .little);
        const authorization_protocol_data_len = try reader.takeInt(u16, .little);
        _ = try reader.take(2);
        const authorization_protocol_name_byte_len = @as(usize, authorization_protocol_name_len);
        const authorization_protocol_name_temp = try reader.take(authorization_protocol_name_byte_len);
        const authorization_protocol_name = try allocator.dupe(u8, authorization_protocol_name_temp);
        _ = try reader.take(wire.pad4(authorization_protocol_name.len));
        const authorization_protocol_data_byte_len = @as(usize, authorization_protocol_data_len);
        const authorization_protocol_data_temp = try reader.take(authorization_protocol_data_byte_len);
        const authorization_protocol_data = try allocator.dupe(u8, authorization_protocol_data_temp);
        _ = try reader.take(wire.pad4(authorization_protocol_data.len));
        return .{
            .byte_order = byte_order,
            .protocol_major_version = protocol_major_version,
            .protocol_minor_version = protocol_minor_version,
            .authorization_protocol_name = authorization_protocol_name,
            .authorization_protocol_data = authorization_protocol_data,
        };
    }

    pub fn deinit(self: *@This(), allocator: std.mem.Allocator) void {
        allocator.free(self.authorization_protocol_name);
        allocator.free(self.authorization_protocol_data);
    }
};

pub const VISUALTYPE = struct {
    visual_id: u32,
    class: VisualClass,
    bits_per_rgb_value: u8,
    colormap_entries: u16,
    red_mask: u32,
    green_mask: u32,
    blue_mask: u32,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 1 + 1 + 2 + 4 + 4 + 4 + 4;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeInt(u32, self.visual_id, .little);
        try writer.writeByte(@intCast(@intFromEnum(self.class)));
        try writer.writeByte(self.bits_per_rgb_value);
        try writer.writeInt(u16, self.colormap_entries, .little);
        try writer.writeInt(u32, self.red_mask, .little);
        try writer.writeInt(u32, self.green_mask, .little);
        try writer.writeInt(u32, self.blue_mask, .little);
        try writer.splatByteAll(0, 4);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        const visual_id = try reader.takeInt(u32, .little);
        const class = @as(VisualClass, @enumFromInt(try reader.takeInt(u8, .little)));
        const bits_per_rgb_value = try reader.takeByte();
        const colormap_entries = try reader.takeInt(u16, .little);
        const red_mask = try reader.takeInt(u32, .little);
        const green_mask = try reader.takeInt(u32, .little);
        const blue_mask = try reader.takeInt(u32, .little);
        _ = try reader.take(4);
        return .{
            .visual_id = visual_id,
            .class = class,
            .bits_per_rgb_value = bits_per_rgb_value,
            .colormap_entries = colormap_entries,
            .red_mask = red_mask,
            .green_mask = green_mask,
            .blue_mask = blue_mask,
        };
    }
};

pub const InternAtomReply = struct {
    atom: Atom,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 1 + 4;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.splatByteAll(0, 1);
        try writer.writeInt(u32, @intFromEnum(self.atom), .little);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        _ = try reader.takeInt(u32, .little);
        const atom = @as(Atom, @enumFromInt(try reader.takeInt(u32, .little)));
        return .{
            .atom = atom,
        };
    }
};

pub const InternAtom = struct {
    pub const opcode: u8 = 16;
    pub const Reply = InternAtomReply;

    only_if_exists: bool,
    name: []const u8,

    pub fn byteLen(self: @This()) usize {
        return 4 + 2 + 2 + self.name.len;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        const len = self.byteLen();
        const pad = wire.pad4(len);
        try writer.writeByte(opcode);
        try writer.writeByte(@intFromBool(self.only_if_exists));
        try writer.writeInt(u16, @intCast((len + pad) / 4), .little);
        try writer.writeInt(u16, @intCast(self.name.len), .little);
        try writer.splatByteAll(0, 2);
        try writer.writeAll(self.name);
        try writer.splatByteAll(0, pad);
    }
};

pub const GetPropertyReply = struct {
    format: u8,
    type: Atom,
    bytes_after: u32,
    value_len: u32,
    value: []const u8,

    pub fn byteLen(self: @This()) usize {
        return 1 + 4 + 4 + 4 + 12 + self.value.len;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(self.format);
        try writer.writeInt(u32, @intFromEnum(self.type), .little);
        try writer.writeInt(u32, self.bytes_after, .little);
        try writer.writeInt(u32, self.value_len, .little);
        try writer.splatByteAll(0, 12);
        try writer.writeAll(self.value);
    }

    pub fn decode(scratch: []u8, reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        const format = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        _ = try reader.takeInt(u32, .little);
        var scratch_used: usize = 0;
        const @"type" = @as(Atom, @enumFromInt(try reader.takeInt(u32, .little)));
        const bytes_after = try reader.takeInt(u32, .little);
        const value_len = try reader.takeInt(u32, .little);
        _ = try reader.take(12);
        const value_byte_len = @as(usize, (value_len * (format / 8)));
        const value_temp = try reader.take(value_byte_len);
        if (scratch_used + value_byte_len > scratch.len) return error.BufferTooSmall;
        @memcpy(scratch[scratch_used..][0..value_byte_len], value_temp);
        const value = scratch[scratch_used..][0..value_byte_len];
        scratch_used += value_byte_len;
        return .{
            .format = format,
            .type = @"type",
            .bytes_after = bytes_after,
            .value_len = value_len,
            .value = value,
        };
    }
};

pub const GetProperty = struct {
    pub const opcode: u8 = 20;
    pub const Reply = GetPropertyReply;

    delete: bool,
    window: Window,
    property: Atom,
    type: Atom,
    long_offset: u32,
    long_length: u32,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 4 + 4 + 4 + 4 + 4;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        const len = self.byteLen();
        const pad = wire.pad4(len);
        try writer.writeByte(opcode);
        try writer.writeByte(@intFromBool(self.delete));
        try writer.writeInt(u16, @intCast((len + pad) / 4), .little);
        try writer.writeInt(u32, @intFromEnum(self.window), .little);
        try writer.writeInt(u32, @intFromEnum(self.property), .little);
        try writer.writeInt(u32, @intFromEnum(self.type), .little);
        try writer.writeInt(u32, self.long_offset, .little);
        try writer.writeInt(u32, self.long_length, .little);
        try writer.splatByteAll(0, pad);
    }
};

pub const GetInputFocusReply = struct {
    revert_to: InputFocus,
    focus: Window,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 1 + 4;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        try writer.writeByte(@intCast(@intFromEnum(self.revert_to)));
        try writer.writeInt(u32, @intFromEnum(self.focus), .little);
    }

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        const revert_to = @as(InputFocus, @enumFromInt(try reader.takeInt(u8, .little)));
        _ = try reader.takeInt(u16, .little);
        _ = try reader.takeInt(u32, .little);
        const focus = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        return .{
            .revert_to = revert_to,
            .focus = focus,
        };
    }
};

pub const GetInputFocus = struct {
    pub const opcode: u8 = 43;
    pub const Reply = GetInputFocusReply;

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 0;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        const len = self.byteLen();
        const pad = wire.pad4(len);
        try writer.writeByte(opcode);
        try writer.splatByteAll(0, 1);
        try writer.writeInt(u16, @intCast((len + pad) / 4), .little);
        try writer.splatByteAll(0, pad);
    }
};

pub const CreateWindowValueList = struct {
    background_pixmap: ?Pixmap = null,
    background_pixel: ?u32 = null,
    border_pixmap: ?Pixmap = null,
    border_pixel: ?u32 = null,
    bit_gravity: ?Gravity = null,
    win_gravity: ?Gravity = null,
    backing_store: ?BackingStore = null,
    backing_planes: ?u32 = null,
    backing_pixel: ?u32 = null,
    override_redirect: ?u32 = null,
    save_under: ?u32 = null,
    event_mask: ?u32 = null,
    do_not_propogate_mask: ?u32 = null,
    colormap: ?Colormap = null,
    cursor: ?Cursor = null,
};

pub const CreateWindowValueListSpec = struct {
    pub const fields = .{
        .{ .name = "background_pixmap", .bit = @intFromEnum(CW.BackPixmap), .value_type = Pixmap },
        .{ .name = "background_pixel", .bit = @intFromEnum(CW.BackPixel), .value_type = u32 },
        .{ .name = "border_pixmap", .bit = @intFromEnum(CW.BorderPixmap), .value_type = Pixmap },
        .{ .name = "border_pixel", .bit = @intFromEnum(CW.BorderPixel), .value_type = u32 },
        .{ .name = "bit_gravity", .bit = @intFromEnum(CW.BitGravity), .value_type = Gravity },
        .{ .name = "win_gravity", .bit = @intFromEnum(CW.WinGravity), .value_type = Gravity },
        .{ .name = "backing_store", .bit = @intFromEnum(CW.BackingStore), .value_type = BackingStore },
        .{ .name = "backing_planes", .bit = @intFromEnum(CW.BackingPlanes), .value_type = u32 },
        .{ .name = "backing_pixel", .bit = @intFromEnum(CW.BackingPixel), .value_type = u32 },
        .{ .name = "override_redirect", .bit = @intFromEnum(CW.OverrideRedirect), .value_type = u32 },
        .{ .name = "save_under", .bit = @intFromEnum(CW.SaveUnder), .value_type = u32 },
        .{ .name = "event_mask", .bit = @intFromEnum(CW.EventMask), .value_type = u32 },
        .{ .name = "do_not_propogate_mask", .bit = @intFromEnum(CW.DontPropagate), .value_type = u32 },
        .{ .name = "colormap", .bit = @intFromEnum(CW.Colormap), .value_type = Colormap },
        .{ .name = "cursor", .bit = @intFromEnum(CW.Cursor), .value_type = Cursor },
    };
};

pub const CreateWindow = struct {
    pub const opcode: u8 = 1;
    pub const Reply = void;

    depth: u8,
    wid: Window,
    parent: Window,
    x: i16,
    y: i16,
    width: u16,
    height: u16,
    border_width: u16,
    class: WindowClass,
    visual: u32,
    value_list: CreateWindowValueList,

    pub fn byteLen(self: @This()) usize {
        return 4 + 4 + 4 + 2 + 2 + 2 + 2 + 2 + 2 + 4 + 4 + wire.valueListByteLen(CreateWindowValueListSpec, self.value_list);
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        const len = self.byteLen();
        const pad = wire.pad4(len);
        try writer.writeByte(opcode);
        try writer.writeByte(self.depth);
        try writer.writeInt(u16, @intCast((len + pad) / 4), .little);
        try writer.writeInt(u32, @intFromEnum(self.wid), .little);
        try writer.writeInt(u32, @intFromEnum(self.parent), .little);
        try writer.writeInt(i16, self.x, .little);
        try writer.writeInt(i16, self.y, .little);
        try writer.writeInt(u16, self.width, .little);
        try writer.writeInt(u16, self.height, .little);
        try writer.writeInt(u16, self.border_width, .little);
        try writer.writeInt(u16, @intCast(@intFromEnum(self.class)), .little);
        try writer.writeInt(u32, self.visual, .little);
        try writer.writeInt(u32, wire.computeValueMask(CreateWindowValueListSpec, self.value_list), .little);
        try wire.writeValueList(CreateWindowValueListSpec, self.value_list, writer);
        try writer.splatByteAll(0, pad);
    }
};

pub const MapWindow = struct {
    pub const opcode: u8 = 8;
    pub const Reply = void;

    window: Window,

    pub fn byteLen(self: @This()) usize {
        _ = self;
        return 4 + 4;
    }

    pub fn encode(self: @This(), writer: *std.Io.Writer) wire.Error!void {
        const len = self.byteLen();
        const pad = wire.pad4(len);
        try writer.writeByte(opcode);
        try writer.splatByteAll(0, 1);
        try writer.writeInt(u16, @intCast((len + pad) / 4), .little);
        try writer.writeInt(u32, @intFromEnum(self.window), .little);
        try writer.splatByteAll(0, pad);
    }
};

pub const KeyPressEvent = struct {
    detail: u8,
    time: u32,
    root: Window,
    event: Window,
    child: Window,
    root_x: i16,
    root_y: i16,
    event_x: i16,
    event_y: i16,
    state: u16,
    same_screen: bool,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        const detail = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        const time = try reader.takeInt(u32, .little);
        const root = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const child = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const root_x = try reader.takeInt(i16, .little);
        const root_y = try reader.takeInt(i16, .little);
        const event_x = try reader.takeInt(i16, .little);
        const event_y = try reader.takeInt(i16, .little);
        const state = try reader.takeInt(u16, .little);
        const same_screen = (try reader.takeByte()) != 0;
        _ = try reader.take(1);
        return .{
            .detail = detail,
            .time = time,
            .root = root,
            .event = event,
            .child = child,
            .root_x = root_x,
            .root_y = root_y,
            .event_x = event_x,
            .event_y = event_y,
            .state = state,
            .same_screen = same_screen,
        };
    }
};

pub const KeyReleaseEvent = struct {
    detail: u8,
    time: u32,
    root: Window,
    event: Window,
    child: Window,
    root_x: i16,
    root_y: i16,
    event_x: i16,
    event_y: i16,
    state: u16,
    same_screen: bool,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        const detail = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        const time = try reader.takeInt(u32, .little);
        const root = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const child = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const root_x = try reader.takeInt(i16, .little);
        const root_y = try reader.takeInt(i16, .little);
        const event_x = try reader.takeInt(i16, .little);
        const event_y = try reader.takeInt(i16, .little);
        const state = try reader.takeInt(u16, .little);
        const same_screen = (try reader.takeByte()) != 0;
        _ = try reader.take(1);
        return .{
            .detail = detail,
            .time = time,
            .root = root,
            .event = event,
            .child = child,
            .root_x = root_x,
            .root_y = root_y,
            .event_x = event_x,
            .event_y = event_y,
            .state = state,
            .same_screen = same_screen,
        };
    }
};

pub const ButtonPressEvent = struct {
    detail: u8,
    time: u32,
    root: Window,
    event: Window,
    child: Window,
    root_x: i16,
    root_y: i16,
    event_x: i16,
    event_y: i16,
    state: u16,
    same_screen: bool,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        const detail = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        const time = try reader.takeInt(u32, .little);
        const root = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const child = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const root_x = try reader.takeInt(i16, .little);
        const root_y = try reader.takeInt(i16, .little);
        const event_x = try reader.takeInt(i16, .little);
        const event_y = try reader.takeInt(i16, .little);
        const state = try reader.takeInt(u16, .little);
        const same_screen = (try reader.takeByte()) != 0;
        _ = try reader.take(1);
        return .{
            .detail = detail,
            .time = time,
            .root = root,
            .event = event,
            .child = child,
            .root_x = root_x,
            .root_y = root_y,
            .event_x = event_x,
            .event_y = event_y,
            .state = state,
            .same_screen = same_screen,
        };
    }
};

pub const ButtonReleaseEvent = struct {
    detail: u8,
    time: u32,
    root: Window,
    event: Window,
    child: Window,
    root_x: i16,
    root_y: i16,
    event_x: i16,
    event_y: i16,
    state: u16,
    same_screen: bool,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        const detail = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        const time = try reader.takeInt(u32, .little);
        const root = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const child = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const root_x = try reader.takeInt(i16, .little);
        const root_y = try reader.takeInt(i16, .little);
        const event_x = try reader.takeInt(i16, .little);
        const event_y = try reader.takeInt(i16, .little);
        const state = try reader.takeInt(u16, .little);
        const same_screen = (try reader.takeByte()) != 0;
        _ = try reader.take(1);
        return .{
            .detail = detail,
            .time = time,
            .root = root,
            .event = event,
            .child = child,
            .root_x = root_x,
            .root_y = root_y,
            .event_x = event_x,
            .event_y = event_y,
            .state = state,
            .same_screen = same_screen,
        };
    }
};

pub const MotionNotifyEvent = struct {
    detail: Motion,
    time: u32,
    root: Window,
    event: Window,
    child: Window,
    root_x: i16,
    root_y: i16,
    event_x: i16,
    event_y: i16,
    state: u16,
    same_screen: bool,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        const detail = @as(Motion, @enumFromInt(try reader.takeInt(u8, .little)));
        _ = try reader.takeInt(u16, .little);
        const time = try reader.takeInt(u32, .little);
        const root = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const child = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const root_x = try reader.takeInt(i16, .little);
        const root_y = try reader.takeInt(i16, .little);
        const event_x = try reader.takeInt(i16, .little);
        const event_y = try reader.takeInt(i16, .little);
        const state = try reader.takeInt(u16, .little);
        const same_screen = (try reader.takeByte()) != 0;
        _ = try reader.take(1);
        return .{
            .detail = detail,
            .time = time,
            .root = root,
            .event = event,
            .child = child,
            .root_x = root_x,
            .root_y = root_y,
            .event_x = event_x,
            .event_y = event_y,
            .state = state,
            .same_screen = same_screen,
        };
    }
};

pub const EnterNotifyEvent = struct {
    detail: NotifyDetail,
    time: u32,
    root: Window,
    event: Window,
    child: Window,
    root_x: i16,
    root_y: i16,
    event_x: i16,
    event_y: i16,
    state: u16,
    mode: NotifyMode,
    same_screen_focus: u8,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        const detail = @as(NotifyDetail, @enumFromInt(try reader.takeInt(u8, .little)));
        _ = try reader.takeInt(u16, .little);
        const time = try reader.takeInt(u32, .little);
        const root = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const child = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const root_x = try reader.takeInt(i16, .little);
        const root_y = try reader.takeInt(i16, .little);
        const event_x = try reader.takeInt(i16, .little);
        const event_y = try reader.takeInt(i16, .little);
        const state = try reader.takeInt(u16, .little);
        const mode = @as(NotifyMode, @enumFromInt(try reader.takeInt(u8, .little)));
        const same_screen_focus = try reader.takeByte();
        return .{
            .detail = detail,
            .time = time,
            .root = root,
            .event = event,
            .child = child,
            .root_x = root_x,
            .root_y = root_y,
            .event_x = event_x,
            .event_y = event_y,
            .state = state,
            .mode = mode,
            .same_screen_focus = same_screen_focus,
        };
    }
};

pub const LeaveNotifyEvent = struct {
    detail: NotifyDetail,
    time: u32,
    root: Window,
    event: Window,
    child: Window,
    root_x: i16,
    root_y: i16,
    event_x: i16,
    event_y: i16,
    state: u16,
    mode: NotifyMode,
    same_screen_focus: u8,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        const detail = @as(NotifyDetail, @enumFromInt(try reader.takeInt(u8, .little)));
        _ = try reader.takeInt(u16, .little);
        const time = try reader.takeInt(u32, .little);
        const root = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const child = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const root_x = try reader.takeInt(i16, .little);
        const root_y = try reader.takeInt(i16, .little);
        const event_x = try reader.takeInt(i16, .little);
        const event_y = try reader.takeInt(i16, .little);
        const state = try reader.takeInt(u16, .little);
        const mode = @as(NotifyMode, @enumFromInt(try reader.takeInt(u8, .little)));
        const same_screen_focus = try reader.takeByte();
        return .{
            .detail = detail,
            .time = time,
            .root = root,
            .event = event,
            .child = child,
            .root_x = root_x,
            .root_y = root_y,
            .event_x = event_x,
            .event_y = event_y,
            .state = state,
            .mode = mode,
            .same_screen_focus = same_screen_focus,
        };
    }
};

pub const FocusInEvent = struct {
    detail: NotifyDetail,
    event: Window,
    mode: NotifyMode,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        const detail = @as(NotifyDetail, @enumFromInt(try reader.takeInt(u8, .little)));
        _ = try reader.takeInt(u16, .little);
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const mode = @as(NotifyMode, @enumFromInt(try reader.takeInt(u8, .little)));
        _ = try reader.take(3);
        return .{
            .detail = detail,
            .event = event,
            .mode = mode,
        };
    }
};

pub const FocusOutEvent = struct {
    detail: NotifyDetail,
    event: Window,
    mode: NotifyMode,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        const detail = @as(NotifyDetail, @enumFromInt(try reader.takeInt(u8, .little)));
        _ = try reader.takeInt(u16, .little);
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const mode = @as(NotifyMode, @enumFromInt(try reader.takeInt(u8, .little)));
        _ = try reader.take(3);
        return .{
            .detail = detail,
            .event = event,
            .mode = mode,
        };
    }
};

pub const KeymapNotifyEvent = struct {
    keys: [31]u8,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        var keys: [31]u8 = undefined;
        @memcpy(keys[0..], try reader.take(31));
        return .{
            .keys = keys,
        };
    }
};

pub const ExposeEvent = struct {
    window: Window,
    x: u16,
    y: u16,
    width: u16,
    height: u16,
    count: u16,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const x = try reader.takeInt(u16, .little);
        const y = try reader.takeInt(u16, .little);
        const width = try reader.takeInt(u16, .little);
        const height = try reader.takeInt(u16, .little);
        const count = try reader.takeInt(u16, .little);
        _ = try reader.take(2);
        return .{
            .window = window,
            .x = x,
            .y = y,
            .width = width,
            .height = height,
            .count = count,
        };
    }
};

pub const GraphicsExposureEvent = struct {
    drawable: Drawable,
    x: u16,
    y: u16,
    width: u16,
    height: u16,
    minor_opcode: u16,
    count: u16,
    major_opcode: u8,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const drawable = @as(Drawable, @enumFromInt(try reader.takeInt(u32, .little)));
        const x = try reader.takeInt(u16, .little);
        const y = try reader.takeInt(u16, .little);
        const width = try reader.takeInt(u16, .little);
        const height = try reader.takeInt(u16, .little);
        const minor_opcode = try reader.takeInt(u16, .little);
        const count = try reader.takeInt(u16, .little);
        const major_opcode = try reader.takeByte();
        _ = try reader.take(3);
        return .{
            .drawable = drawable,
            .x = x,
            .y = y,
            .width = width,
            .height = height,
            .minor_opcode = minor_opcode,
            .count = count,
            .major_opcode = major_opcode,
        };
    }
};

pub const NoExposureEvent = struct {
    drawable: Drawable,
    minor_opcode: u16,
    major_opcode: u8,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const drawable = @as(Drawable, @enumFromInt(try reader.takeInt(u32, .little)));
        const minor_opcode = try reader.takeInt(u16, .little);
        const major_opcode = try reader.takeByte();
        _ = try reader.take(1);
        return .{
            .drawable = drawable,
            .minor_opcode = minor_opcode,
            .major_opcode = major_opcode,
        };
    }
};

pub const VisibilityNotifyEvent = struct {
    window: Window,
    state: Visibility,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const state = @as(Visibility, @enumFromInt(try reader.takeInt(u8, .little)));
        _ = try reader.take(3);
        return .{
            .window = window,
            .state = state,
        };
    }
};

pub const CreateNotifyEvent = struct {
    parent: Window,
    window: Window,
    x: i16,
    y: i16,
    width: u16,
    height: u16,
    border_width: u16,
    override_redirect: bool,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const parent = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const x = try reader.takeInt(i16, .little);
        const y = try reader.takeInt(i16, .little);
        const width = try reader.takeInt(u16, .little);
        const height = try reader.takeInt(u16, .little);
        const border_width = try reader.takeInt(u16, .little);
        const override_redirect = (try reader.takeByte()) != 0;
        _ = try reader.take(1);
        return .{
            .parent = parent,
            .window = window,
            .x = x,
            .y = y,
            .width = width,
            .height = height,
            .border_width = border_width,
            .override_redirect = override_redirect,
        };
    }
};

pub const DestroyNotifyEvent = struct {
    event: Window,
    window: Window,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        return .{
            .event = event,
            .window = window,
        };
    }
};

pub const UnmapNotifyEvent = struct {
    event: Window,
    window: Window,
    from_configure: bool,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const from_configure = (try reader.takeByte()) != 0;
        _ = try reader.take(3);
        return .{
            .event = event,
            .window = window,
            .from_configure = from_configure,
        };
    }
};

pub const MapNotifyEvent = struct {
    event: Window,
    window: Window,
    override_redirect: bool,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const override_redirect = (try reader.takeByte()) != 0;
        _ = try reader.take(3);
        return .{
            .event = event,
            .window = window,
            .override_redirect = override_redirect,
        };
    }
};

pub const MapRequestEvent = struct {
    parent: Window,
    window: Window,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const parent = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        return .{
            .parent = parent,
            .window = window,
        };
    }
};

pub const ReparentNotifyEvent = struct {
    event: Window,
    window: Window,
    parent: Window,
    x: i16,
    y: i16,
    override_redirect: bool,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const parent = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const x = try reader.takeInt(i16, .little);
        const y = try reader.takeInt(i16, .little);
        const override_redirect = (try reader.takeByte()) != 0;
        _ = try reader.take(3);
        return .{
            .event = event,
            .window = window,
            .parent = parent,
            .x = x,
            .y = y,
            .override_redirect = override_redirect,
        };
    }
};

pub const ConfigureNotifyEvent = struct {
    event: Window,
    window: Window,
    above_sibling: Window,
    x: i16,
    y: i16,
    width: u16,
    height: u16,
    border_width: u16,
    override_redirect: bool,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const above_sibling = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const x = try reader.takeInt(i16, .little);
        const y = try reader.takeInt(i16, .little);
        const width = try reader.takeInt(u16, .little);
        const height = try reader.takeInt(u16, .little);
        const border_width = try reader.takeInt(u16, .little);
        const override_redirect = (try reader.takeByte()) != 0;
        _ = try reader.take(1);
        return .{
            .event = event,
            .window = window,
            .above_sibling = above_sibling,
            .x = x,
            .y = y,
            .width = width,
            .height = height,
            .border_width = border_width,
            .override_redirect = override_redirect,
        };
    }
};

pub const ConfigureRequestEvent = struct {
    stack_mode: StackMode,
    parent: Window,
    window: Window,
    sibling: Window,
    x: i16,
    y: i16,
    width: u16,
    height: u16,
    border_width: u16,
    value_mask: u16,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        const stack_mode = @as(StackMode, @enumFromInt(try reader.takeInt(u8, .little)));
        _ = try reader.takeInt(u16, .little);
        const parent = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const sibling = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const x = try reader.takeInt(i16, .little);
        const y = try reader.takeInt(i16, .little);
        const width = try reader.takeInt(u16, .little);
        const height = try reader.takeInt(u16, .little);
        const border_width = try reader.takeInt(u16, .little);
        const value_mask = try reader.takeInt(u16, .little);
        return .{
            .stack_mode = stack_mode,
            .parent = parent,
            .window = window,
            .sibling = sibling,
            .x = x,
            .y = y,
            .width = width,
            .height = height,
            .border_width = border_width,
            .value_mask = value_mask,
        };
    }
};

pub const GravityNotifyEvent = struct {
    event: Window,
    window: Window,
    x: i16,
    y: i16,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const x = try reader.takeInt(i16, .little);
        const y = try reader.takeInt(i16, .little);
        return .{
            .event = event,
            .window = window,
            .x = x,
            .y = y,
        };
    }
};

pub const ResizeRequestEvent = struct {
    window: Window,
    width: u16,
    height: u16,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const width = try reader.takeInt(u16, .little);
        const height = try reader.takeInt(u16, .little);
        return .{
            .window = window,
            .width = width,
            .height = height,
        };
    }
};

pub const CirculateNotifyEvent = struct {
    event: Window,
    window: Window,
    place: Place,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        _ = try reader.take(4);
        const place = @as(Place, @enumFromInt(try reader.takeInt(u8, .little)));
        _ = try reader.take(3);
        return .{
            .event = event,
            .window = window,
            .place = place,
        };
    }
};

pub const CirculateRequestEvent = struct {
    event: Window,
    window: Window,
    place: Place,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const event = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        _ = try reader.take(4);
        const place = @as(Place, @enumFromInt(try reader.takeInt(u8, .little)));
        _ = try reader.take(3);
        return .{
            .event = event,
            .window = window,
            .place = place,
        };
    }
};

pub const PropertyNotifyEvent = struct {
    window: Window,
    atom: Atom,
    time: u32,
    state: Property,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const atom = @as(Atom, @enumFromInt(try reader.takeInt(u32, .little)));
        const time = try reader.takeInt(u32, .little);
        const state = @as(Property, @enumFromInt(try reader.takeInt(u8, .little)));
        _ = try reader.take(3);
        return .{
            .window = window,
            .atom = atom,
            .time = time,
            .state = state,
        };
    }
};

pub const SelectionClearEvent = struct {
    time: u32,
    owner: Window,
    selection: Atom,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const time = try reader.takeInt(u32, .little);
        const owner = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const selection = @as(Atom, @enumFromInt(try reader.takeInt(u32, .little)));
        return .{
            .time = time,
            .owner = owner,
            .selection = selection,
        };
    }
};

pub const SelectionRequestEvent = struct {
    time: u32,
    owner: Window,
    requestor: Window,
    selection: Atom,
    target: Atom,
    property: Atom,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const time = try reader.takeInt(u32, .little);
        const owner = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const requestor = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const selection = @as(Atom, @enumFromInt(try reader.takeInt(u32, .little)));
        const target = @as(Atom, @enumFromInt(try reader.takeInt(u32, .little)));
        const property = @as(Atom, @enumFromInt(try reader.takeInt(u32, .little)));
        return .{
            .time = time,
            .owner = owner,
            .requestor = requestor,
            .selection = selection,
            .target = target,
            .property = property,
        };
    }
};

pub const SelectionNotifyEvent = struct {
    time: u32,
    requestor: Window,
    selection: Atom,
    target: Atom,
    property: Atom,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const time = try reader.takeInt(u32, .little);
        const requestor = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const selection = @as(Atom, @enumFromInt(try reader.takeInt(u32, .little)));
        const target = @as(Atom, @enumFromInt(try reader.takeInt(u32, .little)));
        const property = @as(Atom, @enumFromInt(try reader.takeInt(u32, .little)));
        return .{
            .time = time,
            .requestor = requestor,
            .selection = selection,
            .target = target,
            .property = property,
        };
    }
};

pub const ColormapNotifyEvent = struct {
    window: Window,
    colormap: Colormap,
    new: bool,
    state: ColormapState,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const colormap = @as(Colormap, @enumFromInt(try reader.takeInt(u32, .little)));
        const new = (try reader.takeByte()) != 0;
        const state = @as(ColormapState, @enumFromInt(try reader.takeInt(u8, .little)));
        _ = try reader.take(2);
        return .{
            .window = window,
            .colormap = colormap,
            .new = new,
            .state = state,
        };
    }
};

pub const ClientMessageEvent = struct {
    format: u8,
    window: Window,
    type: Atom,
    data: ClientMessageData,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        const format = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        const window = @as(Window, @enumFromInt(try reader.takeInt(u32, .little)));
        const @"type" = @as(Atom, @enumFromInt(try reader.takeInt(u32, .little)));
        const data = try ClientMessageData.decode(reader);
        return .{
            .format = format,
            .window = window,
            .type = @"type",
            .data = data,
        };
    }
};

pub const MappingNotifyEvent = struct {
    request: Mapping,
    first_keycode: u8,
    count: u8,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        _ = try reader.take(1);
        _ = try reader.takeInt(u16, .little);
        const request = @as(Mapping, @enumFromInt(try reader.takeInt(u8, .little)));
        const first_keycode = try reader.takeByte();
        const count = try reader.takeByte();
        _ = try reader.take(1);
        return .{
            .request = request,
            .first_keycode = first_keycode,
            .count = count,
        };
    }
};

pub const GeGenericEvent = struct {
    extension: u8,
    length: u32,
    event_type: u16,
    full_sequence: u32,

    pub fn decode(reader: *std.Io.Reader) wire.Error!@This() {
        _ = try reader.takeByte();
        const extension = try reader.takeByte();
        _ = try reader.takeInt(u16, .little);
        const length = try reader.takeInt(u32, .little);
        const event_type = try reader.takeInt(u16, .little);
        _ = try reader.take(2);
        const full_sequence = try reader.takeInt(u32, .little);
        _ = try reader.take(16);
        _ = try reader.take(@as(usize, length) * 4);
        return .{
            .extension = extension,
            .length = length,
            .event_type = event_type,
            .full_sequence = full_sequence,
        };
    }
};

pub const UnknownEvent = struct {
    code: u8,
    sequence: u16,
    raw: [32]u8,
};

pub const Event = union(enum) {
    unknown: UnknownEvent,
    KeyPress: KeyPressEvent,
    KeyRelease: KeyReleaseEvent,
    ButtonPress: ButtonPressEvent,
    ButtonRelease: ButtonReleaseEvent,
    MotionNotify: MotionNotifyEvent,
    EnterNotify: EnterNotifyEvent,
    LeaveNotify: LeaveNotifyEvent,
    FocusIn: FocusInEvent,
    FocusOut: FocusOutEvent,
    KeymapNotify: KeymapNotifyEvent,
    Expose: ExposeEvent,
    GraphicsExposure: GraphicsExposureEvent,
    NoExposure: NoExposureEvent,
    VisibilityNotify: VisibilityNotifyEvent,
    CreateNotify: CreateNotifyEvent,
    DestroyNotify: DestroyNotifyEvent,
    UnmapNotify: UnmapNotifyEvent,
    MapNotify: MapNotifyEvent,
    MapRequest: MapRequestEvent,
    ReparentNotify: ReparentNotifyEvent,
    ConfigureNotify: ConfigureNotifyEvent,
    ConfigureRequest: ConfigureRequestEvent,
    GravityNotify: GravityNotifyEvent,
    ResizeRequest: ResizeRequestEvent,
    CirculateNotify: CirculateNotifyEvent,
    CirculateRequest: CirculateRequestEvent,
    PropertyNotify: PropertyNotifyEvent,
    SelectionClear: SelectionClearEvent,
    SelectionRequest: SelectionRequestEvent,
    SelectionNotify: SelectionNotifyEvent,
    ColormapNotify: ColormapNotifyEvent,
    ClientMessage: ClientMessageEvent,
    MappingNotify: MappingNotifyEvent,
    GeGeneric: GeGenericEvent,
};

pub fn decodeEvent(reader: *std.Io.Reader) wire.Error!Event {
    const code = (try reader.peek(1))[0] & 0x7f;
    return switch (code) {
        2 => .{ .KeyPress = try KeyPressEvent.decode(reader) },
        3 => .{ .KeyRelease = try KeyReleaseEvent.decode(reader) },
        4 => .{ .ButtonPress = try ButtonPressEvent.decode(reader) },
        5 => .{ .ButtonRelease = try ButtonReleaseEvent.decode(reader) },
        6 => .{ .MotionNotify = try MotionNotifyEvent.decode(reader) },
        7 => .{ .EnterNotify = try EnterNotifyEvent.decode(reader) },
        8 => .{ .LeaveNotify = try LeaveNotifyEvent.decode(reader) },
        9 => .{ .FocusIn = try FocusInEvent.decode(reader) },
        10 => .{ .FocusOut = try FocusOutEvent.decode(reader) },
        11 => .{ .KeymapNotify = try KeymapNotifyEvent.decode(reader) },
        12 => .{ .Expose = try ExposeEvent.decode(reader) },
        13 => .{ .GraphicsExposure = try GraphicsExposureEvent.decode(reader) },
        14 => .{ .NoExposure = try NoExposureEvent.decode(reader) },
        15 => .{ .VisibilityNotify = try VisibilityNotifyEvent.decode(reader) },
        16 => .{ .CreateNotify = try CreateNotifyEvent.decode(reader) },
        17 => .{ .DestroyNotify = try DestroyNotifyEvent.decode(reader) },
        18 => .{ .UnmapNotify = try UnmapNotifyEvent.decode(reader) },
        19 => .{ .MapNotify = try MapNotifyEvent.decode(reader) },
        20 => .{ .MapRequest = try MapRequestEvent.decode(reader) },
        21 => .{ .ReparentNotify = try ReparentNotifyEvent.decode(reader) },
        22 => .{ .ConfigureNotify = try ConfigureNotifyEvent.decode(reader) },
        23 => .{ .ConfigureRequest = try ConfigureRequestEvent.decode(reader) },
        24 => .{ .GravityNotify = try GravityNotifyEvent.decode(reader) },
        25 => .{ .ResizeRequest = try ResizeRequestEvent.decode(reader) },
        26 => .{ .CirculateNotify = try CirculateNotifyEvent.decode(reader) },
        27 => .{ .CirculateRequest = try CirculateRequestEvent.decode(reader) },
        28 => .{ .PropertyNotify = try PropertyNotifyEvent.decode(reader) },
        29 => .{ .SelectionClear = try SelectionClearEvent.decode(reader) },
        30 => .{ .SelectionRequest = try SelectionRequestEvent.decode(reader) },
        31 => .{ .SelectionNotify = try SelectionNotifyEvent.decode(reader) },
        32 => .{ .ColormapNotify = try ColormapNotifyEvent.decode(reader) },
        33 => .{ .ClientMessage = try ClientMessageEvent.decode(reader) },
        34 => .{ .MappingNotify = try MappingNotifyEvent.decode(reader) },
        35 => .{ .GeGeneric = try GeGenericEvent.decode(reader) },
        else => blk: {
            const packet = try reader.take(32);
            var raw: [32]u8 = undefined;
            @memcpy(raw[0..], packet);
            break :blk .{ .unknown = .{
                .code = packet[0] & 0x7f,
                .sequence = std.mem.readInt(u16, packet[2..4], .little),
                .raw = raw,
            } };
        },
    };
}
